"""Revision candidates generated by research or operators."""

from __future__ import annotations

from app.extensions import db
from app.utils.time_utils import utc_now as _utc_now


class NarrativeRevisionCandidate(db.Model):
    """Structured revision proposal that stays review-bound until approved."""

    __tablename__ = "narrative_revision_candidates"

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    revision_id = db.Column(db.String(64), nullable=False, unique=True, index=True)
    module_id = db.Column(db.String(128), nullable=False, index=True)
    source_finding_id = db.Column(db.String(64), nullable=True, index=True)
    target_kind = db.Column(db.String(64), nullable=False)
    target_ref = db.Column(db.String(255), nullable=False)
    operation = db.Column(db.String(64), nullable=False)
    structured_delta_json = db.Column(db.JSON, nullable=False, default=dict)
    expected_effects_json = db.Column(db.JSON, nullable=False, default=list)
    risk_flags_json = db.Column(db.JSON, nullable=False, default=list)
    review_status = db.Column(db.String(32), nullable=False, index=True)
    requires_review = db.Column(db.Boolean, nullable=False, default=True)
    mutation_allowed = db.Column(db.Boolean, nullable=False, default=False)
    created_by = db.Column(db.String(128), nullable=True)
    created_at = db.Column(db.DateTime(timezone=True), nullable=False, default=_utc_now)
    updated_at = db.Column(db.DateTime(timezone=True), nullable=False, default=_utc_now, onupdate=_utc_now)

    __table_args__ = (
        db.Index(
            "ix_narrative_revision_candidates_module_target",
            "module_id",
            "target_kind",
            "target_ref",
        ),
    )

    def to_dict(self) -> dict[str, str | bool | dict[str, object] | list[object] | None]:
        """Serialize revision candidate."""
        return {
            "revision_id": self.revision_id,
            "module_id": self.module_id,
            "source_finding_id": self.source_finding_id,
            "target_kind": self.target_kind,
            "target_ref": self.target_ref,
            "operation": self.operation,
            "structured_delta": self.structured_delta_json or {},
            "expected_effects": self.expected_effects_json or [],
            "risk_flags": self.risk_flags_json or [],
            "review_status": self.review_status,
            "requires_review": bool(self.requires_review),
            "mutation_allowed": bool(self.mutation_allowed),
            "created_by": self.created_by,
            "created_at": self.created_at.isoformat() if self.created_at else None,
            "updated_at": self.updated_at.isoformat() if self.updated_at else None,
        }
