"""Actor-lane scope and reconciliation.

Prunes out-of-scope structured actor lines and reconciles model responder claims against the director-selected responder scope.
"""
SOURCE_LINES = [
    'def _prune_out_of_scope_actor_lanes(\n',
    '    generation: dict[str, Any], out_of_scope_actors: list[str]\n',
    ') -> dict[str, str]:\n',
    '    """Prune out-of-scope actors from spoken_lines and action_lines in structured output.\n',
    '\n',
    '    Returns a dict with pruning stats for telemetry.\n',
    '    """\n',
    '    if not out_of_scope_actors:\n',
    '        return {"spoken_lines_pruned": 0, "action_lines_pruned": 0}\n',
    '\n',
    '    meta = generation.get("metadata") if isinstance(generation.get("metadata"), dict) else {}\n',
    '    structured = meta.get("structured_output") if isinstance(meta.get("structured_output"), dict) else {}\n',
    '    if not structured:\n',
    '        return {"spoken_lines_pruned": 0, "action_lines_pruned": 0}\n',
    '\n',
    '    out_of_scope_set = set(out_of_scope_actors)\n',
    '    spoken_lines_pruned = 0\n',
    '    action_lines_pruned = 0\n',
    '\n',
    '    spoken_lines = structured.get("spoken_lines")\n',
    '    if isinstance(spoken_lines, list):\n',
    '        filtered = []\n',
    '        for row in spoken_lines:\n',
    '            if isinstance(row, dict):\n',
    '                speaker_id = row.get("speaker_id")\n',
    '                if isinstance(speaker_id, str) and speaker_id.strip() in out_of_scope_set:\n',
    '                    spoken_lines_pruned += 1\n',
    '                    continue\n',
    '            filtered.append(row)\n',
    '        structured["spoken_lines"] = filtered\n',
    '\n',
    '    action_lines = structured.get("action_lines")\n',
    '    if isinstance(action_lines, list):\n',
    '        filtered = []\n',
    '        for row in action_lines:\n',
    '            if isinstance(row, dict):\n',
    '                actor_id = row.get("actor_id")\n',
    '                if isinstance(actor_id, str) and actor_id.strip() in out_of_scope_set:\n',
    '                    action_lines_pruned += 1\n',
    '                    continue\n',
    '            filtered.append(row)\n',
    '        structured["action_lines"] = filtered\n',
    '\n',
    '    return {"spoken_lines_pruned": spoken_lines_pruned, "action_lines_pruned": action_lines_pruned}\n',
    '\n',
    '\n',
    'def _reconcile_model_responders(\n',
    '    state: "RuntimeTurnState", generation: dict[str, Any]\n',
    ') -> dict[str, Any]:\n',
    '    """Check the model\'s proposed responders against the director\'s scope.\n',
    '\n',
    '    The model may propose a ``responder_id`` and/or a list of\n',
    "    ``responder_actor_ids`` in its structured output. The director's\n",
    '    ``selected_responder_set`` is the authoritative scope for the scene.\n',
    '    This helper computes the intersection, records the actors the model\n',
    '    introduced that were out of scope, and picks the final effective\n',
    "    responder — preferring the model's claim when it was in scope and\n",
    "    otherwise falling back to the director's first responder.\n",
    '\n',
    '    The returned dict lives on the runtime state as\n',
    '    ``responder_reconciliation`` and is surfaced on the governance surface\n',
    '    so operators can audit when and why a model responder claim was\n',
    '    dropped.\n',
    '    """\n',
    '    selected = state.get("selected_responder_set")\n',
    '    selected_list = selected if isinstance(selected, list) else []\n',
    '    director_actor_ids: list[str] = []\n',
    '    for row in selected_list:\n',
    '        if isinstance(row, dict):\n',
    '            aid = row.get("actor_id") or row.get("responder_id")\n',
    '            if isinstance(aid, str) and aid.strip():\n',
    '                director_actor_ids.append(aid.strip())\n',
    '    director_scope = set(director_actor_ids)\n',
    '\n',
    '    meta = generation.get("metadata") if isinstance(generation.get("metadata"), dict) else {}\n',
    '    structured = meta.get("structured_output") if isinstance(meta.get("structured_output"), dict) else {}\n',
    '\n',
    '    model_primary_raw = structured.get("primary_responder_id") or structured.get("responder_id")\n',
    '    model_primary = model_primary_raw.strip() if isinstance(model_primary_raw, str) else ""\n',
    '\n',
    '    model_scope_raw = structured.get("secondary_responder_ids")\n',
    '    if not isinstance(model_scope_raw, list):\n',
    '        model_scope_raw = structured.get("responder_actor_ids")\n',
    '    model_scope: list[str] = []\n',
    '    if isinstance(model_scope_raw, list):\n',
    '        for value in model_scope_raw:\n',
    '            if isinstance(value, str) and value.strip():\n',
    '                model_scope.append(value.strip())\n',
    '    if model_primary and model_primary not in model_scope:\n',
    '        model_scope.append(model_primary)\n',
    '\n',
    '    in_scope: list[str] = []\n',
    '    out_of_scope: list[str] = []\n',
    '    for actor in model_scope:\n',
    '        if not director_scope or actor in director_scope:\n',
    '            if actor not in in_scope:\n',
    '                in_scope.append(actor)\n',
    '        else:\n',
    '            if actor not in out_of_scope:\n',
    '                out_of_scope.append(actor)\n',
    '\n',
    '    if model_primary and model_primary in in_scope:\n',
    '        effective_primary = model_primary\n',
    '        reconciliation_outcome = "model_responder_accepted"\n',
    '    elif director_actor_ids:\n',
    '        effective_primary = director_actor_ids[0]\n',
    '        if model_primary and model_primary not in director_scope:\n',
    '            reconciliation_outcome = "model_responder_out_of_scope_dropped"\n',
    '        elif model_primary:\n',
    '            reconciliation_outcome = "model_responder_missing_from_director_scope"\n',
    '        else:\n',
    '            reconciliation_outcome = "director_primary_responder_used"\n',
    '    else:\n',
    '        effective_primary = model_primary or ""\n',
    '        reconciliation_outcome = (\n',
    '            "no_director_scope_available"\n',
    '            if not model_primary\n',
    '            else "no_director_scope_accepting_model_responder"\n',
    '        )\n',
    '\n',
    '    return {\n',
    '        "outcome": reconciliation_outcome,\n',
    '        "director_responder_scope": director_actor_ids,\n',
    '        "model_proposed_responder_id": model_primary or None,\n',
    '        "model_proposed_responder_scope": model_scope,\n',
    '        "effective_responder_id": effective_primary or None,\n',
    '        "effective_responder_scope": in_scope,\n',
    '        "dropped_out_of_scope_actors": out_of_scope,\n',
    '        "dropped_out_of_scope_count": len(out_of_scope),\n',
    '    }\n',
    '\n',
    '\n',
    '_ALLOWED_INITIATIVE_EVENT_TYPES = {"interrupt", "escalate", "withdraw", "deflect", "counter", "seize"}\n',
    '\n',
    '\n',
    'def _actor_lane_validation(\n',
    '    state: "RuntimeTurnState",\n',
    '    generation: dict[str, Any],\n',
    ') -> dict[str, Any]:\n',
    '    """Validate actor-lane legality without flattening actor-level structure."""\n',
    '    selected = state.get("selected_responder_set")\n',
    '    selected_list = selected if isinstance(selected, list) else []\n',
    '    director_actor_ids: list[str] = []\n',
    '    for row in selected_list:\n',
    '        if isinstance(row, dict):\n',
    '            aid = row.get("actor_id") or row.get("responder_id")\n',
    '            if isinstance(aid, str) and aid.strip():\n',
    '                director_actor_ids.append(aid.strip())\n',
    '\n',
    '    mind_records = state.get("character_mind_records")\n',
    '    if isinstance(mind_records, list):\n',
    '        for row in mind_records:\n',
    '            if isinstance(row, dict):\n',
    '                aid = row.get("runtime_actor_id") or row.get("character_key")\n',
    '                if isinstance(aid, str) and aid.strip():\n',
    '                    director_actor_ids.append(aid.strip())\n',
    '\n',
    '    allowed_actor_ids = sorted({aid for aid in director_actor_ids if aid})\n',
    '    allowed_scope: set[str] = set()\n',
    '    for aid in allowed_actor_ids:\n',
    '        allowed_scope.update(expand_goc_actor_id_aliases(aid))\n',
    '    allowed_scope.update(allowed_actor_ids)\n',
    '\n',
    '    meta = generation.get("metadata") if isinstance(generation.get("metadata"), dict) else {}\n',
    '    structured = meta.get("structured_output") if isinstance(meta.get("structured_output"), dict) else {}\n',
    '    if not structured:\n',
    '        has_selected_responders = bool(allowed_actor_ids)\n',
    '        reason = (\n',
    '            "no_structured_actor_output_with_selected_responders"\n',
    '            if has_selected_responders\n',
    '            else "no_structured_actor_output"\n',
    '        )\n',
    '        return {\n',
    '            "status": "approved",\n',
    '            "reason": reason,\n',
    '            "allowed_actor_ids": allowed_actor_ids,\n',
    '            "illegal_actor_ids": [],\n',
    '            "invalid_initiative_types": [],\n',
    '            "scene_function_compatibility": "not_evaluated",\n',
    '            "checked_fields": [],\n',
]
