"""Actor-lane scene-function compatibility.

Completes actor-lane validation by checking initiative event types, scene-function compatibility, and diagnostic approval or rejection payloads.
"""
SOURCE_LINES = [
    '    aid = str(actor_id or "").strip()\n',
    '    if not aid:\n',
    '        return False\n',
    '    return aid in scope or (canonicalize_goc_actor_id(aid) or aid) in scope\n',
    '\n',
    '\n',
    'def _normalized_word_set(text: str) -> set[str]:\n',
    '    return {\n',
    '        item\n',
    '        for item in re.split(r"[^a-zA-ZÀ-ÿ0-9_]+", str(text or "").lower())\n',
    '        if len(item) >= 3\n',
    '    }\n',
    '\n',
    '\n',
    'def _authority_text_matches_player_action(text: str, frame: dict[str, Any]) -> bool:\n',
    '    """Generic overlap check against resolved semantic fields, without verb/language maps."""\n',
    '    blob = str(text or "").strip().lower()\n',
    '    if not blob:\n',
    '        return False\n',
    '    words = _normalized_word_set(blob)\n',
    '    target_terms: set[str] = set()\n',
    '    for value in (\n',
    '        frame.get("target_query"),\n',
    '        frame.get("resolved_target_id"),\n',
    '        (frame.get("resolved_target") or {}).get("matched_alias")\n',
    '        if isinstance(frame.get("resolved_target"), dict)\n',
    '        else None,\n',
    '        (frame.get("resolved_target") or {}).get("canonical_name")\n',
    '        if isinstance(frame.get("resolved_target"), dict)\n',
    '        else None,\n',
    '    ):\n',
    '        target_terms.update(_normalized_word_set(str(value or "")))\n',
    '    if target_terms:\n',
    '        return bool(words.intersection(target_terms))\n',
    '    raw_words = _normalized_word_set(str(frame.get("source_text") or frame.get("raw_text") or ""))\n',
    '    return len(raw_words.intersection(words)) >= 2\n',
    '\n',
    '\n',
    'def _npc_action_controls_human_actor(row: dict[str, Any], human_scope: set[str]) -> bool:\n',
    '    """Return True for structured NPC coercion targeting the player-owned actor."""\n',
    '    target_values: list[Any] = [\n',
    '        row.get("target_actor_id"),\n',
    '        row.get("target_actor"),\n',
    '        row.get("target_id"),\n',
    '    ]\n',
    '    target_actor_ids = row.get("target_actor_ids")\n',
    '    if isinstance(target_actor_ids, list):\n',
    '        target_values.extend(target_actor_ids)\n',
    '    target_ids = row.get("target_ids")\n',
    '    if isinstance(target_ids, list):\n',
    '        target_values.extend(target_ids)\n',
    '    if not any(_actor_in_scope(str(value or ""), human_scope) for value in target_values):\n',
    '        return False\n',
    '\n',
    '    for key in ("coercion_type", "action_type"):\n',
    '        value = str(row.get(key) or "").strip().lower()\n',
    '        if value in NPC_COERCIVE_ACTION_TYPES:\n',
    '            return True\n',
    '\n',
    '    words = _normalized_word_set(_row_text(row))\n',
    '    if words.intersection(NPC_ALLOWED_PRESSURE_VERBS):\n',
    '        return False\n',
    '    return bool(words.intersection(NPC_COERCIVE_CONTROL_VERBS))\n',
]
