"""Authority aspect record builders.

Builds narrator, NPC, and player-action authority records from structured generation output and runtime state.
"""
SOURCE_LINES = [
    'def _build_authority_aspect_records(\n',
    '    *,\n',
    '    state: "RuntimeTurnState",\n',
    '    generation: dict[str, Any],\n',
    '    proposed_state_effects: list[dict[str, Any]],\n',
    ') -> tuple[dict[str, Any], dict[str, Any]]:\n',
    '    structured = _structured_output_from_generation(generation)\n',
    '    interp = state.get("interpreted_input") if isinstance(state.get("interpreted_input"), dict) else {}\n',
    '    frame = state.get("player_action_frame") if isinstance(state.get("player_action_frame"), dict) else {}\n',
    '    aff = state.get("affordance_resolution") if isinstance(state.get("affordance_resolution"), dict) else {}\n',
    '    module_policy = state.get("module_runtime_policy") if isinstance(state.get("module_runtime_policy"), dict) else {}\n',
    '    authority_policy = (\n',
    '        module_policy.get("authority_policy")\n',
    '        if isinstance(module_policy.get("authority_policy"), dict)\n',
    '        else {}\n',
    '    )\n',
    '    capability_policy = (\n',
    '        module_policy.get("capability_policy")\n',
    '        if isinstance(module_policy.get("capability_policy"), dict)\n',
    '        else {}\n',
    '    )\n',
    '    turn_number = int(state.get("turn_number") or 0)\n',
    '    player_input_kind = str(frame.get("player_input_kind") or interp.get("player_input_kind") or "").strip().lower()\n',
    '    narrator_required = bool(frame.get("narrator_response_expected") or interp.get("narrator_response_expected"))\n',
    '    if is_narrator_only_player_input_kind(player_input_kind) or is_mixed_player_input_kind(player_input_kind):\n',
    '        narrator_required = True\n',
    '    if str(aff.get("requires_narrator") or "").strip().lower() == "true":\n',
    '        narrator_required = True\n',
    '    narrative_text = "\\n".join(\n',
    '        part\n',
    '        for part in (\n',
    '            narration_summary_to_plain_str(structured.get("narration_summary")),\n',
    '            str(structured.get("narrative_response") or "").strip(),\n',
    '            extract_proposed_narrative_text(proposed_state_effects),\n',
    '        )\n',
    '        if str(part or "").strip()\n',
    '    ).strip()\n',
    '    narrator_present = bool(narrative_text)\n',
    '    if turn_number <= 0 and narrator_present:\n',
    '        narrator_required = True\n',
    '    narrator_status = "passed"\n',
    '    narrator_failure_reason = None\n',
    '    if narrator_required and not narrator_present:\n',
    '        narrator_status = "failed"\n',
    '        narrator_failure_reason = "narrator_required_missing"\n',
    '    narrator_record = make_aspect_record(\n',
    '        applicable=bool(narrator_required or narrator_present),\n',
    '        status=narrator_status if (narrator_required or narrator_present) else "not_applicable",\n',
    '        expected={\n',
    '            "required": bool(narrator_required),\n',
    '            "expected_owner": "narrator" if narrator_required else None,\n',
    '            "reason": "player_action_or_perception_consequence"\n',
    '            if is_narrator_only_player_input_kind(player_input_kind) or is_mixed_player_input_kind(player_input_kind)\n',
    '            else "opening_or_optional_narration"\n',
    '            if narrator_required\n',
    '            else None,\n',
    '            "required_capabilities": [\n',
    '                NARRATOR_PERCEPTION_RESULT_DESCRIBE\n',
    '                if is_perception_like_player_input_kind(player_input_kind)\n',
    '                else NARRATOR_LOCATION_TRANSITION_DESCRIBE\n',
    '                if str(frame.get("action_kind") or "").strip().lower() == "movement"\n',
    '                else NARRATOR_OBJECT_STATE_DESCRIBE\n',
    '                if str(frame.get("action_kind") or "").strip().lower() == "object_interaction"\n',
    '                else NARRATOR_ACTION_CONSEQUENCE_DESCRIBE\n',
    '            ]\n',
    '            if narrator_required\n',
    '            else [],\n',
    '            "authority_policy_source": "module_runtime_policy"\n',
    '            if authority_policy\n',
    '            else "runtime_default",\n',
    '        },\n',
    '        actual={\n',
    '            "actual_owner": "narrator" if narrator_present else None,\n',
    '            "narrator_block_present": narrator_present,\n',
    '            "consequence_realized": narrator_present if narrator_required else None,\n',
    '            "narrative_text_present": narrator_present,\n',
    '        },\n',
    '        reasons=[] if narrator_failure_reason is None else [narrator_failure_reason],\n',
    '        source="runtime",\n',
    '        failure_class=None if narrator_failure_reason is None else "hard_contract_failure",\n',
    '        failure_reason=narrator_failure_reason,\n',
    '        expected_owner="narrator" if narrator_required else None,\n',
    '        actual_owner="narrator" if narrator_present else None,\n',
    '        missing_field="narration_summary" if narrator_failure_reason else None,\n',
    '    )\n',
    '\n',
    '    actor_lane_ctx = state.get("actor_lane_context") if isinstance(state.get("actor_lane_context"), dict) else {}\n',
    '    human_scope = _actor_alias_scope(\n',
    '        str(actor_lane_ctx.get("human_actor_id") or actor_lane_ctx.get("selected_player_role") or "").strip()\n',
    '    )\n',
    '    npc_scope: set[str] = set()\n',
    '    for raw_actor_id in actor_lane_ctx.get("npc_actor_ids") or []:\n',
    '        npc_scope.update(_actor_alias_scope(str(raw_actor_id or "").strip()))\n',
    '    spoken_rows = [row for row in structured.get("spoken_lines") or [] if isinstance(row, dict)]\n',
    '    action_rows = [row for row in structured.get("action_lines") or [] if isinstance(row, dict)]\n',
    '    offending_actor_id = None\n',
    '    offending_block_id = None\n',
    '    failure_reason = None\n',
    '\n',
    '    for row in spoken_rows:\n',
    '        sid = str(row.get("speaker_id") or "").strip()\n',
    '        if _actor_in_scope(sid, human_scope):\n',
    '            offending_actor_id = sid\n',
    '            offending_block_id = str(row.get("id") or row.get("block_id") or "")\n',
    '            failure_reason = AI_CONTROLLED_HUMAN_ACTOR_REASON\n',
    '            break\n',
    '        if is_perception_like_player_input_kind(player_input_kind) and not _actor_in_scope(sid, human_scope):\n',
    '            if _authority_text_matches_player_action(_row_text(row), frame):\n',
    '                offending_actor_id = sid or None\n',
    '                offending_block_id = str(row.get("id") or row.get("block_id") or "")\n',
    '                failure_reason = NPC_NARRATED_PLAYER_PERCEPTION_REASON\n',
    '                break\n',
    '    if failure_reason is None:\n',
    '        for row in action_rows:\n',
    '            aid = str(row.get("actor_id") or "").strip()\n',
    '            if _actor_in_scope(aid, human_scope):\n',
    '                offending_actor_id = aid\n',
    '                offending_block_id = str(row.get("id") or row.get("block_id") or "")\n',
    '                failure_reason = AI_CONTROLLED_HUMAN_ACTOR_REASON\n',
    '                break\n',
    '            if not _actor_in_scope(aid, human_scope) and _npc_action_controls_human_actor(row, human_scope):\n',
    '                offending_actor_id = aid or None\n',
    '                offending_block_id = str(row.get("id") or row.get("block_id") or "")\n',
    '                failure_reason = NPC_ACTION_CONTROLS_HUMAN_ACTOR_REASON\n',
    '                break\n',
    '            if _actor_in_scope(aid, npc_scope) and (\n',
    '                is_action_like_player_input_kind(player_input_kind)\n',
    '                or is_perception_like_player_input_kind(player_input_kind)\n',
    '                or is_mixed_player_input_kind(player_input_kind)\n',
    '            ):\n',
    '                if _authority_text_matches_player_action(_row_text(row), frame):\n',
    '                    offending_actor_id = aid\n',
    '                    offending_block_id = str(row.get("id") or row.get("block_id") or "")\n',
    '                    failure_reason = (\n',
    '                        NPC_NARRATED_PLAYER_PERCEPTION_REASON\n',
    '                        if is_perception_like_player_input_kind(player_input_kind)\n',
    '                        else NPC_EXECUTED_PLAYER_ACTION_REASON\n',
    '                    )\n',
    '                    break\n',
    '    npc_status = "failed" if failure_reason else "passed"\n',
    '    actual_npc_actors: list[str] = []\n',
    '    for row in spoken_rows:\n',
    '        sid = str(row.get("speaker_id") or "").strip()\n',
    '        if sid and sid not in actual_npc_actors:\n',
    '            actual_npc_actors.append(sid)\n',
    '    for row in action_rows:\n',
    '        aid = str(row.get("actor_id") or "").strip()\n',
    '        if aid and aid not in actual_npc_actors:\n',
    '            actual_npc_actors.append(aid)\n',
    '    policy_name = "direct_response" if is_speech_like_player_input_kind(player_input_kind) else "optional_social_reaction"\n',
    '    if not spoken_rows and not action_rows and not bool(interp.get("npc_response_expected")):\n',
    '        policy_name = "none"\n',
    '    forbidden_caps = [\n',
    '        str(item).strip()\n',
    '        for item in (capability_policy.get("forbidden") if isinstance(capability_policy.get("forbidden"), list) else [])\n',
    '        if str(item).strip()\n',
    '    ]\n',
    '    npc_record = make_aspect_record(\n',
    '        applicable=True,\n',
    '        status=npc_status,\n',
    '        expected={\n',
    '            "policy": policy_name,\n',
    '            "allowed_actors": sorted(npc_scope),\n',
    '            "allowed_capabilities": [\n',
    '                NPC_SOCIAL_REACTION_OPTIONAL,\n',
    '                NPC_DIRECT_ANSWER_ALLOWED,\n',
    '                NPC_ACTION_GESTURE_OPTIONAL,\n',
    '            ],\n',
    '            "forbidden_capabilities": forbidden_caps,\n',
    '            "authority_policy_source": "module_runtime_policy"\n',
    '            if authority_policy\n',
    '            else "runtime_default",\n',
    '        },\n',
    '        actual={\n',
    '            "spoken_line_count": len(spoken_rows),\n',
    '            "action_line_count": len(action_rows),\n',
    '            "actual_actors": actual_npc_actors,\n',
    '            "npc_takeover_detected": bool(failure_reason),\n',
    '            "offending_actor_id": offending_actor_id,\n',
    '            "offending_block_id": offending_block_id or None,\n',
]
