"""Voice profile and dispatch records.

Derives voice validation mode, voice profiles, ADR-0041 graph dispatch bundles, and voice consistency aspect records.
"""
SOURCE_LINES = [
    '        },\n',
    '        reasons=[] if failure_reason is None else [failure_reason],\n',
    '        source="runtime",\n',
    '        failure_class=None if failure_reason is None else "hard_contract_failure",\n',
    '        failure_reason=failure_reason,\n',
    '        offending_actor_id=offending_actor_id,\n',
    '        offending_block_id=offending_block_id or None,\n',
    '        expected_owner="narrator" if failure_reason == NPC_NARRATED_PLAYER_PERCEPTION_REASON else None,\n',
    '        actual_owner="npc" if failure_reason else None,\n',
    '    )\n',
    '    return narrator_record, npc_record\n',
    '\n',
    '\n',
    'def _voice_validation_mode_from_state(state: "RuntimeTurnState") -> str:\n',
    '    raw = str(\n',
    '        state.get("validation_execution_mode")\n',
    '        or state.get("validation_mode")\n',
    '        or "schema_plus_semantic"\n',
    '    ).strip().lower()\n',
    '    if raw not in {"schema_only", "schema_plus_semantic", "strict_rule_engine"}:\n',
    '        return "schema_plus_semantic"\n',
    '    return raw\n',
    '\n',
    '\n',
    'def _voice_profiles_from_state(state: "RuntimeTurnState") -> list[dict[str, Any]]:\n',
    '    profiles = state.get("character_voice_profiles")\n',
    '    if isinstance(profiles, list) and profiles:\n',
    '        return [row for row in profiles if isinstance(row, dict)]\n',
    '    if str(state.get("module_id") or "") != GOC_MODULE_ID:\n',
    '        return []\n',
    '    yslice = state.get("goc_yaml_slice") if isinstance(state.get("goc_yaml_slice"), dict) else None\n',
    '    if yslice is None:\n',
    '        try:\n',
    '            yslice = load_goc_yaml_slice_bundle()\n',
    '        except Exception:\n',
    '            yslice = None\n',
    '    active_keys: list[str] = []\n',
    '    minds = state.get("character_mind_records") if isinstance(state.get("character_mind_records"), list) else []\n',
    '    for row in minds:\n',
    '        if not isinstance(row, dict):\n',
    '            continue\n',
    '        key = str(row.get("character_key") or "").strip()\n',
    '        if key and key not in active_keys:\n',
    '            active_keys.append(key)\n',
    '    if not active_keys:\n',
    '        active_keys = _derive_active_character_keys(\n',
    '            yaml_slice=yslice,\n',
    '            primary_responder=(\n',
    '                state.get("selected_responder_set", [{}])[0]\n',
    '                if isinstance(state.get("selected_responder_set"), list)\n',
    '                and state.get("selected_responder_set")\n',
    '                and isinstance(state.get("selected_responder_set", [None])[0], dict)\n',
    '                else {}\n',
    '            ),\n',
    '            module_id=str(state.get("module_id") or ""),\n',
    '            module_runtime_policy=state.get("module_runtime_policy")\n',
    '            if isinstance(state.get("module_runtime_policy"), dict)\n',
    '            else None,\n',
    '        )\n',
    '    return [\n',
    '        profile.to_runtime_dict()\n',
    '        for profile in build_character_voice_profiles_for_goc(\n',
    '            yaml_slice=yslice,\n',
    '            active_character_keys=active_keys,\n',
    '            current_scene_id=str(state.get("current_scene_id") or ""),\n',
    '            module_id=str(state.get("module_id") or ""),\n',
    '        )\n',
    '    ]\n',
]
