"""Director W5 location projection.

Adds optional W5 projection support and blocker diagnostics for director gathering state.
"""
SOURCE_LINES = [
    '    existing completion helper so current-turn target movement and NPC fallback\n',
    '    semantics stay unchanged.\n',
    '\n',
    '    Phase 6B-3A — F1 lazy re-order: ``complete_actor_locations_for_gathering``\n',
    '    is now invoked only inside the two return paths that actually need its\n',
    '    output (the explicit-opt-out short-circuit and the malformed-W5 ``except``\n',
    '    branch). Under the default-on happy path the legacy completion is no\n',
    '    longer pre-computed; the W5 success branch already runs its own completion\n',
    '    call (F4) over W5-derived actor locations. Output is bit-for-bit identical\n',
    '    on D / O / M paths — only the placement of the legacy call changed.\n',
    '    """\n',
    '\n',
    '    enabled = (\n',
    '        w5_ast_director_projection_enabled()\n',
    '        if w5_director_projection_enabled is None\n',
    '        else bool(w5_director_projection_enabled)\n',
    '    )\n',
    '    if not enabled:\n',
    '        return {\n',
    '            "location_completion": complete_actor_locations_for_gathering(\n',
    '                actor_locations=actor_locations,\n',
    '                actor_lane_context=actor_lane_context,\n',
    '                current_step_scene_id=current_step_scene_id,\n',
    '                selected_human_actor_id=selected_human_actor_id,\n',
    '                free_player_action_resolution=free_player_action_resolution,\n',
    '                environment_current_room_id=environment_current_room_id,\n',
    '            ),\n',
    '            "diagnostics": {},\n',
    '            "w5_projection": None,\n',
    '        }\n',
    '\n',
    '    diagnostics: dict[str, Any] = {\n',
    '        "w5_director_projection_used": False,\n',
    '        "w5_director_projection_failed": None,\n',
    '        "w5_snapshot_id": None,\n',
    '        "derived_actor_locations_source": "baseline_completion",\n',
    '        "gathering_pause_source": "baseline_completion",\n',
    '    }\n',
    '    try:\n',
    '        if not isinstance(w5_latest_snapshot, dict):\n',
    '            raise ValueError("missing_w5_latest_snapshot")\n',
    '        projection = build_w5_projection_for_director(w5_latest_snapshot)\n',
    '        projection_payload = projection.to_dict()\n',
    '        where_summary = (\n',
    '            projection.where_summary if isinstance(projection.where_summary, dict) else {}\n',
    '        )\n',
    '        raw_locations = where_summary.get("derived_actor_locations")\n',
    '        if not isinstance(raw_locations, dict) or not raw_locations:\n',
    '            raise ValueError("w5_projection_missing_actor_locations")\n',
    '        w5_actor_locations = {\n',
    '            str(actor_id): str(location_id)\n',
    '            for actor_id, location_id in raw_locations.items()\n',
    '            if str(actor_id).strip() and str(location_id or "").strip()\n',
    '        }\n',
    '        if not w5_actor_locations:\n',
    '            raise ValueError("w5_projection_missing_actor_locations")\n',
    '\n',
    '        completion = complete_actor_locations_for_gathering(\n',
    '            actor_locations=w5_actor_locations,\n',
    '            actor_lane_context=actor_lane_context,\n',
    '            current_step_scene_id=current_step_scene_id,\n',
    '            selected_human_actor_id=selected_human_actor_id,\n',
    '            free_player_action_resolution=free_player_action_resolution,\n',
    '            environment_current_room_id=environment_current_room_id,\n',
    '        )\n',
    '        completion = dict(completion)\n',
    '        completion["source"] = "w5_projection_with_actor_lane_fallback"\n',
    '        diagnostics.update(\n',
    '            {\n',
    '                "w5_director_projection_used": True,\n',
    '                "w5_snapshot_id": where_summary.get("w5_snapshot_id"),\n',
    '                "derived_actor_locations_source": "w5_projection",\n',
    '                "gathering_pause_source": "w5_projection",\n',
    '            }\n',
    '        )\n',
    '        return {\n',
    '            "location_completion": completion,\n',
    '            "diagnostics": diagnostics,\n',
    '            "w5_projection": projection_payload,\n',
    '        }\n',
    '    except Exception as exc:\n',
    '        diagnostics["w5_director_projection_failed"] = _w5_director_projection_failure_reason(exc)\n',
    '        return {\n',
    '            "location_completion": complete_actor_locations_for_gathering(\n',
    '                actor_locations=actor_locations,\n',
    '                actor_lane_context=actor_lane_context,\n',
    '                current_step_scene_id=current_step_scene_id,\n',
    '                selected_human_actor_id=selected_human_actor_id,\n',
    '                free_player_action_resolution=free_player_action_resolution,\n',
    '                environment_current_room_id=environment_current_room_id,\n',
    '            ),\n',
    '            "diagnostics": diagnostics,\n',
    '            "w5_projection": None,\n',
    '        }\n',
    '\n',
    '\n',
    'def resolve_w5_first_actor_locations(\n',
    '    *,\n',
    '    legacy_actor_locations: dict[str, Any] | None,\n',
    '    w5_latest_snapshot: dict[str, Any] | None,\n',
    '    w5_director_projection_enabled: bool | None = None,\n',
    ') -> dict[str, Any]:\n',
    '    """Phase 6B-3A — F21/F22 W5-first actor_locations resolver.\n',
    '\n',
    '    Returns a typed dict with keys:\n',
    '\n',
    '        actor_locations: dict[str, str]\n',
    '            The resolved actor_locations map. Under the default-on happy path\n',
    '            this is the W5 ``where_summary.derived_actor_locations`` projection\n',
    '            output. Under explicit opt-out, malformed/missing W5, or an old\n',
    '            payload without ``w5_latest_snapshot`` the legacy substrate map is\n',
    '            returned verbatim.\n',
    '\n',
    '        source: str\n',
    '            One of:\n',
    '                ``"w5_projection"``           — default-on happy path; W5 won.\n',
    '                ``"explicit_opt_out_legacy"`` — W5_AST_DIRECTOR_PROJECTION_ENABLED=0/false/no/off.\n',
    '                ``"malformed_w5_fallback"``   — default-on but projection raised\n',
    '                                                  or returned no derived_actor_locations.\n',
    '                ``"old_payload_legacy"``      — default-on but no W5 snapshot in state\n',
    '                                                  (pre-Phase-1 session or missing wire-in).\n',
    '\n',
    '        w5_snapshot_id: str | None\n',
    '            The W5 snapshot id that produced the projection (only set when\n',
    '            ``source == "w5_projection"``).\n',
    '\n',
    '        failure_reason: str | None\n',
    '            Compact failure reason (only set when ``source == "malformed_w5_fallback"``).\n',
    '\n',
    '    No committed event or committed-output field is mutated. The helper is a\n',
    '    pure read-side classifier so executor_action_resolution_start /\n',
    '    executor_action_resolution_commit can identify the actor-location\n',
    '    substrate they are about to feed into\n',
    '    ``complete_actor_locations_for_gathering_with_optional_w5_projection``.\n',
    '\n',
    '    ADR-0061 pause semantics, Actor Lane authority, Commit/Readiness, the\n',
    '    Canonical Path, ADR-0033 commit semantics, and W5 validation semantics\n',
    '    are unchanged by this helper.\n',
    '    """\n',
    '\n',
    '    enabled = (\n',
    '        w5_ast_director_projection_enabled()\n',
    '        if w5_director_projection_enabled is None\n',
    '        else bool(w5_director_projection_enabled)\n',
    '    )\n',
    '    legacy_locations: dict[str, Any] = (\n',
    '        dict(legacy_actor_locations)\n',
    '        if isinstance(legacy_actor_locations, dict)\n',
    '        else {}\n',
    '    )\n',
    '    if not enabled:\n',
    '        return {\n',
    '            "actor_locations": legacy_locations,\n',
    '            "source": "explicit_opt_out_legacy",\n',
    '            "w5_snapshot_id": None,\n',
    '            "failure_reason": None,\n',
    '        }\n',
    '    if not isinstance(w5_latest_snapshot, dict) or not w5_latest_snapshot:\n',
    '        return {\n',
    '            "actor_locations": legacy_locations,\n',
    '            "source": "old_payload_legacy",\n',
    '            "w5_snapshot_id": None,\n',
    '            "failure_reason": None,\n',
    '        }\n',
    '    try:\n',
    '        projection = build_w5_projection_for_director(w5_latest_snapshot)\n',
    '        where_summary = (\n',
    '            projection.where_summary if isinstance(projection.where_summary, dict) else {}\n',
    '        )\n',
    '        raw_locations = where_summary.get("derived_actor_locations")\n',
    '        if not isinstance(raw_locations, dict) or not raw_locations:\n',
    '            raise ValueError("w5_projection_missing_actor_locations")\n',
    '        w5_locations = {\n',
    '            str(actor_id): str(location_id)\n',
    '            for actor_id, location_id in raw_locations.items()\n',
    '            if str(actor_id).strip() and str(location_id or "").strip()\n',
    '        }\n',
    '        if not w5_locations:\n',
    '            raise ValueError("w5_projection_missing_actor_locations")\n',
    '        return {\n',
    '            "actor_locations": w5_locations,\n',
    '            "source": "w5_projection",\n',
    '            "w5_snapshot_id": where_summary.get("w5_snapshot_id"),\n',
    '            "failure_reason": None,\n',
    '        }\n',
    '    except Exception as exc:\n',
    '        return {\n',
    '            "actor_locations": legacy_locations,\n',
    '            "source": "malformed_w5_fallback",\n',
    '            "w5_snapshot_id": None,\n',
    '            "failure_reason": _w5_director_projection_failure_reason(exc),\n',
    '        }\n',
    '\n',
    '\n',
    'def _director_gathering_blocker(\n',
    '    *,\n',
    '    reason: str,\n',
    '    presence_required_for_step: list[str] | None = None,\n',
    '    evidence_status: dict[str, Any] | None = None,\n',
    ') -> dict[str, Any]:\n',
    '    out: dict[str, Any] = {\n',
    '        "schema_version": "director_gathering_state.v1",\n',
    '        "paused": False,\n',
    '        "reason": reason,\n',
    '        "diagnostic_blocker": True,\n',
    '        "missing_actor_ids": [],\n',
    '        "presence_required_for_step": list(presence_required_for_step or []),\n',
    '    }\n',
    '    if evidence_status:\n',
    '        out["evidence_status"] = dict(evidence_status)\n',
    '    return out\n',
]
