"""Director location completion.

Derives named characters and current scene ids, then completes actor locations required for gathering-state decisions.
"""
SOURCE_LINES = [
    '        frame.get("selected_actor_id"),\n',
    '        frame.get("actor_id"),\n',
    '        state.get("player_actor_id"),\n',
    '        alc.get("human_actor_id"),\n',
    '        alc.get("selected_player_role"),\n',
    '    ):\n',
    '        text = str(value or "").strip()\n',
    '        if text:\n',
    '            return text\n',
    '    return None\n',
    '\n',
    '\n',
    'def complete_actor_locations_for_gathering(\n',
    '    *,\n',
    '    actor_locations: dict[str, Any] | None,\n',
    '    actor_lane_context: dict[str, Any] | None,\n',
    '    current_step_scene_id: str | None,\n',
    '    selected_human_actor_id: str | None = None,\n',
    '    free_player_action_resolution: dict[str, Any] | None = None,\n',
    '    environment_current_room_id: str | None = None,\n',
    ') -> dict[str, Any]:\n',
    '    """Complete actor_locations with actor_lane_context NPC fallback.\n',
    '\n',
    '    Resolution order for actor_locations:\n',
    '    1. Environment state / canonical actor_locations wins for any ID already\n',
    '       present.\n',
    '    2. Missing NPC IDs from ``actor_lane_context`` are defaulted to the best\n',
    '       available room-level location: ``environment_current_room_id`` first\n',
    '       (from ``environment_state.current_room_id`` — actual room, room-level),\n',
    '       then ``current_step_scene_id`` (which may be a coarse scene identifier).\n',
    "    3. The selected human actor's location is updated from the resolved\n",
    '       ``target_location`` in ``free_player_action_resolution`` when present.\n',
    '\n',
    '    Gathering scene derivation (Phase 1 without active room tracking):\n',
    '    NPCs do not move in Phase 1 — their actor_location IS the gathering room.\n',
    '    ``gathering_scene_id`` is therefore derived from the most common NPC\n',
    '    location in the completed actor_locations, not from ``current_step_scene_id``\n',
    '    (which may be a scene-level identifier like ``"scene_1"`` that does not\n',
    '    match room-level actor_location values).  This ensures that the topology\n',
    '    check in ``compute_gathering_state`` uses room-level IDs on both sides.\n',
    '\n',
    '    Fail-closed rule: when no fallback location is available (both\n',
    '    ``environment_current_room_id`` and ``current_step_scene_id`` are absent)\n',
    '    but there are NPC IDs missing from ``actor_locations``, return\n',
    '    ``diagnostic_blocker=True`` with reason ``missing_current_step_scene_id``.\n',
    '\n',
    '    No hardcoded actor IDs, room names, or module-specific content.\n',
    '\n',
    '    Returns a dict with keys:\n',
    '        actor_locations: completed mapping (copy, never mutates input)\n',
    '        gathering_scene_id: room-level ID to use for compute_gathering_state\n',
    '        source: "environment_state_with_actor_lane_fallback"\n',
    '        fallback_actor_ids: list of NPC IDs whose location was defaulted\n',
    '        original_actor_locations: the input actor_locations before completion\n',
    '        diagnostic_blocker: bool\n',
    '        reason: None or a DIAGNOSTIC_BLOCKER_* string\n',
    '    """\n',
    '    locations: dict[str, Any] = dict(actor_locations) if isinstance(actor_locations, dict) else {}\n',
    '    original_locations: dict[str, Any] = dict(locations)\n',
    '\n',
    '    alc = actor_lane_context if isinstance(actor_lane_context, dict) else {}\n',
    '\n',
    '    # NPC ID resolution order (ADR-0039 — no hardcoded roster):\n',
    '    # 1. npc_actor_ids   — explicit field used in some test fixtures / LDSS input builder\n',
    '    # 2. ai_allowed_actor_ids — live runtime path: ActorLaneContext.model_dump() uses this\n',
    '    # 3. actor_lanes entries with lane == "npc" — ultimate fallback\n',
    '    npc_ids: list[str] = []\n',
    '    _raw_npc_source = (\n',
    '        alc.get("npc_actor_ids")\n',
    '        or alc.get("ai_allowed_actor_ids")\n',
    '        or []\n',
    '    )\n',
    '    for raw_id in _raw_npc_source:\n',
    '        nid = str(raw_id or "").strip()\n',
    '        if nid:\n',
    '            npc_ids.append(nid)\n',
    '    if not npc_ids:\n',
    '        _lanes = alc.get("actor_lanes") if isinstance(alc.get("actor_lanes"), dict) else {}\n',
    '        for actor_id, lane in _lanes.items():\n',
    '            if str(lane).strip() == "npc":\n',
    '                aid = str(actor_id).strip()\n',
    '                if aid:\n',
    '                    npc_ids.append(aid)\n',
    '\n',
    '    # Resolve target location from free_player_action_resolution\n',
    '    target_location: str | None = None\n',
    '    if isinstance(free_player_action_resolution, dict):\n',
    '        raw_target = free_player_action_resolution.get("target_location")\n',
    '        if raw_target:\n',
    '            target_location = str(raw_target).strip() or None\n',
    '\n',
    '    # Apply player/human location from resolved action target\n',
    '    if selected_human_actor_id and target_location:\n',
    '        locations[selected_human_actor_id] = target_location\n',
    '\n',
    '    # Determine which NPCs are missing from actor_locations\n',
    '    missing_npc_ids = [nid for nid in npc_ids if nid not in locations]\n',
    '\n',
    '    # Best available room-level fallback for missing NPCs.\n',
    '    # environment_current_room_id is preferred because it is always a room-level\n',
    '    # ID (from environment_state.current_room_id), while current_step_scene_id\n',
    '    # may be a coarse scene identifier (e.g. "scene_1") that does not appear in\n',
    '    # actor_locations values.\n',
    '    fallback_location: str | None = environment_current_room_id or current_step_scene_id\n',
    '\n',
    '    if missing_npc_ids:\n',
    '        if not fallback_location:\n',
    '            return {\n',
    '                "actor_locations": locations,\n',
    '                "gathering_scene_id": None,\n',
    '                "source": "environment_state_with_actor_lane_fallback",\n',
    '                "fallback_actor_ids": [],\n',
    '                "original_actor_locations": original_locations,\n',
    '                "diagnostic_blocker": True,\n',
    '                "reason": "missing_current_step_scene_id",\n',
    '            }\n',
    '        for nid in missing_npc_ids:\n',
    '            locations[nid] = fallback_location\n',
    '\n',
    '    # Derive gathering_scene_id from NPC locations (Phase 1 without room\n',
    '    # tracking: NPCs never move, so their current location IS the gathering\n',
    '    # room).  Using the most common NPC location ensures the topology check in\n',
    '    # compute_gathering_state uses the same room-level ID as actor_locations.\n',
    '    npc_location_values = [\n',
    '        str(locations[nid]).strip()\n',
    '        for nid in npc_ids\n',
    '        if nid in locations and str(locations[nid] or "").strip()\n',
    '    ]\n',
    '    if npc_location_values:\n',
    '        # Most common NPC location = gathering room\n',
    '        _counts: dict[str, int] = {}\n',
    '        for _loc in npc_location_values:\n',
    '            _counts[_loc] = _counts.get(_loc, 0) + 1\n',
    '        gathering_scene_id: str | None = max(_counts, key=lambda k: _counts[k])\n',
    '    elif environment_current_room_id:\n',
    '        gathering_scene_id = environment_current_room_id\n',
    '    else:\n',
    '        gathering_scene_id = current_step_scene_id\n',
    '\n',
    '    return {\n',
    '        "actor_locations": locations,\n',
    '        "gathering_scene_id": gathering_scene_id,\n',
    '        "source": "environment_state_with_actor_lane_fallback",\n',
    '        "fallback_actor_ids": missing_npc_ids,\n',
    '        "original_actor_locations": original_locations,\n',
    '        "diagnostic_blocker": False,\n',
    '        "reason": None,\n',
    '    }\n',
    '\n',
    '\n',
    'def w5_ast_director_projection_enabled() -> bool:\n',
    '    """W5 Director/Gathering projection flag (default-on as of Phase 6B-1).\n',
    '\n',
    '    Returns True when unset/empty: Director/Gathering reads the typed W5\n',
    '    projection as its actor-location input while the legacy completion\n',
    '    helper remains as fallback. Explicit opt-out via ``0/false/no/off``\n',
    '    restores pre-Phase-6B-1 legacy-only behavior. ADR-0061 pause\n',
    '    semantics are not changed by this flag default.\n',
    '    """\n',
    '\n',
    '    raw = (os.environ.get("W5_AST_DIRECTOR_PROJECTION_ENABLED") or "").strip().lower()\n',
    '    if raw in {"0", "false", "no", "off"}:\n',
    '        return False\n',
    '    return True\n',
    '\n',
    '\n',
    'def _w5_director_projection_failure_reason(exc: Exception) -> str:\n',
    '    text = str(exc).strip()\n',
    '    if text:\n',
    '        return text\n',
    '    return type(exc).__name__\n',
    '\n',
    '\n',
    'def complete_actor_locations_for_gathering_with_optional_w5_projection(\n',
    '    *,\n',
    '    actor_locations: dict[str, Any] | None,\n',
    '    actor_lane_context: dict[str, Any] | None,\n',
    '    current_step_scene_id: str | None,\n',
    '    selected_human_actor_id: str | None = None,\n',
    '    free_player_action_resolution: dict[str, Any] | None = None,\n',
    '    environment_current_room_id: str | None = None,\n',
    '    w5_latest_snapshot: dict[str, Any] | None = None,\n',
    '    w5_director_projection_enabled: bool | None = None,\n',
    ') -> dict[str, Any]:\n',
    '    """Resolve Director/Gathering actor locations with W5 Phase 3A fallback.\n',
    '\n',
    '    When disabled, this returns the baseline completion payload. When\n',
    '    enabled, it builds a typed W5 Director projection, uses its\n',
    '    ``derived_actor_locations`` map as the input substrate, then runs the\n',
]
