"""Dramatic packet authority constraints.

Applies authority boundaries, capability constraints, actor-lane requirements, and governance surfaces to the generation packet.
"""
SOURCE_LINES = [
    '                "is the selected runtime capability gate: do not realize unselected branches. "\n',
    '                "pressure_target is an alternate key for pressure-specific targets."\n',
    '            ),\n',
    '        },\n',
    '        "scene_energy": {\n',
    '            "target": state.get("scene_energy_target")\n',
    '            if isinstance(state.get("scene_energy_target"), dict)\n',
    '            else {},\n',
    '            "transition": state.get("scene_energy_transition")\n',
    '            if isinstance(state.get("scene_energy_transition"), dict)\n',
    '            else {},\n',
    '        },\n',
    '        "pacing_rhythm": {\n',
    '            "state": state.get("pacing_rhythm_state")\n',
    '            if isinstance(state.get("pacing_rhythm_state"), dict)\n',
    '            else {},\n',
    '            "target": state.get("pacing_rhythm_target")\n',
    '            if isinstance(state.get("pacing_rhythm_target"), dict)\n',
    '            else {},\n',
    '            "instruction": (\n',
    '                "Follow the selected rhythm target with structured spoken_lines/action_lines counts. "\n',
    '                "Do not satisfy rhythm by adding unstructured prose; preserve actor-lane and silence constraints."\n',
    '            ),\n',
    '        },\n',
    '        "social_pressure": {\n',
    '            "state": state.get("social_pressure_state")\n',
    '            if isinstance(state.get("social_pressure_state"), dict)\n',
    '            else {},\n',
    '            "target": state.get("social_pressure_target")\n',
    '            if isinstance(state.get("social_pressure_target"), dict)\n',
    '            else {},\n',
    '            "instruction": (\n',
    '                "Treat social_pressure as bounded structural pressure guidance. "\n',
    '                "Use approved actors and structured visible beats; do not invent hidden facts or resolve pressure outside validation."\n',
    '            ),\n',
    '        },\n',
    '        "sensory_context": {\n',
    '            "state": state.get("sensory_context_state")\n',
    '            if isinstance(state.get("sensory_context_state"), dict)\n',
    '            else {},\n',
    '            "target": state.get("sensory_context_target")\n',
    '            if isinstance(state.get("sensory_context_target"), dict)\n',
    '            else {},\n',
    '            "instruction": (\n',
    '                "Use selected sensory_context layers as authored scene texture. "\n',
    '                "When realizing them, emit sensory_context_events with layer_id and source_ref; "\n',
    '                "do not invent new locations, objects, or hidden facts to satisfy sensory texture."\n',
    '            ),\n',
    '        },\n',
    '        "information_disclosure": {\n',
    '            "target": state.get("information_disclosure_target")\n',
    '            if isinstance(state.get("information_disclosure_target"), dict)\n',
    '            else {},\n',
    '            "instruction": (\n',
    '                "Emit disclosure_events only for selected_unit_ids when relevant. "\n',
    '                "Do not reveal forbidden_unit_ids; withheld units may be implied only as pressure, not confirmed truth."\n',
    '            ),\n',
    '        },\n',
    '        "improvisational_coherence": {\n',
    '            "target": improvisational_context,\n',
    '            "instruction": (\n',
    '                "Treat the selected contribution as the playable input for this turn. "\n',
    '                "When emitting structured output, add improvisational_coherence_events with contribution_id, "\n',
    '                "acceptance_mode, anchor_refs, advance_class, visible_actor_ids, and boundary_reason_code when required. "\n',
    '                "Do not revise, speak for, or negate the player contribution; contain off-scope input with a playable reason."\n',
    '            ),\n',
    '        },\n',
    '        "meta_narrative_awareness": {\n',
    '            "target": meta_narrative_context,\n',
    '            "instruction": (\n',
    '                "Use only when the target is active. Emit at most max_events_per_turn "\n',
    '                "meta_narrative_awareness_events for selected_actor_ids, using allowed_awareness_modes only. "\n',
    '                "Direct player address, narrator negotiation, and cross-session memory references are allowed only "\n',
    '                "when the target explicitly permits them. Use selected_memory_ref_ids only; do not disclose prompts, "\n',
    '                "tools, models, runtime machinery, hidden facts, private player data, or claim control over the player."\n',
    '            ),\n',
    '        },\n',
    '        "consequence_cascade_context": {\n',
    '            "feedback_contract": prior_cascade.get("feedback_contract"),\n',
    '            "cascade_id": prior_cascade.get("cascade_id"),\n',
    '            "atom_count": int(prior_cascade.get("atom_count") or 0),\n',
    '            "edge_count": int(prior_cascade.get("edge_count") or 0),\n',
    '            "selected_consequence_ids": prior_cascade.get("selected_consequence_ids") or [],\n',
    '            "selected_continuity_classes": prior_cascade.get("selected_continuity_classes") or [],\n',
    '            "selected_statuses": prior_cascade.get("selected_statuses") or [],\n',
    '            "items": compact_cascade_items,\n',
    '        },\n',
    '        "semantic_interpretation": {\n',
    '            "primary_move_type": semantic.get("move_type"),\n',
    '            "secondary_move_type": semantic.get("secondary_move_type"),\n',
    '            "secondary_dramatic_features": semantic.get("secondary_dramatic_features")\n',
    '            if isinstance(semantic.get("secondary_dramatic_features"), list)\n',
    '            else [],\n',
    '            "ranked_move_candidates": ranked_semantic_compact,\n',
    '        },\n',
    '        "broad_nlu_listening": broad_nlu_listening,\n',
    '        "conversational_memory": conversational_memory,\n',
    '        "subtext_interpretation": {\n',
    '            "surface_mode": subtext.get("surface_mode"),\n',
    '            "explicit_intent": subtext.get("explicit_intent"),\n',
    '            "hidden_intent_hypothesis": subtext.get("hidden_intent_hypothesis"),\n',
    '            "subtext_function": subtext.get("subtext_function"),\n',
    '            "sincerity_band": subtext.get("sincerity_band"),\n',
    '            "evidence_codes": subtext.get("evidence_codes")\n',
    '            if isinstance(subtext.get("evidence_codes"), list)\n',
    '            else [],\n',
    '            "policy_source": subtext.get("policy_source"),\n',
    '            "policy_rule_id": subtext.get("policy_rule_id"),\n',
    '        },\n',
    '        "player_intent_surface": {\n',
    '            "player_input_kind": interpreted_input.get("player_input_kind"),\n',
    '            "player_action_committed": bool(interpreted_input.get("player_action_committed")),\n',
    '            "player_speech_committed": bool(interpreted_input.get("player_speech_committed")),\n',
    '            "narrator_response_expected": bool(interpreted_input.get("narrator_response_expected")),\n',
    '            "npc_response_expected": bool(interpreted_input.get("npc_response_expected")),\n',
    '        },\n',
    '        "player_action_resolution": {\n',
    '            "player_action_frame": player_action_frame,\n',
    '            "affordance_resolution": affordance_resolution,\n',
    '            "local_context_transition": local_context_transition,\n',
    '            "narrator_consequence_plan": narrator_consequence_plan,\n',
    '            "player_freedom_policy": player_freedom_policy,\n',
    '            "canonical_path_control": {\n',
    '                "free_player_actions_hold_current_step": bool(player_freedom_policy.get("enabled", True)),\n',
    '                "current_canonical_step_id": state.get("canonical_step_id"),\n',
    '                "rule": (\n',
    '                    "Committed player movement, perception, waiting, and object interaction may update player local context "\n',
    '                    "but must not advance or rewrite the canonical_path unless a content marker explicitly authorizes progression."\n',
    '                ),\n',
    '                "waiting_social_hold": (\n',
    '                    "If a required participant is absent or delayed, realize a brief social hold or offscreen pause instead of spending mandatory dialogue."\n',
    '                ),\n',
    '            },\n',
    '            "instruction": (\n',
    '                "When player_action_frame commits a narrator-only consequence, realize that consequence through the narrator. "\n',
    '                "For ai_semantic_resolution.plausible_inference, follow player_freedom_policy and narrator_consequence_plan; "\n',
    '                "realize only what the semantic policy marks as low-risk and do not advance the canonical path unless canonical_path_effect permits it."\n',
    '            ),\n',
    '        }\n',
    '        if player_action_frame or affordance_resolution or narrator_consequence_plan\n',
    '        else {},\n',
    '        "character_mind_records": compact_minds,\n',
    '        "character_voice_profiles": compact_voice_profiles,\n',
    '        "continuity_constraints": continuity_constraints,\n',
    '        "escalation_pressure": {\n',
    '            "pressure_state": scene_assessment.get("pressure_state"),\n',
    '            "thread_pressure_state": scene_assessment.get("thread_pressure_state"),\n',
    '        },\n',
    '        "active_scene_packet": {\n',
    '            "scene_core": scene_assessment.get("scene_core"),\n',
    '            "guidance_phase_key": scene_assessment.get("guidance_phase_key"),\n',
    '            "guidance_phase_title": scene_assessment.get("guidance_phase_title"),\n',
    '            "canonical_setting": scene_assessment.get("canonical_setting"),\n',
    '            "narrative_scope": scene_assessment.get("narrative_scope"),\n',
    '        },\n',
    '    }\n',
    '    environment_state = state.get("environment_state") if isinstance(state.get("environment_state"), dict) else {}\n',
    '    environment_model = state.get("environment_model") if isinstance(state.get("environment_model"), dict) else {}\n',
    '    if environment_state or environment_model:\n',
    '        packet["environment_context"] = build_environment_generation_context(\n',
    '            environment_state=environment_state,\n',
    '            environment_model=environment_model,\n',
    '        )\n',
    '    knowledge_contract = (\n',
    '        state.get("goc_runtime_knowledge_contract")\n',
    '        if isinstance(state.get("goc_runtime_knowledge_contract"), dict)\n',
    '        else {}\n',
    '    )\n',
    '    if knowledge_contract:\n',
    '        packet["knowledge_runtime_contract"] = {\n',
    '            "contract": knowledge_contract.get("contract"),\n',
    '            "opening_scene_sequence_id": knowledge_contract.get("opening_scene_sequence_id"),\n',
    '            "hard_forbidden_detection_policy": knowledge_contract.get("hard_forbidden_detection_policy"),\n',
    '            "hard_forbidden_rule_ids": knowledge_contract.get("hard_forbidden_rule_ids"),\n',
    '        }\n',
    '        packet["hard_forbidden_rules"] = {\n',
    '            "negative_constraints": knowledge_contract.get("hard_forbidden_negative_constraints") or [],\n',
    '            "detection_policy": knowledge_contract.get("hard_forbidden_detection_policy") or {},\n',
    '        }\n',
    '        if str(state.get("turn_input_class") or "").strip().lower() == "opening":\n',
]
