"""Commit and render setup.

Runs the commit seam, prepares visible-render inputs, and carries diagnostics into player-facing rendering.
"""
SOURCE_LINES = [
    '        update["turn_aspect_ledger"] = authority_ledger\n',
    '        if context_synthesis_retry_history:\n',
    '            update["context_synthesis_retry_history"] = context_synthesis_retry_history\n',
    '            if last_validation_feedback is not None:\n',
    '                update["validation_feedback"] = last_validation_feedback\n',
    '            if isinstance(last_retry_context_synthesis_bundle, dict):\n',
    '                retry_diag = summarize_context_synthesis_for_diagnostics(\n',
    '                    last_retry_context_synthesis_bundle,\n',
    '                    used_in_model_prompt=True,\n',
    '                )\n',
    '                retry_diag.update(\n',
    '                    {\n',
    '                        "resynthesis_count": len(context_synthesis_retry_history),\n',
    '                        "used_for_self_correction": True,\n',
    '                        "retry_attempts": context_synthesis_retry_history,\n',
    '                    }\n',
    '                )\n',
    '                update["context_synthesis_bundle"] = last_retry_context_synthesis_bundle\n',
    '                update["context_synthesis_diagnostics"] = retry_diag\n',
    '        copy_validation_eval_to_update(update, validation_eval)\n',
    '        update["self_correction"] = {\n',
    '            "attempt_count": len(self_correction_attempts),\n',
    '            "attempts": self_correction_attempts,\n',
    '        }\n',
    '        geo = outcome.get("dramatic_effect_gate_outcome")\n',
    '        if isinstance(geo, dict):\n',
    '            update["dramatic_effect_outcome"] = geo\n',
    '\n',
    "        # Reconcile the model's proposed responder fields against the\n",
    "        # director's selected responder set. Out-of-scope actors are dropped\n",
    '        # so downstream commit / rendering never carries an actor the scene\n',
    '        # never authorized, and the reconciliation outcome is published onto\n',
    '        # state for the governance surface.\n',
    '        reconciliation = _reconcile_model_responders(state, generation)\n',
    '\n',
    '        # Prune out-of-scope actors from structured output lanes (spoken_lines, action_lines)\n',
    '        # to prevent out-of-scope actors from flowing through to commit and rendering\n',
    '        out_of_scope = reconciliation.get("dropped_out_of_scope_actors") or []\n',
    '        pruning_stats = _prune_out_of_scope_actor_lanes(generation, out_of_scope)\n',
    '        reconciliation.update(pruning_stats)\n',
    '\n',
    '        update["responder_reconciliation"] = reconciliation\n',
    '        primary_responder = reconciliation.get("effective_responder_id")\n',
    '        if primary_responder:\n',
    '            update["responder_id"] = primary_responder\n',
    '        elif reconciliation.get("dropped_out_of_scope_count"):\n',
    "            # The model's proposal was entirely out of scope. Clear the prior\n",
    '            # top-level ``responder_id`` so planner-truth extraction reflects\n',
    "            # that the model's responder claim was rejected.\n",
    '            update["responder_id"] = ""\n',
    '        return update\n',
    '\n',
    '    def _commit_seam(self, state: RuntimeTurnState) -> RuntimeTurnState:\n',
    '        """``_commit_seam`` — see implementation for behaviour and contracts.\n',
    '        \n',
    '        Behaviour, edge cases, and invariants should be inferred from the implementation and public contract of this symbol.\n',
    '        \n',
    '        Args:\n',
    '            state: ``state`` (RuntimeTurnState); meaning follows the type and call sites.\n',
    '        \n',
    '        Returns:\n',
    '            RuntimeTurnState:\n',
    '                Returns a value of type ``RuntimeTurnState``; see the function body for structure, error paths, and sentinels.\n',
    '        """\n',
    '        update = _track(state, node_name="commit_seam")\n',
    '        validation = state.get("validation_outcome") if isinstance(state.get("validation_outcome"), dict) else {}\n',
    '        proposed = list(state.get("proposed_state_effects") or [])\n',
    '        candidate_deltas = state.get("candidate_deltas")\n',
    '        state_delta_boundary = state.get("state_delta_boundary")\n',
    '        committed = run_commit_seam(\n',
    '            module_id=state.get("module_id") or "",\n',
    '            validation_outcome=validation,\n',
    '            proposed_state_effects=proposed,\n',
    '            candidate_deltas=candidate_deltas if isinstance(candidate_deltas, list) else None,\n',
    '            state_delta_boundary=state_delta_boundary if isinstance(state_delta_boundary, dict) else None,\n',
    '            player_action_frame=state.get("player_action_frame")\n',
    '            if isinstance(state.get("player_action_frame"), dict)\n',
    '            else None,\n',
    '        )\n',
    '        continuity: list[dict[str, Any]] = []\n',
    '        if (\n',
    '            _runtime_governance_hook_enabled(state, "module_continuity_impacts_on_commit_v1")\n',
    '            and validation.get("status") == "approved"\n',
    '            and committed.get("commit_applied")\n',
    '        ):\n',
    '            continuity = build_goc_continuity_impacts_on_commit(\n',
    '                module_id=str(state.get("module_id") or ""),\n',
    '                selected_scene_function=str(state.get("selected_scene_function") or ""),\n',
    '                proposed_state_effects=proposed,\n',
    '                social_outcome=state.get("social_outcome"),\n',
    '                emotional_shift=state.get("emotional_shift") if isinstance(state.get("emotional_shift"), dict) else None,\n',
    '                dramatic_direction=state.get("dramatic_direction"),\n',
    '            )\n',
    '        action_authority = (\n',
    '            committed.get("player_action_authority")\n',
    '            if isinstance(committed.get("player_action_authority"), dict)\n',
    '            else {}\n',
    '        )\n',
    '        committed_environment_state: dict[str, Any] | None = None\n',
    '        if bool(committed.get("commit_applied")) and bool(action_authority.get("player_action_committed")):\n',
    '            committed_environment_state = apply_action_to_environment_state(\n',
    '                environment_state=state.get("environment_state")\n',
    '                if isinstance(state.get("environment_state"), dict)\n',
    '                else None,\n',
    '                environment_model=state.get("environment_model")\n',
    '                if isinstance(state.get("environment_model"), dict)\n',
    '                else None,\n',
    '                player_action_frame=state.get("player_action_frame")\n',
    '                if isinstance(state.get("player_action_frame"), dict)\n',
    '                else None,\n',
    '                affordance_resolution=state.get("affordance_resolution")\n',
    '                if isinstance(state.get("affordance_resolution"), dict)\n',
    '                else None,\n',
    '                local_context_transition=state.get("local_context_transition")\n',
    '                if isinstance(state.get("local_context_transition"), dict)\n',
    '                else None,\n',
    '                narrator_consequence_plan=state.get("narrator_consequence_plan")\n',
    '                if isinstance(state.get("narrator_consequence_plan"), dict)\n',
    '                else None,\n',
    '                actor_lane_context=state.get("actor_lane_context")\n',
    '                if isinstance(state.get("actor_lane_context"), dict)\n',
    '                else None,\n',
    '                turn_number=int(state.get("turn_number") or 0),\n',
    '            )\n',
    '            committed["environment_state_after"] = committed_environment_state\n',
    '        validation_status = str(validation.get("status") or "").strip().lower()\n',
    '        commit_applied = bool(committed.get("commit_applied"))\n',
    '        commit_status = "partial"\n',
    '        if (validation_status == "approved" and commit_applied) or (\n',
    '            validation_status != "approved" and not commit_applied\n',
    '        ):\n',
    '            commit_status = "passed"\n',
    '        commit_failure_reason = None\n',
    '        state_delta_rejection = (\n',
    '            committed.get("state_delta_rejection")\n',
    '            if isinstance(committed.get("state_delta_rejection"), dict)\n',
    '            else {}\n',
    '        )\n',
    '        if state_delta_rejection:\n',
    '            commit_status = "failed"\n',
    '            commit_failure_reason = str(\n',
    '                state_delta_rejection.get("error_code") or "state_delta_boundary_violation"\n',
    '            )\n',
    '        if validation_status == "approved" and not commit_applied and not state_delta_rejection:\n',
    '            commit_failure_reason = "approved_turn_without_committed_effects"\n',
    '        ledger_aspects = (\n',
    '            (state.get("turn_aspect_ledger") or {}).get("turn_aspect_ledger")\n',
    '            if isinstance(state.get("turn_aspect_ledger"), dict)\n',
    '            else {}\n',
    '        )\n',
    '        cap_aspect = (\n',
    '            ledger_aspects.get(ASPECT_CAPABILITY_SELECTION)\n',
    '            if isinstance(ledger_aspects, dict)\n',
    '            else {}\n',
    '        )\n',
    '        cap_selected = cap_aspect.get("selected") if isinstance(cap_aspect, dict) and isinstance(cap_aspect.get("selected"), dict) else {}\n',
    '        cap_actual = cap_aspect.get("actual") if isinstance(cap_aspect, dict) and isinstance(cap_aspect.get("actual"), dict) else {}\n',
    '        commit_ledger = set_aspect_record(\n',
    '            state.get("turn_aspect_ledger") if isinstance(state.get("turn_aspect_ledger"), dict) else {},\n',
    '            ASPECT_COMMIT,\n',
    '            make_aspect_record(\n',
    '                applicable=True,\n',
    '                status=commit_status,\n',
    '                expected={\n',
    '                    "validation_status": validation.get("status"),\n',
    '                    "commit_applies_only_after_validation": True,\n',
    '                },\n',
    '                actual={\n',
    '                    "commit_applied": commit_applied,\n',
    '                    "commit_lane": committed.get("commit_lane"),\n',
    '                    "committed_effect_count": len(committed.get("committed_effects") or []),\n',
    '                    "player_action_committed": action_authority.get("player_action_committed"),\n',
    '                    "player_speech_committed": action_authority.get("player_speech_committed"),\n',
    '                    "affordance_status": action_authority.get("affordance_status"),\n',
    '                    "action_commit_status": action_authority.get("action_commit_status"),\n',
    '                    "validation_rejection_not_committed": (\n',
    '                        validation_status != "approved" and not commit_applied\n',
    '                    ),\n',
    '                    "deliberately_not_committed_failure": (\n',
    '                        validation.get("reason") if validation_status != "approved" else None\n',
]
