"""Visible render execution.

Runs visible rendering, applies narrative visibility rules, and prepares rendered turn surfaces.
"""
SOURCE_LINES = [
    '                    ),\n',
    '                    "selected_capabilities": cap_selected.get("selected_capabilities"),\n',
    '                    "realized_capabilities": cap_actual.get("realized_capabilities"),\n',
    '                    "forbidden_capability_realized": cap_actual.get("forbidden_capability_realized"),\n',
    '                    "state_delta_rejection": state_delta_rejection,\n',
    '                },\n',
    '                reasons=[commit_failure_reason] if commit_failure_reason else [],\n',
    '                source="runtime",\n',
    '                failure_class=(\n',
    '                    "hard_contract_failure"\n',
    '                    if state_delta_rejection\n',
    '                    else "observability_gap"\n',
    '                    if commit_failure_reason\n',
    '                    else None\n',
    '                ),\n',
    '                failure_reason=commit_failure_reason,\n',
    '            ),\n',
    '        )\n',
    '        update["committed_result"] = committed\n',
    '        update["continuity_impacts"] = continuity\n',
    '        if committed_environment_state:\n',
    '            update["environment_state"] = committed_environment_state\n',
    '            update["environment_transition"] = {\n',
    '                "contract": "environment_transition.v1",\n',
    '                "committed": True,\n',
    '                "source": "commit_seam",\n',
    '                "last_environment_event": (\n',
    '                    committed_environment_state.get("last_environment_events") or [None]\n',
    '                )[-1],\n',
    '            }\n',
    '        update["turn_aspect_ledger"] = commit_ledger\n',
    '        return update\n',
    '\n',
    '    def _render_visible(self, state: RuntimeTurnState) -> RuntimeTurnState:\n',
    '        """``_render_visible`` — see implementation for behaviour and contracts.\n',
    '        \n',
    '        Behaviour, edge cases, and invariants should be inferred from the implementation and public contract of this symbol.\n',
    '        \n',
    '        Args:\n',
    '            state: ``state`` (RuntimeTurnState); meaning follows the type and call sites.\n',
    '        \n',
    '        Returns:\n',
    '            RuntimeTurnState:\n',
    '                Returns a value of type ``RuntimeTurnState``; see the function body for structure, error paths, and sentinels.\n',
    '        """\n',
    '        update = _track(state, node_name="render_visible")\n',
    '        generation = dict(state.get("generation") or {})\n',
    '        if "content" not in generation and generation.get("model_raw_text"):\n',
    '            generation["content"] = generation["model_raw_text"]\n',
    '        committed = state.get("committed_result") if isinstance(state.get("committed_result"), dict) else {}\n',
    '        validation = state.get("validation_outcome") if isinstance(state.get("validation_outcome"), dict) else {}\n',
    '        tp = "diagnostics_only"\n',
    '        if state.get("graph_errors"):\n',
    '            tp = "diagnostics_only"\n',
    '        elif committed.get("commit_applied"):\n',
    '            tp = "hard"\n',
    '        elif validation.get("status") == "approved":\n',
    '            tp = "soft"\n',
    '        elif "fallback_model" in (state.get("nodes_executed") or []):\n',
    '            tp = "diagnostics_only"\n',
    '        yslice = state.get("goc_yaml_slice") if isinstance(state.get("goc_yaml_slice"), dict) else {}\n',
    '        sg = yslice.get("scene_guidance") if isinstance(yslice.get("scene_guidance"), dict) else {}\n',
    '        responders = state.get("selected_responder_set") if isinstance(state.get("selected_responder_set"), list) else []\n',
    '        primary = responders[0] if responders and isinstance(responders[0], dict) else {}\n',
    '        actor_id = str(primary.get("actor_id") or "")\n',
    '        actor_reason = str(primary.get("reason") or "")\n',
    '        actor_lane_ctx = state.get("actor_lane_context") if isinstance(state.get("actor_lane_context"), dict) else {}\n',
    '        hid = str(actor_lane_ctx.get("human_actor_id") or "").strip()\n',
    '        spr = str(actor_lane_ctx.get("selected_player_role") or "").strip()\n',
    '        pri = str(actor_id or state.get("primary_responder_id") or "").strip()\n',
    '        char_snippet = goc_character_profile_snippet(\n',
    '            actor_id=actor_id,\n',
    '            yaml_slice=yslice,\n',
    '            scene_id=state.get("current_scene_id") or "",\n',
    '        )\n',
    '        guidance_snip = scene_guidance_snippets(\n',
    '            scene_guidance=sg,\n',
    '            scene_id=state.get("current_scene_id") or "",\n',
    '        )\n',
    '        proposed_fx = list(state.get("proposed_state_effects") or [])\n',
    '        prop_narr = extract_proposed_narrative_text(proposed_fx)\n',
    '        bundle, vis_markers = run_visible_render(\n',
    '            module_id=state.get("module_id") or "",\n',
    '            committed_result=committed,\n',
    '            validation_outcome=validation,\n',
    '            generation=generation,\n',
    '            transition_pattern=tp,\n',
    '            live_player_truth_surface=bool(state.get("live_player_truth_surface")),\n',
    '            render_context={\n',
    '                "turn_number": int(state.get("turn_number") or 0),\n',
    '                "turn_input_class": str(state.get("turn_input_class") or ""),\n',
    '                "pacing_mode": state.get("pacing_mode") or "",\n',
    '                "silence_brevity_decision": state.get("silence_brevity_decision")\n',
    '                if isinstance(state.get("silence_brevity_decision"), dict)\n',
    '                else {},\n',
    '                "current_scene_id": state.get("current_scene_id") or "",\n',
    '                "scene_guidance": sg,\n',
    '                "proposed_narrative_excerpt": prop_narr,\n',
    '                "responder_actor_id": actor_id,\n',
    '                "responder_reason": actor_reason,\n',
    '                "character_profile_snippet": char_snippet,\n',
    '                "scene_guidance_snippets": guidance_snip,\n',
    '                "carry_forward_tension_notes": (state.get("prior_planner_truth") or {}).get("carry_forward_tension_notes"),\n',
    '                "player_input": str(state.get("player_input") or "").strip(),\n',
    '                "human_actor_id": hid,\n',
    '                "selected_player_role": spr,\n',
    '                "primary_responder_id": pri,\n',
    '                "runtime_projection": {\n',
    '                    "human_actor_id": hid,\n',
    '                    "selected_player_role": spr,\n',
    '                    "npc_actor_ids": list(actor_lane_ctx.get("npc_actor_ids") or []),\n',
    '                },\n',
    '                "environment_render_context": build_environment_render_context(\n',
    '                    environment_state=state.get("environment_state")\n',
    '                    if isinstance(state.get("environment_state"), dict)\n',
    '                    else None,\n',
    '                    environment_model=state.get("environment_model")\n',
    '                    if isinstance(state.get("environment_model"), dict)\n',
    '                    else None,\n',
    '                ),\n',
    '                # C3: Reaction order divergence for render support surfacing (computed from realized output)\n',
    '                **_compute_reaction_order_divergence_for_render(state),\n',
    '            },\n',
    '        )\n',
    '        update["generation"] = generation\n',
    '        update["visible_output_bundle"] = bundle\n',
    '        update["visibility_class_markers"] = vis_markers\n',
    '        update["transition_pattern"] = tp\n',
    '        # PR-B: project narrator_consequence_realization.v1 from the\n',
    '        # narrator_consequence_plan and the rendered scene_blocks. The\n',
    '        # contract always emits; non-realization is recorded explicitly via\n',
    '        # ``non_realization_reason`` so the operator never has to infer\n',
    '        # status from the absence of a block.\n',
    '        try:\n',
    '            ncp = state.get("narrator_consequence_plan") if isinstance(\n',
    '                state.get("narrator_consequence_plan"), dict\n',
    '            ) else None\n',
    '            scene_blocks = bundle.get("scene_blocks") if isinstance(bundle, dict) else None\n',
    '            actor_lane_v = (\n',
    '                validation.get("actor_lane_validation")\n',
    '                if isinstance(validation, dict) else {}\n',
    '            )\n',
    '            validation_gated = bool(\n',
    '                isinstance(actor_lane_v, dict)\n',
    '                and str(actor_lane_v.get("status") or "").strip().lower() == "rejected"\n',
    '            )\n',
    '            update["narrator_consequence_realization"] = (\n',
    '                build_narrator_consequence_realization(\n',
    '                    narrator_consequence_plan=ncp,\n',
    '                    visible_scene_blocks=scene_blocks if isinstance(scene_blocks, list) else None,\n',
    '                    validation_gated=validation_gated,\n',
    '                )\n',
    '            )\n',
    '        except Exception as exc:\n',
    '            # Defensive: realization projection failures must not block render,\n',
    '            # but the Phase-1 diagnostic contract must still be explicit.\n',
    '            update["narrator_consequence_realization"] = (\n',
    '                build_narrator_consequence_realization(\n',
    '                    narrator_consequence_plan=None,\n',
    '                    visible_scene_blocks=None,\n',
    '                    validation_gated=False,\n',
    '                )\n',
    '            )\n',
    '            update["narrator_consequence_realization"]["projection_error"] = str(exc)[:240]\n',
    '        # PR-C: record narrator transition reaction metadata on pause entry.\n',
    '        # On transition paused=false → true, optionally emit one content-led\n',
    '        # narrator reaction block. If not emitted, record explicit reason.\n',
    '        try:\n',
    '            _pr_c_curr_gathering = (\n',
    '                update.get("director_gathering_state")\n',
    '                or (state.get("director_gathering_state") if isinstance(state.get("director_gathering_state"), dict) else None)\n',
    '            )\n',
    '            _pr_c_prev_gathering = (\n',
    '                state.get("_prior_director_gathering_state")\n',
    '                if isinstance(state.get("_prior_director_gathering_state"), dict)\n',
    '                else None\n',
    '            )\n',
    '            _pr_c_transition = gathering_pause_is_transition(\n',
    '                previous_state=_pr_c_prev_gathering,\n',
    '                current_state=_pr_c_curr_gathering,\n',
]
