"""Executor run completion.

Finishes RuntimeTurnGraphExecutor.run by handling graph results, failures, health metadata, and packaged runtime output.
"""
SOURCE_LINES = [
    '        if canonical_step_id:\n',
    '            initial_state["canonical_step_id"] = str(canonical_step_id)\n',
    '        if canonical_path and isinstance(canonical_path, dict):\n',
    '            initial_state["canonical_path"] = dict(canonical_path)\n',
    '        if current_step_scene_id:\n',
    '            initial_state["current_step_scene_id"] = str(current_step_scene_id)\n',
    '        if current_step_named_characters:\n',
    '            initial_state["current_step_named_characters"] = [\n',
    '                str(actor_id).strip()\n',
    '                for actor_id in current_step_named_characters\n',
    '                if str(actor_id).strip()\n',
    '            ]\n',
    '        if prior_director_gathering_state and isinstance(prior_director_gathering_state, dict):\n',
    '            initial_state["_prior_director_gathering_state"] = dict(prior_director_gathering_state)\n',
    '        if w5_latest_snapshot and isinstance(w5_latest_snapshot, dict):\n',
    '            initial_state["w5_latest_snapshot"] = dict(w5_latest_snapshot)\n',
    '        if turn_input_class is not None:\n',
    '            initial_state["turn_input_class"] = turn_input_class\n',
    '        if force_experiment_preview is not None:\n',
    '            initial_state["force_experiment_preview"] = force_experiment_preview\n',
    '        lt = live_player_truth_surface\n',
    '        if lt is None:\n',
    '            lt = not bool(force_experiment_preview)\n',
    '        initial_state["live_player_truth_surface"] = bool(lt)\n',
    '        # MVP2: actor-lane enforcement context — passed through state to validate_seam.\n',
    '        if actor_lane_context and isinstance(actor_lane_context, dict):\n',
    '            initial_state["actor_lane_context"] = actor_lane_context\n',
    '        if active_narrative_threads:\n',
    '            initial_state["active_narrative_threads"] = active_narrative_threads\n',
    '        if thread_pressure_summary:\n',
    '            # Keep in sync with world-engine story_runtime narrative_threads.THREAD_PRESSURE_SUMMARY_MAX (128).\n',
    '            initial_state["thread_pressure_summary"] = thread_pressure_summary[:128]\n',
    '        if prior_continuity_impacts:\n',
    '            initial_state["prior_continuity_impacts"] = list(prior_continuity_impacts)\n',
    '        if prior_dramatic_signature:\n',
    '            initial_state["prior_dramatic_signature"] = dict(prior_dramatic_signature)\n',
    '        if prior_social_state_record:\n',
    '            initial_state["prior_social_state_record"] = dict(prior_social_state_record)\n',
    '        if prior_narrative_thread_state:\n',
    '            initial_state["prior_narrative_thread_state"] = dict(prior_narrative_thread_state)\n',
    '        if prior_callback_web_state:\n',
    '            initial_state["prior_callback_web_state"] = dict(prior_callback_web_state)\n',
    '        if prior_consequence_cascade_state:\n',
    '            initial_state["prior_consequence_cascade_state"] = dict(\n',
    '                prior_consequence_cascade_state\n',
    '            )\n',
    '        if prior_temporal_control_state:\n',
    '            initial_state["prior_temporal_control_state"] = dict(\n',
    '                prior_temporal_control_state\n',
    '            )\n',
    '        if prior_expectation_variation_state:\n',
    '            initial_state["prior_expectation_variation_state"] = dict(\n',
    '                prior_expectation_variation_state\n',
    '            )\n',
    '        if prior_narrative_momentum_state:\n',
    '            initial_state["prior_narrative_momentum_state"] = dict(\n',
    '                prior_narrative_momentum_state\n',
    '            )\n',
    '        if prior_genre_awareness_state:\n',
    '            initial_state["prior_genre_awareness_state"] = dict(prior_genre_awareness_state)\n',
    '        if prior_symbolic_object_resonance_state:\n',
    '            initial_state["prior_symbolic_object_resonance_state"] = dict(\n',
    '                prior_symbolic_object_resonance_state\n',
    '            )\n',
    '        if prior_pacing_rhythm_state:\n',
    '            initial_state["prior_pacing_rhythm_state"] = dict(prior_pacing_rhythm_state)\n',
    '        if prior_social_pressure_state:\n',
    '            initial_state["prior_social_pressure_state"] = dict(prior_social_pressure_state)\n',
    '        if prior_relationship_state_record:\n',
    '            initial_state["prior_relationship_state_record"] = dict(prior_relationship_state_record)\n',
    '        if prior_planner_truth:\n',
    '            initial_state["prior_planner_truth"] = dict(prior_planner_truth)\n',
    '        if hierarchical_memory_context:\n',
    '            initial_state["hierarchical_memory_context"] = dict(hierarchical_memory_context)\n',
    '        sol = str(session_output_language or "de").strip().lower()[:2] or "de"\n',
    '        sil = str(session_input_language or sol).strip().lower()[:2] or sol\n',
    '        initial_state["session_input_language"] = sil\n',
    '        initial_state["session_output_language"] = sol\n',
    '        if story_runtime_experience and isinstance(story_runtime_experience, dict):\n',
    '            initial_state["story_runtime_experience"] = dict(story_runtime_experience)\n',
    '        if validation_execution_mode:\n',
    '            initial_state["validation_execution_mode"] = str(validation_execution_mode)\n',
    '        return self._graph.invoke(initial_state)\n',
]
