"""Model fallback handling.

Handles degraded generation, fallback adapter selection, raw graph fallback, and fallback diagnostics.
"""
SOURCE_LINES = [
    '            update_pa = {}\n',
    '        update = _track(state, node_name="invoke_model", outcome=outcome)\n',
    '        update["generation"] = generation\n',
    '        update["fallback_needed"] = bool(generation["error"] or generation["success"] is False)\n',
    '        if update["fallback_needed"]:\n',
    '            _log.warning("Primary model invocation failed: provider=%s error=%s", provider or "unknown", generation.get("error") or "unknown")\n',
    '        if update_pa:\n',
    '            update["primary_attempt_evidence"] = update_pa\n',
    '        return update\n',
    '\n',
    '    def _next_step_after_invoke(self, state: RuntimeTurnState) -> str:\n',
    '        """Describe what ``_next_step_after_invoke`` does in one line\n',
    '        (verb-led summary for this method).\n',
    '        \n',
    '        Behaviour, edge cases, and invariants should be inferred from the implementation and public contract of this symbol.\n',
    '        \n',
    '        Args:\n',
    '            state: ``state`` (RuntimeTurnState); meaning follows the type and call sites.\n',
    '        \n',
    '        Returns:\n',
    '            str:\n',
    '                Returns a value of type ``str``; see the function body for structure, error paths, and sentinels.\n',
    '        """\n',
    '        return "fallback_model" if state.get("fallback_needed") else "proposal_normalize"\n',
    '\n',
    '    def _fallback_model(self, state: RuntimeTurnState) -> RuntimeTurnState:\n',
    '        """``_fallback_model`` — see implementation for behaviour and contracts.\n',
    '        \n',
    '        Behaviour, edge cases, and invariants should be inferred from the implementation and public contract of this symbol.\n',
    '        \n',
    '        Args:\n',
    '            state: ``state`` (RuntimeTurnState); meaning follows the type and call sites.\n',
    '        \n',
    '        Returns:\n',
    '            RuntimeTurnState:\n',
    '                Returns a value of type ``RuntimeTurnState``; see the function body for structure, error paths, and sentinels.\n',
    '        """\n',
    '        fallback_generation = dict(state.get("generation", {}))\n',
    '        primary_error = (state.get("generation") or {}).get("error") or "unknown"\n',
    '        configured_fallback_error: str | None = None\n',
    '        routing = state.get("routing") if isinstance(state.get("routing"), dict) else {}\n',
    '        selected_mid = str(routing.get("selected_model") or "").strip()\n',
    '        fallback_mid = str(routing.get("fallback_model") or "").strip()\n',
    '        if fallback_mid and fallback_mid != selected_mid:\n',
    '            spec = self.registry.get(fallback_mid)\n',
    '            provider = str(getattr(spec, "provider", "") or "").strip() if spec is not None else ""\n',
    '            if spec is None:\n',
    '                configured_fallback_error = f"fallback_model_not_registered:{fallback_mid}"\n',
    '            elif provider == "mock":\n',
    '                configured_fallback_error = "fallback_model_provider_is_mock"\n',
    '            else:\n',
    '                adapter = self.adapters.get(provider)\n',
    '                if adapter is None:\n',
    '                    configured_fallback_error = f"fallback_adapter_missing:{provider}"\n',
    '                else:\n',
    '                    provider_model = str(getattr(spec, "provider_model_name", "") or "").strip()\n',
    '                    api_model = provider_model or str(getattr(spec, "model_name", "") or "").strip() or None\n',
    '                    _log.warning(\n',
    '                        "Falling back to configured runtime model: fallback_model=%s primary_error=%s",\n',
    '                        fallback_mid,\n',
    '                        primary_error,\n',
    '                    )\n',
    '                    invoke_kw: dict[str, Any] = {\n',
    '                        "adapter": adapter,\n',
    '                        "player_input": state["player_input"],\n',
    '                        "interpreted_input": state.get("interpreted_input", {})\n',
    '                        if isinstance(state.get("interpreted_input"), dict)\n',
    '                        else {},\n',
    '                        "retrieval_context": state.get("context_text"),\n',
    '                        "timeout_seconds": float(getattr(spec, "timeout_seconds", 10.0) or 10.0),\n',
    '                        "model_prompt": state.get("model_prompt", ""),\n',
    '                        "dramatic_generation_packet": state.get("dramatic_generation_packet")\n',
    '                        if isinstance(state.get("dramatic_generation_packet"), dict)\n',
    '                        else None,\n',
    '                    }\n',
    '                    if api_model:\n',
    '                        invoke_kw["model_name"] = api_model\n',
    '                    runtime_result = _invoke_runtime_adapter_with_langchain(**invoke_kw)\n',
    '                    call = runtime_result.call\n',
    '                    fallback_generation["attempted"] = True\n',
    '                    fallback_generation["success"] = call.success\n',
    '                    fallback_generation["error"] = call.metadata.get("error") if not call.success else None\n',
    '                    fallback_generation["model_raw_text"] = call.content\n',
    '                    fallback_generation["content"] = call.content\n',
    '                    fallback_generation["retrieval_context_attached"] = bool(state.get("context_text"))\n',
    '                    fallback_generation["prompt_length"] = len(state.get("model_prompt", ""))\n',
    '                    fallback_generation["fallback_used"] = True\n',
    '                    fallback_generation["metadata"] = {\n',
    '                        **call.metadata,\n',
    '                        "langchain_prompt_used": True,\n',
    '                        "langchain_parser_error": runtime_result.parser_error,\n',
    '                        "structured_output": runtime_result.parsed_output.model_dump(mode="json")\n',
    '                        if runtime_result.parsed_output\n',
    '                        else None,\n',
    '                        "adapter_invocation_mode": ADAPTER_INVOCATION_LANGCHAIN_PRIMARY,\n',
    '                        "fallback_model_id": fallback_mid,\n',
    '                        "fallback_provider": provider,\n',
    '                        "fallback_reason": "primary_model_invocation_failed",\n',
    '                        "primary_error": primary_error,\n',
    '                        "dramatic_generation_packet_included": isinstance(\n',
    '                            state.get("dramatic_generation_packet"), dict\n',
    '                        ),\n',
    '                        "dramatic_generation_packet_scene_function": (\n',
    '                            state.get("dramatic_generation_packet", {}).get("selected_scene_function")\n',
    '                            if isinstance(state.get("dramatic_generation_packet"), dict)\n',
    '                            else None\n',
    '                        ),\n',
    '                        "dramatic_generation_packet_primary_responder": (\n',
    '                            state.get("dramatic_generation_packet", {}).get("primary_responder_id")\n',
    '                            if isinstance(state.get("dramatic_generation_packet"), dict)\n',
    '                            else None\n',
    '                        ),\n',
    '                    }\n',
    '                    if call.success:\n',
    '                        update = _track(state, node_name="fallback_model")\n',
    '                        update["generation"] = fallback_generation\n',
    '                        update["fallback_needed"] = False\n',
    '                        return update\n',
    '                    configured_fallback_error = (\n',
    '                        call.metadata.get("error")\n',
    '                        if isinstance(call.metadata, dict) and call.metadata.get("error")\n',
    '                        else f"fallback_model_failed:{fallback_mid}"\n',
    '                    )\n',
    '\n',
    '        _log.warning(\n',
    '            "Falling back to mock adapter: primary_error=%s configured_fallback_error=%s",\n',
    '            primary_error,\n',
    '            configured_fallback_error or "not_attempted",\n',
    '        )\n',
    '\n',
    '        if (self.generation_execution_mode or "").strip().lower() == "ai_only":\n',
    '            errors = list(state.get("graph_errors", []))\n',
    '            errors.append("ai_only_mode_blocks_graph_managed_mock_fallback")\n',
    '            if configured_fallback_error:\n',
    '                errors.append(str(configured_fallback_error))\n',
    '            fb_gen = dict(fallback_generation)\n',
    '            meta = fb_gen.get("metadata") if isinstance(fb_gen.get("metadata"), dict) else {}\n',
    '            fb_gen["metadata"] = {\n',
    '                **meta,\n',
    '                "note": "generation_execution_mode=ai_only — graph-managed mock fallback is disabled.",\n',
    '                "configured_fallback_error": configured_fallback_error,\n',
    '            }\n',
    '            update = _track(state, node_name="fallback_model", outcome="error")\n',
    '            update["graph_errors"] = errors\n',
    '            update["generation"] = fb_gen\n',
    '            update["fallback_needed"] = True\n',
    '            return update\n',
    '\n',
    '        fallback_adapter = self.adapters.get("mock")\n',
    '        if fallback_adapter:\n',
    '            call = fallback_adapter.generate(\n',
    '                state.get("model_prompt", state["player_input"]),\n',
    '                timeout_seconds=5.0,\n',
    '                retrieval_context=state.get("context_text"),\n',
    '            )\n',
    '            fallback_generation["attempted"] = True\n',
    '            fallback_generation["success"] = call.success\n',
    '            fallback_generation["error"] = call.metadata.get("error") if not call.success else None\n',
    '            fallback_generation["model_raw_text"] = call.content\n',
    '            fallback_generation["metadata"] = {\n',
    '                **call.metadata,\n',
    '                "langchain_prompt_used": False,\n',
    '                "langchain_parser_error": None,\n',
    '                "structured_output": None,\n',
    '                "adapter_invocation_mode": ADAPTER_INVOCATION_RAW_GRAPH_FALLBACK,\n',
    '                "bypass_note": RAW_FALLBACK_BYPASS_NOTE,\n',
    '                "configured_fallback_error": configured_fallback_error,\n',
    '            }\n',
    '            fallback_generation["fallback_used"] = True\n',
    '            update = _track(state, node_name="fallback_model")\n',
    '            update["generation"] = fallback_generation\n',
    '            update["fallback_needed"] = False\n',
    '            return update\n',
    '        errors = list(state.get("graph_errors", []))\n',
    '        errors.append("fallback_adapter_missing:mock")\n',
    '        if configured_fallback_error:\n',
    '            errors.append(str(configured_fallback_error))\n',
    '        prior_meta = fallback_generation.get("metadata") if isinstance(fallback_generation.get("metadata"), dict) else {}\n',
    '        fallback_generation["metadata"] = {\n',
    '            **prior_meta,\n',
]
