"""Context synthesis derivation.

Builds context synthesis bundles for normal and retry paths, including diagnostic summaries.
"""
SOURCE_LINES = [
    '        return build_context_synthesis_bundle(\n',
    '            retrieval=state.get("retrieval") if isinstance(state.get("retrieval"), dict) else None,\n',
    '            context_text=state.get("context_text") if isinstance(state.get("context_text"), str) else None,\n',
    '            scene_assessment=state.get("scene_assessment")\n',
    '            if isinstance(state.get("scene_assessment"), dict)\n',
    '            else None,\n',
    '            semantic_move_record=state.get("semantic_move_record")\n',
    '            if isinstance(state.get("semantic_move_record"), dict)\n',
    '            else None,\n',
    '            social_state_record=state.get("social_state_record")\n',
    '            if isinstance(state.get("social_state_record"), dict)\n',
    '            else None,\n',
    '            turn_aspect_ledger=state.get("turn_aspect_ledger")\n',
    '            if isinstance(state.get("turn_aspect_ledger"), dict)\n',
    '            else None,\n',
    '            hierarchical_memory_context=state.get("hierarchical_memory_context")\n',
    '            if isinstance(state.get("hierarchical_memory_context"), dict)\n',
    '            else None,\n',
    '            validation_feedback=validation_feedback\n',
    '            if isinstance(validation_feedback, dict)\n',
    '            else (\n',
    '                state.get("validation_feedback")\n',
    '                if isinstance(state.get("validation_feedback"), dict)\n',
    '                else None\n',
    '            ),\n',
    '        )\n',
    '\n',
    '    def _synthesize_context(self, state: RuntimeTurnState) -> RuntimeTurnState:\n',
    '        """Build a deterministic, non-authoritative context synthesis bundle."""\n',
    '        update = _track(state, node_name="synthesize_context")\n',
    '        try:\n',
    '            bundle = self._build_context_synthesis_bundle_for_state(state)\n',
    '        except Exception as exc:\n',
    '            bundle = build_context_synthesis_error_bundle(exc)\n',
    '            errors = list(state.get("graph_errors") or [])\n',
    '            errors.append(f"context_synthesis_error:{type(exc).__name__}")\n',
    '            update["graph_errors"] = errors\n',
    '        update["context_synthesis_bundle"] = bundle\n',
    '        update["context_synthesis_diagnostics"] = summarize_context_synthesis_for_diagnostics(bundle)\n',
    '        return update\n',
    '\n',
    '    def _synthesize_context_for_retry(\n',
    '        self,\n',
    '        state: RuntimeTurnState,\n',
    '        *,\n',
    '        validation_feedback: dict[str, Any],\n',
    '        attempt_index: int,\n',
    '    ) -> tuple[dict[str, Any], dict[str, Any], str]:\n',
    '        """Rebuild context synthesis with validation feedback for self-correction."""\n',
    '        try:\n',
    '            bundle = self._build_context_synthesis_bundle_for_state(\n',
    '                state,\n',
    '                validation_feedback=validation_feedback,\n',
    '            )\n',
    '        except Exception as exc:\n',
    '            bundle = build_context_synthesis_error_bundle(exc)\n',
    '        diagnostics = summarize_context_synthesis_for_diagnostics(bundle, used_in_model_prompt=True)\n',
    '        diagnostics.update(\n',
    '            {\n',
    '                "retry_attempt_index": attempt_index,\n',
    '                "validation_feedback": {\n',
    '                    "codes": list(validation_feedback.get("codes") or []),\n',
    '                    "trigger_source": validation_feedback.get("trigger_source"),\n',
    '                    "failure_reason_before_retry": validation_feedback.get("failure_reason_before_retry"),\n',
    '                    "validation_status_before_retry": validation_feedback.get("validation_status_before_retry"),\n',
    '                },\n',
    '                "used_for_self_correction": True,\n',
    '            }\n',
    '        )\n',
    '        prompt_lines = context_synthesis_prompt_lines(bundle)\n',
    '        prompt_block = ""\n',
    '        if prompt_lines:\n',
    '            prompt_block = (\n',
    '                "Validation Feedback Resynthesis (proposal support, non-authoritative):\\n"\n',
    '                + "\\n".join(prompt_lines)\n',
    '            )\n',
    '        return bundle, diagnostics, prompt_block\n',
]
