"""Generation normalization.

Normalizes model proposals, strips illegal director overwrites, and prepares structured output for validation.
"""
SOURCE_LINES = [
    '                else None\n',
    '            ),\n',
    '        }\n',
    '        proposed = structured_output_to_proposed_effects(parsed_structured)\n',
    '        attempt = {\n',
    '            "attempt_index": attempt_index,\n',
    '            "candidate_model": candidate_mid,\n',
    '            "provider": provider,\n',
    '            "feedback_codes": list(feedback_codes),\n',
    '            "success": bool(call.success),\n',
    '            "parser_error": runtime_result.parser_error,\n',
    '            "preserve_actor_lanes": bool(preserve_actor_lanes),\n',
    '            "self_correction_model_changed": self_correction_model_changed,\n',
    '            "context_synthesis_retry_attached": bool(retry_context_synthesis_prompt.strip()),\n',
    '            "context_synthesis_retry_status": retry_synthesis_status,\n',
    '        }\n',
    '        return rewritten, proposed, attempt\n',
    '\n',
    '    def _proposal_normalize(self, state: RuntimeTurnState) -> RuntimeTurnState:\n',
    '        """``_proposal_normalize`` — see implementation for behaviour and contracts.\n',
    '        \n',
    '        Behaviour, edge cases, and invariants should be inferred from the implementation and public contract of this symbol.\n',
    '        \n',
    '        Args:\n',
    '            state: ``state`` (RuntimeTurnState); meaning follows the type and call sites.\n',
    '        \n',
    '        Returns:\n',
    '            RuntimeTurnState:\n',
    '                Returns a value of type ``RuntimeTurnState``; see the function body for structure, error paths, and sentinels.\n',
    '        """\n',
    '        update = _track(state, node_name="proposal_normalize")\n',
    '        generation = dict(state.get("generation") or {})\n',
    '        meta = generation.get("metadata") if isinstance(generation.get("metadata"), dict) else {}\n',
    '        structured = meta.get("structured_output")\n',
    '        if structured is None:\n',
    '            raw = generation.get("content") if isinstance(generation.get("content"), str) else ""\n',
    '            if not raw.strip():\n',
    '                raw = generation.get("model_raw_text") if isinstance(generation.get("model_raw_text"), str) else ""\n',
    '            if raw.strip().startswith("{"):\n',
    '                try:\n',
    '                    parsed = json.loads(raw)\n',
    '                    parsed_narrative = ""\n',
    '                    parsed_runtime_structure = False\n',
    '                    if isinstance(parsed, dict):\n',
    '                        narr_summary = parsed.get("narration_summary")\n',
    '                        fallback_narrative = parsed.get("narrative_response")\n',
    '                        if isinstance(narr_summary, str) and narr_summary.strip():\n',
    '                            parsed_narrative = narr_summary.strip()\n',
    '                        elif isinstance(fallback_narrative, str) and fallback_narrative.strip():\n',
    '                            parsed_narrative = fallback_narrative.strip()\n',
    '                        parsed_runtime_structure = any(\n',
    '                            isinstance(parsed.get(key), list)\n',
    '                            for key in ("spoken_lines", "action_lines", "initiative_events")\n',
    '                        ) or str(parsed.get("schema_version") or "").strip() == "runtime_actor_turn_v1"\n',
    '                    if (\n',
    '                        isinstance(parsed, dict)\n',
    '                        and (parsed_narrative or parsed_runtime_structure)\n',
    '                    ):\n',
    '                        meta = dict(meta)\n',
    '                        meta["structured_output"] = parsed\n',
    '                        generation["metadata"] = meta\n',
    '                        structured = parsed\n',
    '                except json.JSONDecodeError:\n',
    '                    pass\n',
    '        structured_dict = structured if isinstance(structured, dict) else None\n',
    '        cleaned, strip_markers = strip_director_overwrites_from_structured_output(structured_dict)\n',
    '        if cleaned is not None:\n',
    '            meta = dict(meta)\n',
    '            meta["structured_output"] = cleaned\n',
    '            generation["metadata"] = meta\n',
    '        if isinstance(cleaned, dict):\n',
    '            generation = apply_structured_hydration(state, generation)\n',
    '            meta = generation.get("metadata") if isinstance(generation.get("metadata"), dict) else {}\n',
    '            cleaned = meta.get("structured_output") if isinstance(meta.get("structured_output"), dict) else cleaned\n',
    '        proposed = structured_output_to_proposed_effects(cleaned)\n',
    '        if isinstance(cleaned, dict):\n',
    '            schema_version = str(cleaned.get("schema_version") or "").strip()\n',
    '            narration_summary = narration_summary_to_plain_str(cleaned.get("narration_summary"))\n',
    '            narrative_response = str(cleaned.get("narrative_response") or "").strip()\n',
    '            spoken_count = len([x for x in (cleaned.get("spoken_lines") or []) if isinstance(x, dict)])\n',
    '            action_count = len([x for x in (cleaned.get("action_lines") or []) if isinstance(x, dict)])\n',
    '            has_actor_lane_substance = (spoken_count + action_count) > 0\n',
    '            has_existing_narrative = bool(narration_summary or narrative_response)\n',
    '            parser_error = (\n',
    '                generation.get("parser_error")\n',
    '                or meta.get("langchain_parser_error")\n',
    '                or meta.get("parser_error")\n',
    '            )\n',
    '            transition_pattern = str(state.get("transition_pattern") or "").strip().lower()\n',
    '            adapter_name = str(meta.get("adapter") or "").strip().lower()\n',
    '            # LDSS adapters produce their own narration — synthesis must not override them.\n',
    '            # Configured model fallbacks (gpt-5-nano) produce the same structured format as\n',
    '            # the primary, so synthesis is valid there. Mock fallback is safe because its\n',
    '            # structured_output=None → has_actor_lane_substance=False blocks synthesis anyway.\n',
    '            ldss_active = adapter_name in {"ldss_fallback", "ldss_deterministic"}\n',
    '            fallback_active = ldss_active\n',
    '            actor_lane_validation = _actor_lane_validation(state, generation)\n',
    '            actor_lane_status = str(actor_lane_validation.get("status") or "").strip().lower()\n',
    '            can_synthesize = (\n',
    '                schema_version == "runtime_actor_turn_v1"\n',
    '                and has_actor_lane_substance\n',
    '                and not has_existing_narrative\n',
    '                and not _has_usable_narrative_effect(proposed)\n',
    '                and actor_lane_status in {"approved", "not_applicable"}\n',
    '                and not parser_error\n',
    '                and transition_pattern != "diagnostics_only"\n',
    '                and not fallback_active\n',
    '                and int(state.get("turn_number") or 0) == 0\n',
    '            )\n',
    '            if can_synthesize:\n',
    '                synthesized = _build_actor_lane_opening_narration(\n',
    '                    state=state,\n',
    '                    structured_output=cleaned,\n',
    '                )\n',
    '                if synthesized.strip():\n',
    '                    cleaned = dict(cleaned)\n',
    '                    cleaned["narration_summary"] = synthesized\n',
    '                    cleaned["narrative_response"] = synthesized\n',
    '                    meta = dict(meta)\n',
    '                    meta["structured_output"] = cleaned\n',
    '                    meta["narration_summary_synthesized"] = True\n',
    '                    meta["narration_summary_source"] = "actor_lane_generation_error"\n',
    '                    meta["narration_summary_error_code"] = "opening_actor_lane_narration_missing"\n',
    '                    meta["synthetic_narration_reason"] = (\n',
    '                        "opening_actor_lane_narration_missing"\n',
    '                    )\n',
    '                    generation["metadata"] = meta\n',
    '                    proposed = structured_output_to_proposed_effects(cleaned)\n',
    '        if isinstance(cleaned, dict):\n',
    '            if cleaned.get("primary_responder_id"):\n',
    '                update["primary_responder_id"] = str(cleaned["primary_responder_id"])\n',
    '            if cleaned.get("responder_id"):\n',
    '                update["responder_id"] = str(cleaned["responder_id"])\n',
    '            if cleaned.get("primary_responder_id") and not update.get("responder_id"):\n',
    '                update["responder_id"] = str(cleaned["primary_responder_id"])\n',
    '            secondary = cleaned.get("secondary_responder_ids")\n',
    '            if (not isinstance(secondary, list) or not secondary) and isinstance(\n',
    '                cleaned.get("responder_actor_ids"), list\n',
    '            ):\n',
    '                secondary = cleaned.get("responder_actor_ids")\n',
    '            if isinstance(secondary, list):\n',
    '                update["secondary_responder_ids"] = [str(x).strip() for x in secondary if str(x).strip()]\n',
    '            spoken = cleaned.get("spoken_lines")\n',
    '            if isinstance(spoken, list):\n',
    '                update["spoken_lines"] = list(spoken)\n',
    '            action = cleaned.get("action_lines")\n',
    '            if isinstance(action, list):\n',
    '                update["action_lines"] = list(action)\n',
    '            initiative = cleaned.get("initiative_events")\n',
    '            if isinstance(initiative, list):\n',
    '                update["initiative_events"] = [x for x in initiative if isinstance(x, dict)]\n',
    '            state_effects = cleaned.get("state_effects")\n',
    '            if isinstance(state_effects, list):\n',
    '                update["state_effects"] = [x for x in state_effects if isinstance(x, dict)]\n',
    '            if cleaned.get("function_type"):\n',
    '                update["function_type"] = str(cleaned["function_type"])\n',
    '            if isinstance(cleaned.get("emotional_shift"), dict):\n',
    '                update["emotional_shift"] = cleaned["emotional_shift"]\n',
    '            if cleaned.get("social_outcome"):\n',
    '                update["social_outcome"] = str(cleaned["social_outcome"])\n',
    '            if cleaned.get("dramatic_direction"):\n',
    '                update["dramatic_direction"] = str(cleaned["dramatic_direction"])\n',
    '        fallback_markers = list(state.get("fallback_markers") or [])\n',
    '        fallback_markers.extend(strip_markers)\n',
    '        update["generation"] = generation\n',
    '        update["proposed_state_effects"] = proposed\n',
    '        update["fallback_markers"] = fallback_markers\n',
    '        return update\n',
]
