"""Sensory, improvisation, and disclosure derivation.

Derives improvisational coherence, information disclosure, and dramatic irony input state.
"""
SOURCE_LINES = [
    '            scene_energy_target=state.get("scene_energy_target")\n',
    '            if isinstance(state.get("scene_energy_target"), dict)\n',
    '            else None,\n',
    '            pacing_rhythm_target=state.get("pacing_rhythm_target")\n',
    '            if isinstance(state.get("pacing_rhythm_target"), dict)\n',
    '            else None,\n',
    '            social_pressure_target=state.get("social_pressure_target")\n',
    '            if isinstance(state.get("social_pressure_target"), dict)\n',
    '            else None,\n',
    '            prior_planner_truth=state.get("prior_planner_truth")\n',
    '            if isinstance(state.get("prior_planner_truth"), dict)\n',
    '            else None,\n',
    '            module_runtime_policy=state.get("module_runtime_policy")\n',
    '            if isinstance(state.get("module_runtime_policy"), dict)\n',
    '            else None,\n',
    '            session_output_language=state.get("session_output_language")\n',
    '            if isinstance(state.get("session_output_language"), str)\n',
    '            else None,\n',
    '        )\n',
    '        sensory_state = result.get("state") if isinstance(result.get("state"), dict) else {}\n',
    '        target = result.get("target") if isinstance(result.get("target"), dict) else {}\n',
    '        if sensory_state:\n',
    '            scene_plan["sensory_context_state"] = sensory_state\n',
    '        if target:\n',
    '            scene_plan["sensory_context_target"] = target\n',
    '        update["scene_plan_record"] = scene_plan\n',
    '        update["sensory_context_state"] = sensory_state\n',
    '        update["sensory_context_target"] = target\n',
    '        update["turn_aspect_ledger"] = set_aspect_record(\n',
    '            state.get("turn_aspect_ledger") if isinstance(state.get("turn_aspect_ledger"), dict) else {},\n',
    '            ASPECT_SENSORY_CONTEXT,\n',
    '            _sensory_context_aspect_record(\n',
    '                state_record=sensory_state,\n',
    '                target=target,\n',
    '                policy=result.get("policy") if isinstance(result.get("policy"), dict) else None,\n',
    '            ),\n',
    '        )\n',
    '        return update\n',
    '\n',
    '    def _derive_improvisational_coherence(self, state: RuntimeTurnState) -> RuntimeTurnState:\n',
    '        update = _track(state, node_name="derive_improvisational_coherence")\n',
    '        scene_plan = (\n',
    '            dict(state.get("scene_plan_record"))\n',
    '            if isinstance(state.get("scene_plan_record"), dict)\n',
    '            else {}\n',
    '        )\n',
    '        result = derive_improvisational_coherence(\n',
    '            player_input=state.get("player_input") if isinstance(state.get("player_input"), str) else None,\n',
    '            interpreted_input=state.get("interpreted_input")\n',
    '            if isinstance(state.get("interpreted_input"), dict)\n',
    '            else None,\n',
    '            semantic_move_record=state.get("semantic_move_record")\n',
    '            if isinstance(state.get("semantic_move_record"), dict)\n',
    '            else None,\n',
    '            scene_plan_record=scene_plan,\n',
    '            selected_scene_function=state.get("selected_scene_function")\n',
    '            if isinstance(state.get("selected_scene_function"), str)\n',
    '            else None,\n',
    '            current_scene_id=state.get("current_scene_id")\n',
    '            if isinstance(state.get("current_scene_id"), str)\n',
    '            else None,\n',
    '            selected_responder_set=state.get("selected_responder_set")\n',
    '            if isinstance(state.get("selected_responder_set"), list)\n',
    '            else None,\n',
    '            scene_energy_target=state.get("scene_energy_target")\n',
    '            if isinstance(state.get("scene_energy_target"), dict)\n',
    '            else None,\n',
    '            pacing_rhythm_target=state.get("pacing_rhythm_target")\n',
    '            if isinstance(state.get("pacing_rhythm_target"), dict)\n',
    '            else None,\n',
    '            module_runtime_policy=state.get("module_runtime_policy")\n',
    '            if isinstance(state.get("module_runtime_policy"), dict)\n',
    '            else None,\n',
    '        )\n',
    '        target = result.get("target") if isinstance(result.get("target"), dict) else {}\n',
    '        if target:\n',
    '            scene_plan["improvisational_coherence_target"] = target\n',
    '        update["scene_plan_record"] = scene_plan\n',
    '        update["improvisational_coherence_target"] = target\n',
    '        update["turn_aspect_ledger"] = set_aspect_record(\n',
    '            state.get("turn_aspect_ledger") if isinstance(state.get("turn_aspect_ledger"), dict) else {},\n',
    '            ASPECT_IMPROVISATIONAL_COHERENCE,\n',
    '            build_improvisational_coherence_aspect_record(\n',
    '                target=target,\n',
    '                policy=result.get("policy") if isinstance(result.get("policy"), dict) else None,\n',
    '            ),\n',
    '        )\n',
    '        return update\n',
    '\n',
    '    def _derive_information_disclosure(self, state: RuntimeTurnState) -> RuntimeTurnState:\n',
    '        update = _track(state, node_name="derive_information_disclosure")\n',
    '        scene_plan = (\n',
    '            dict(state.get("scene_plan_record"))\n',
    '            if isinstance(state.get("scene_plan_record"), dict)\n',
    '            else {}\n',
    '        )\n',
    '        result = derive_information_disclosure(\n',
    '            scene_plan_record=scene_plan,\n',
    '            semantic_move_record=state.get("semantic_move_record")\n',
    '            if isinstance(state.get("semantic_move_record"), dict)\n',
    '            else None,\n',
    '            pacing_mode=state.get("pacing_mode") if isinstance(state.get("pacing_mode"), str) else None,\n',
    '            prior_continuity_impacts=state.get("prior_continuity_impacts")\n',
    '            if isinstance(state.get("prior_continuity_impacts"), list)\n',
    '            else None,\n',
    '            module_runtime_policy=state.get("module_runtime_policy")\n',
    '            if isinstance(state.get("module_runtime_policy"), dict)\n',
    '            else None,\n',
    '        )\n',
    '        target = result.get("target") if isinstance(result.get("target"), dict) else {}\n',
    '        if target:\n',
    '            scene_plan["information_disclosure_target"] = target\n',
    '        update["scene_plan_record"] = scene_plan\n',
    '        update["information_disclosure_target"] = target\n',
    '        update["turn_aspect_ledger"] = set_aspect_record(\n',
    '            state.get("turn_aspect_ledger") if isinstance(state.get("turn_aspect_ledger"), dict) else {},\n',
    '            ASPECT_INFORMATION_DISCLOSURE,\n',
    '            _information_disclosure_aspect_record(\n',
    '                target=target,\n',
    '                policy=result.get("policy") if isinstance(result.get("policy"), dict) else None,\n',
    '            ),\n',
    '        )\n',
    '        return update\n',
    '\n',
    '    def _derive_dramatic_irony(self, state: RuntimeTurnState) -> RuntimeTurnState:\n',
    '        update = _track(state, node_name="derive_dramatic_irony")\n',
    '        responders = (\n',
    '            state.get("selected_responder_set")\n',
    '            if isinstance(state.get("selected_responder_set"), list)\n',
    '            else []\n',
    '        )\n',
    '        responder_ids: list[str] = []\n',
    '        for row in responders:\n',
    '            if not isinstance(row, dict):\n',
    '                continue\n',
    '            actor_id = str(row.get("actor_id") or row.get("responder_id") or "").strip()\n',
    '            if actor_id and actor_id not in responder_ids:\n',
    '                responder_ids.append(actor_id)\n',
    '\n',
    '        actor_lane_ctx = (\n',
    '            state.get("actor_lane_context")\n',
    '            if isinstance(state.get("actor_lane_context"), dict)\n',
    '            else {}\n',
    '        )\n',
    '        forbidden_actor_ids: set[str] = set()\n',
    '        for raw_actor_id in actor_lane_ctx.get("ai_forbidden_actor_ids") or []:\n',
    '            forbidden_actor_ids.update(expand_goc_actor_id_aliases(str(raw_actor_id)))\n',
    '        human_actor_id = str(actor_lane_ctx.get("human_actor_id") or "").strip()\n',
    '        forbidden_actor_ids.update(expand_goc_actor_id_aliases(human_actor_id))\n',
    '        allowed_actor_ids = npc_actor_ids_from_context(actor_lane_ctx)\n',
    '        if not allowed_actor_ids:\n',
    '            allowed_actor_ids = [\n',
    '                actor_id\n',
    '                for actor_id in responder_ids\n',
    '                if actor_id and actor_id not in forbidden_actor_ids\n',
    '            ]\n',
    '\n',
    '        minds = (\n',
    '            state.get("character_mind_records")\n',
    '            if isinstance(state.get("character_mind_records"), list)\n',
    '            else []\n',
    '        )\n',
    '        compact_minds: list[dict[str, Any]] = []\n',
    '        for row in minds[:4]:\n',
    '            if not isinstance(row, dict):\n',
    '                continue\n',
    '            compact_minds.append(\n',
    '                {\n',
    '                    "actor_id": row.get("runtime_actor_id") or row.get("character_key"),\n',
    '                    "formal_role_label": row.get("formal_role_label"),\n',
    '                    "tactical_posture": row.get("tactical_posture"),\n',
    '                    "pressure_response_bias": row.get("pressure_response_bias"),\n',
    '                }\n',
    '            )\n',
    '\n',
    '        _, _, npc_agency_simulation, w5_npc_projection_diagnostics = _build_npc_agency_plan_projection(\n',
    '            state=state,\n',
    '            responders=responders,\n',
    '            responder_ids=responder_ids,\n',
    '            npc_actor_ids=allowed_actor_ids,\n',
]
