"""Irony, expectation, and momentum derivation.

Derives dramatic irony, expectation variation, narrative momentum, and their runtime aspect records.
"""
SOURCE_LINES = [
    '            compact_minds=compact_minds,\n',
    '        )\n',
    '        if isinstance(npc_agency_simulation, dict):\n',
    '            update["npc_agency_simulation"] = npc_agency_simulation\n',
    '        if w5_npc_projection_diagnostics:\n',
    '            update.setdefault("graph_diagnostics", {}).update(\n',
    '                {"w5_npc_projection": w5_npc_projection_diagnostics}\n',
    '            )\n',
    '\n',
    '        scene_plan = (\n',
    '            dict(state.get("scene_plan_record"))\n',
    '            if isinstance(state.get("scene_plan_record"), dict)\n',
    '            else {}\n',
    '        )\n',
    '        dramatic_irony_record = build_dramatic_irony_record(\n',
    '            module_runtime_policy=state.get("module_runtime_policy")\n',
    '            if isinstance(state.get("module_runtime_policy"), dict)\n',
    '            else None,\n',
    '            actor_lane_context=actor_lane_ctx,\n',
    '            selected_responder_set=responders,\n',
    '            character_mind_records=minds,\n',
    '            social_state_record=state.get("social_state_record")\n',
    '            if isinstance(state.get("social_state_record"), dict)\n',
    '            else None,\n',
    '            semantic_move_record=state.get("semantic_move_record")\n',
    '            if isinstance(state.get("semantic_move_record"), dict)\n',
    '            else None,\n',
    '            scene_plan_record=scene_plan,\n',
    '            npc_agency_simulation=npc_agency_simulation\n',
    '            if isinstance(npc_agency_simulation, dict)\n',
    '            else state.get("npc_agency_simulation")\n',
    '            if isinstance(state.get("npc_agency_simulation"), dict)\n',
    '            else None,\n',
    '            prior_planner_truth=state.get("prior_planner_truth")\n',
    '            if isinstance(state.get("prior_planner_truth"), dict)\n',
    '            else None,\n',
    '            current_scene_id=state.get("current_scene_id")\n',
    '            if isinstance(state.get("current_scene_id"), str)\n',
    '            else None,\n',
    '            selected_scene_function=str(state.get("selected_scene_function") or "").strip()\n',
    '            or None,\n',
    '        )\n',
    '        scene_plan["dramatic_irony_record"] = dramatic_irony_record\n',
    '        update["scene_plan_record"] = scene_plan\n',
    '        update["dramatic_irony_record"] = dramatic_irony_record\n',
    '        update["turn_aspect_ledger"] = set_aspect_record(\n',
    '            update.get("turn_aspect_ledger")\n',
    '            if isinstance(update.get("turn_aspect_ledger"), dict)\n',
    '            else state.get("turn_aspect_ledger")\n',
    '            if isinstance(state.get("turn_aspect_ledger"), dict)\n',
    '            else {},\n',
    '            ASPECT_DRAMATIC_IRONY,\n',
    '            build_dramatic_irony_aspect_record(\n',
    '                record=dramatic_irony_record,\n',
    '                validation=None,\n',
    '                source="runtime",\n',
    '            ),\n',
    '        )\n',
    '        return update\n',
    '\n',
    '    def _derive_expectation_variation(self, state: RuntimeTurnState) -> RuntimeTurnState:\n',
    '        update = _track(state, node_name="derive_expectation_variation")\n',
    '        scene_plan = (\n',
    '            dict(state.get("scene_plan_record"))\n',
    '            if isinstance(state.get("scene_plan_record"), dict)\n',
    '            else {}\n',
    '        )\n',
    '        result = derive_expectation_variation(\n',
    '            scene_plan_record=scene_plan,\n',
    '            scene_energy_target=state.get("scene_energy_target")\n',
    '            if isinstance(state.get("scene_energy_target"), dict)\n',
    '            else None,\n',
    '            pacing_rhythm_target=state.get("pacing_rhythm_target")\n',
    '            if isinstance(state.get("pacing_rhythm_target"), dict)\n',
    '            else None,\n',
    '            social_pressure_target=state.get("social_pressure_target")\n',
    '            if isinstance(state.get("social_pressure_target"), dict)\n',
    '            else None,\n',
    '            sensory_context_target=state.get("sensory_context_target")\n',
    '            if isinstance(state.get("sensory_context_target"), dict)\n',
    '            else None,\n',
    '            improvisational_coherence_target=state.get("improvisational_coherence_target")\n',
    '            if isinstance(state.get("improvisational_coherence_target"), dict)\n',
    '            else None,\n',
    '            information_disclosure_target=state.get("information_disclosure_target")\n',
    '            if isinstance(state.get("information_disclosure_target"), dict)\n',
    '            else None,\n',
    '            dramatic_irony_record=state.get("dramatic_irony_record")\n',
    '            if isinstance(state.get("dramatic_irony_record"), dict)\n',
    '            else None,\n',
    '            prior_consequence_cascade_state=state.get("prior_consequence_cascade_state")\n',
    '            if isinstance(state.get("prior_consequence_cascade_state"), dict)\n',
    '            else None,\n',
    '            prior_expectation_variation_state=state.get("prior_expectation_variation_state")\n',
    '            if isinstance(state.get("prior_expectation_variation_state"), dict)\n',
    '            else None,\n',
    '            prior_planner_truth=state.get("prior_planner_truth")\n',
    '            if isinstance(state.get("prior_planner_truth"), dict)\n',
    '            else None,\n',
    '            module_runtime_policy=state.get("module_runtime_policy")\n',
    '            if isinstance(state.get("module_runtime_policy"), dict)\n',
    '            else None,\n',
    '        )\n',
    '        target = result.get("target") if isinstance(result.get("target"), dict) else {}\n',
    '        variation_state = result.get("state") if isinstance(result.get("state"), dict) else {}\n',
    '        if variation_state:\n',
    '            scene_plan["expectation_variation_state"] = variation_state\n',
    '        if target:\n',
    '            scene_plan["expectation_variation_target"] = target\n',
    '        update["scene_plan_record"] = scene_plan\n',
    '        update["expectation_variation_state"] = variation_state\n',
    '        update["expectation_variation_target"] = target\n',
    '        update["turn_aspect_ledger"] = set_aspect_record(\n',
    '            state.get("turn_aspect_ledger") if isinstance(state.get("turn_aspect_ledger"), dict) else {},\n',
    '            ASPECT_EXPECTATION_VARIATION,\n',
    '            build_expectation_variation_aspect_record(\n',
    '                target=target,\n',
    '                state=variation_state,\n',
    '                policy=result.get("policy") if isinstance(result.get("policy"), dict) else None,\n',
    '            ),\n',
    '        )\n',
    '        return update\n',
    '\n',
    '    def _derive_narrative_momentum(self, state: RuntimeTurnState) -> RuntimeTurnState:\n',
    '        update = _track(state, node_name="derive_narrative_momentum")\n',
    '        scene_plan = (\n',
    '            dict(state.get("scene_plan_record"))\n',
    '            if isinstance(state.get("scene_plan_record"), dict)\n',
    '            else {}\n',
    '        )\n',
    '        result = derive_narrative_momentum(\n',
    '            scene_plan_record=scene_plan,\n',
    '            scene_energy_target=state.get("scene_energy_target")\n',
    '            if isinstance(state.get("scene_energy_target"), dict)\n',
    '            else None,\n',
    '            pacing_rhythm_target=state.get("pacing_rhythm_target")\n',
    '            if isinstance(state.get("pacing_rhythm_target"), dict)\n',
    '            else None,\n',
    '            social_pressure_target=state.get("social_pressure_target")\n',
    '            if isinstance(state.get("social_pressure_target"), dict)\n',
    '            else None,\n',
    '            expectation_variation_target=state.get("expectation_variation_target")\n',
    '            if isinstance(state.get("expectation_variation_target"), dict)\n',
    '            else None,\n',
    '            prior_narrative_momentum_state=state.get("prior_narrative_momentum_state")\n',
    '            if isinstance(state.get("prior_narrative_momentum_state"), dict)\n',
    '            else None,\n',
    '            prior_planner_truth=state.get("prior_planner_truth")\n',
    '            if isinstance(state.get("prior_planner_truth"), dict)\n',
    '            else None,\n',
    '            module_runtime_policy=state.get("module_runtime_policy")\n',
    '            if isinstance(state.get("module_runtime_policy"), dict)\n',
    '            else None,\n',
    '        )\n',
    '        momentum_state = result.get("state") if isinstance(result.get("state"), dict) else {}\n',
    '        target = result.get("target") if isinstance(result.get("target"), dict) else {}\n',
    '        if momentum_state:\n',
    '            scene_plan["narrative_momentum_state"] = momentum_state\n',
    '        if target:\n',
    '            scene_plan["narrative_momentum_target"] = target\n',
    '        update["scene_plan_record"] = scene_plan\n',
    '        update["narrative_momentum_state"] = momentum_state\n',
    '        update["narrative_momentum_target"] = target\n',
    '        update["turn_aspect_ledger"] = set_aspect_record(\n',
    '            state.get("turn_aspect_ledger") if isinstance(state.get("turn_aspect_ledger"), dict) else {},\n',
    '            ASPECT_NARRATIVE_MOMENTUM,\n',
    '            build_narrative_momentum_aspect_record(\n',
    '                target=target,\n',
    '                state=momentum_state,\n',
    '                policy=result.get("policy") if isinstance(result.get("policy"), dict) else None,\n',
    '            ),\n',
    '        )\n',
    '        return update\n',
    '\n',
    '    def _build_context_synthesis_bundle_for_state(\n',
    '        self,\n',
    '        state: RuntimeTurnState,\n',
    '        *,\n',
    '        validation_feedback: dict[str, Any] | None = None,\n',
    '    ) -> dict[str, Any]:\n',
]
