"""Executor run preparation.

Begins RuntimeTurnGraphExecutor.run by preparing the incoming state, ledger, diagnostics, routing metadata, and initial graph invocation context.
"""
SOURCE_LINES = [
    '    def run(\n',
    '        self,\n',
    '        *,\n',
    '        session_id: str,\n',
    '        module_id: str,\n',
    '        current_scene_id: str,\n',
    '        player_input: str,\n',
    '        trace_id: str | None = None,\n',
    '        host_versions: dict[str, Any] | None = None,\n',
    '        active_narrative_threads: list[dict[str, Any]] | None = None,\n',
    '        thread_pressure_summary: str | None = None,\n',
    '        host_experience_template: dict[str, Any] | None = None,\n',
    '        force_experiment_preview: bool | None = None,\n',
    '        prior_continuity_impacts: list[dict[str, Any]] | None = None,\n',
    '        prior_dramatic_signature: dict[str, str] | None = None,\n',
    '        prior_social_state_record: dict[str, Any] | None = None,\n',
    '        prior_narrative_thread_state: dict[str, Any] | None = None,\n',
    '        prior_callback_web_state: dict[str, Any] | None = None,\n',
    '        prior_consequence_cascade_state: dict[str, Any] | None = None,\n',
    '        prior_temporal_control_state: dict[str, Any] | None = None,\n',
    '        prior_expectation_variation_state: dict[str, Any] | None = None,\n',
    '        prior_narrative_momentum_state: dict[str, Any] | None = None,\n',
    '        prior_genre_awareness_state: dict[str, Any] | None = None,\n',
    '        prior_symbolic_object_resonance_state: dict[str, Any] | None = None,\n',
    '        prior_pacing_rhythm_state: dict[str, Any] | None = None,\n',
    '        prior_social_pressure_state: dict[str, Any] | None = None,\n',
    '        prior_relationship_state_record: dict[str, Any] | None = None,\n',
    '        prior_planner_truth: dict[str, Any] | None = None,\n',
    '        hierarchical_memory_context: dict[str, Any] | None = None,\n',
    '        turn_number: int | None = None,\n',
    '        turn_id: str | None = None,\n',
    '        turn_timestamp_iso: str | None = None,\n',
    '        turn_initiator_type: str | None = None,\n',
    '        turn_input_class: str | None = None,\n',
    '        turn_execution_mode: str | None = None,\n',
    '        live_player_truth_surface: bool | None = None,\n',
    '        actor_lane_context: dict[str, Any] | None = None,\n',
    '        session_input_language: str | None = None,\n',
    '        session_output_language: str | None = None,\n',
    '        story_runtime_experience: dict[str, Any] | None = None,\n',
    '        validation_execution_mode: str | None = None,\n',
    '        environment_state: dict[str, Any] | None = None,\n',
    '        canonical_step_id: str | None = None,\n',
    '        canonical_path: dict[str, Any] | None = None,\n',
    '        current_step_scene_id: str | None = None,\n',
    '        current_step_named_characters: list[str] | None = None,\n',
    '        prior_director_gathering_state: dict[str, Any] | None = None,\n',
    '        w5_latest_snapshot: dict[str, Any] | None = None,\n',
    '    ) -> RuntimeTurnState:\n',
    '        """Describe what ``run`` does in one line (verb-led summary for\n',
    '        this method).\n',
    '        \n',
    '        Behaviour, edge cases, and invariants should be inferred from the implementation and public contract of this symbol.\n',
    '        \n',
    '        Args:\n',
    '            session_id: ``session_id`` (str); meaning follows the type and call sites.\n',
    '            module_id: ``module_id`` (str); meaning follows the type and call sites.\n',
    '            current_scene_id: ``current_scene_id`` (str); meaning follows the type and call sites.\n',
    '            player_input: ``player_input`` (str); meaning follows the type and call sites.\n',
    '            trace_id: ``trace_id`` (str | None); meaning follows the type and call sites.\n',
    '            host_versions: ``host_versions`` (dict[str,\n',
    '                Any] | None); meaning follows the type and call sites.\n',
    '            active_narrative_threads: ``active_narrative_threads`` (list[dict[str, Any]] |\n',
    '                None); meaning follows the type and call sites.\n',
    '            thread_pressure_summary: ``thread_pressure_summary`` (str | None); meaning follows the type and call sites.\n',
    '            host_experience_template: ``host_experience_template`` (dict[str, Any] | None); meaning follows the type and call sites.\n',
    '            force_experiment_preview: ``force_experiment_preview`` (bool | None); meaning follows the type and call sites.\n',
    '            prior_continuity_impacts: ``prior_continuity_impacts`` (list[dict[str, Any]] |\n',
    '                None); meaning follows the type and call sites.\n',
    '            prior_dramatic_signature: ``prior_dramatic_signature`` (dict[str, str] | None); meaning follows the type and call sites.\n',
    '            prior_social_state_record: previously committed social-state record\n',
    '                rehydrated from planner truth.\n',
    '            prior_narrative_thread_state: committed narrative-thread continuity\n',
    '                snapshot rehydrated from the story session.\n',
    '            prior_callback_web_state: bounded committed callback-web feedback\n',
    '                snapshot rehydrated from the story session.\n',
    '            prior_consequence_cascade_state: bounded committed consequence\n',
    '                cascade feedback snapshot rehydrated from the story session.\n',
    '            prior_temporal_control_state: bounded committed temporal-control\n',
    '                feedback snapshot rehydrated from the story session.\n',
    '            prior_expectation_variation_state: bounded committed variation\n',
    '                feedback snapshot rehydrated from the story session.\n',
    '            prior_narrative_momentum_state: bounded committed momentum\n',
    '                state-machine snapshot rehydrated from the story session.\n',
    '            prior_genre_awareness_state: bounded committed genre-awareness\n',
    '                snapshot rehydrated from the story session.\n',
    '            prior_symbolic_object_resonance_state: bounded committed\n',
    '                symbolic-object feedback snapshot rehydrated from the story session.\n',
    '            prior_pacing_rhythm_state: bounded committed rhythm feedback\n',
    '                snapshot rehydrated from the story session.\n',
    '            prior_social_pressure_state: bounded committed pressure metric\n',
    '                snapshot rehydrated from the story session.\n',
    '            prior_relationship_state_record: bounded committed relationship\n',
    '                state-machine snapshot rehydrated from the story session.\n',
    '            prior_planner_truth: bounded committed planner-truth snapshot used\n',
    '                to bias retrieval toward continuity-relevant precedents.\n',
    '            hierarchical_memory_context: bounded committed memory context\n',
    '                derived from canonical turn records.\n',
    '            turn_number: ``turn_number`` (int | None); meaning follows the type and call sites.\n',
    '            turn_id: ``turn_id`` (str | None); meaning follows the type and call sites.\n',
    '            turn_timestamp_iso: ``turn_timestamp_iso`` (str | None); meaning follows the type and call sites.\n',
    '            turn_initiator_type: ``turn_initiator_type`` (str | None); meaning follows the type and call sites.\n',
    '            turn_input_class: ``turn_input_class`` (str |\n',
    '                None); meaning follows the type and call sites.\n',
    '            turn_execution_mode: ``turn_execution_mode`` (str | None); meaning follows the type and call sites.\n',
    '        \n',
    '        Returns:\n',
    '            RuntimeTurnState:\n',
    '                Returns a value of type ``RuntimeTurnState``; see the function body for structure, error paths, and sentinels.\n',
    '        """\n',
    '        ts = turn_timestamp_iso\n',
    '        if not ts:\n',
    '            ts = datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")\n',
    '        tid = turn_id if turn_id is not None else (trace_id or "")\n',
    '        effective_turn_number = int(turn_number or 0)\n',
    '        effective_turn_kind = str(\n',
    '            turn_input_class\n',
    '            or ("opening" if effective_turn_number <= 0 else turn_initiator_type)\n',
    '            or "player"\n',
    '        ).strip() or "player"\n',
    '        runtime_profile_id = _runtime_profile_id_from_host_template(host_experience_template)\n',
    '        initial_state: RuntimeTurnState = {\n',
    '            "session_id": session_id,\n',
    '            "module_id": module_id,\n',
    '            "current_scene_id": current_scene_id,\n',
    '            "player_input": player_input,\n',
    '            "trace_id": trace_id or "",\n',
    '            "host_versions": host_versions or {},\n',
    '            "host_experience_template": host_experience_template or {},\n',
    '            "nodes_executed": [],\n',
    '            "node_outcomes": {},\n',
    '            "graph_errors": [],\n',
    '            "failure_markers": [],\n',
    '            "fallback_markers": [],\n',
    '            "turn_timestamp_iso": ts,\n',
    '            "turn_id": tid,\n',
    '            "turn_initiator_type": turn_initiator_type or "player",\n',
    '            "turn_execution_mode": turn_execution_mode or "langgraph_runtime_turn_graph",\n',
    '            "turn_aspect_ledger": initialize_runtime_aspect_ledger(\n',
    '                session_id=session_id,\n',
    '                module_id=module_id,\n',
    '                turn_number=effective_turn_number,\n',
    '                turn_kind=effective_turn_kind,\n',
    '                raw_player_input=player_input if effective_turn_number > 0 else None,\n',
    '                input_kind=turn_input_class,\n',
    '                turn_id=tid,\n',
    '                trace_id=trace_id,\n',
    '                runtime_profile_id=runtime_profile_id,\n',
    '            ),\n',
    '        }\n',
    '        try:\n',
    '            module_policy = load_module_runtime_policy(\n',
    '                module_id=module_id,\n',
    '                runtime_profile_id=runtime_profile_id,\n',
    '            ).to_dict()\n',
    '            initial_state["module_runtime_policy"] = module_policy\n',
    '        except Exception as exc:\n',
    '            module_policy = {}\n',
    '            initial_state["module_runtime_policy"] = {\n',
    '                "schema_version": "module_runtime_policy.v1",\n',
    '                "module_id": module_id,\n',
    '                "runtime_profile_id": runtime_profile_id,\n',
    '                "policy_load_status": "failed",\n',
    '                "failure_reason": str(exc),\n',
    '            }\n',
    '        env_model = build_environment_model(\n',
    '            module_id=module_id,\n',
    '            runtime_profile_id=runtime_profile_id,\n',
    '        )\n',
    '        initial_state["environment_model"] = env_model\n',
    '        initial_state["environment_state"] = normalize_environment_state(\n',
    '            environment_state,\n',
    '            module_id=module_id,\n',
    '            environment_model=env_model,\n',
    '            runtime_projection=host_experience_template,\n',
    '            actor_lane_context=actor_lane_context,\n',
    '            turn_number=effective_turn_number,\n',
    '        )\n',
    '        if turn_number is not None:\n',
    '            initial_state["turn_number"] = int(turn_number)\n',
]
