"""Director selection parameters.

Derives dramatic parameters, responder sets, pressure choices, and generation constraints for the model turn.
"""
SOURCE_LINES = [
    '            speech_policy=semantic_scene_plan.get("speech_policy")\n',
    '            if isinstance(semantic_scene_plan.get("speech_policy"), dict)\n',
    '            else {},\n',
    '            quote_moment_policy=semantic_scene_plan.get("quote_moment_policy")\n',
    '            if isinstance(semantic_scene_plan.get("quote_moment_policy"), dict)\n',
    '            else {},\n',
    '            dialogue_plan=semantic_scene_plan.get("dialogue_plan")\n',
    '            if isinstance(semantic_scene_plan.get("dialogue_plan"), list)\n',
    '            else [],\n',
    '            capability_manager_plan=semantic_scene_plan.get("capability_manager_plan")\n',
    '            if isinstance(semantic_scene_plan.get("capability_manager_plan"), dict)\n',
    '            else {},\n',
    '            continuity_obligation=semantic_scene_plan.get("continuity_obligation")\n',
    '            if isinstance(semantic_scene_plan.get("continuity_obligation"), dict)\n',
    '            else {},\n',
    '            expected_transition_pattern=str(\n',
    '                semantic_scene_plan.get("expected_transition_pattern") or "soft"\n',
    '            ),\n',
    '            planner_rationale_codes=rationale_codes,\n',
    '            semantic_move_fingerprint=sem_fp,\n',
    '            social_state_fingerprint=soc_fp,\n',
    '            semantic_scene_planner_version=str(\n',
    '                semantic_scene_plan.get("semantic_scene_planner_version")\n',
    '                or "goc_semantic_scene_planner_v1"\n',
    '            ),\n',
    '            selection_source=str(resolution.get("selection_source") or "semantic_pipeline_v1"),\n',
    '        )\n',
    '        scene_plan_dict = scene_plan.to_runtime_dict()\n',
    '        # GOC-KNOWLEDGE-RUNTIME-INTEGRATION P1.1: record which structured knowledge surfaces the\n',
    '        # planner had available so dashboards/diagnostics can answer "did the director see X?".\n',
    '        knowledge_loaded = state.get("knowledge_runtime_loaded") if isinstance(state.get("knowledge_runtime_loaded"), dict) else {}\n',
    '        _content_sources: list[str] = []\n',
    '        for _src_key, _src_flag in (\n',
    '            ("actor_pressure_profiles", "actor_pressure_profiles_loaded"),\n',
    '            ("character_documents", "character_documents_loaded"),\n',
    '            ("scene_graph", "scene_graph_loaded"),\n',
    '            ("canonical_path", "canonical_path_loaded"),\n',
    '            ("modularity_policy", "modularity_policy_loaded"),\n',
    '            ("beat_library", "beat_library_loaded"),\n',
    '            ("opening_quote_anchors", "opening_quote_anchors_loaded"),\n',
    '            ("locations", "locations_loaded"),\n',
    '            ("objects", "objects_loaded"),\n',
    '            ("content_access_policy", "content_access_policy_loaded"),\n',
    '            ("phase_beat_policy", "phase_beat_policy_loaded"),\n',
    '            ("hard_forbidden_rules", "hard_forbidden_rules_loaded"),\n',
    '            ("opening_scene_sequence", "opening_scene_sequence_loaded"),\n',
    '            ("apartment_layout", "apartment_layout_loaded"),\n',
    '            ("scene_affordances", "scene_affordances_loaded"),\n',
    '            ("narrator_sensory_palette", "narrator_sensory_palette_loaded"),\n',
    '            ("premise_and_backstory", "premise_and_backstory_loaded"),\n',
    '        ):\n',
    '            if knowledge_loaded.get(_src_flag):\n',
    '                _content_sources.append(_src_key)\n',
    '        scene_plan_dict["scene_director_content_sources"] = _content_sources\n',
    '        _pbp = state.get("phase_beat_policy") if isinstance(state.get("phase_beat_policy"), dict) else {}\n',
    '        _phase_id_for_policy = str(state.get("current_scene_id") or "").strip().lower()\n',
    '        _phase_block = _pbp.get("phases", {}).get(_phase_id_for_policy) if isinstance(_pbp.get("phases"), dict) else None\n',
    '        if isinstance(_phase_block, dict):\n',
    '            scene_plan_dict["phase_policy_applied"] = {\n',
    '                "phase_id": _phase_id_for_policy,\n',
    '                "allowed_beats": list(_phase_block.get("allowed_beats") or _phase_block.get("allowed_narrator_beats") or [])\n',
    '                if isinstance(_phase_block.get("allowed_beats") or _phase_block.get("allowed_narrator_beats"), list)\n',
    '                else [],\n',
    '                "forbidden_beats": list(_phase_block.get("forbidden_beats") or _phase_block.get("forbidden_early_escalations") or [])\n',
    '                if isinstance(_phase_block.get("forbidden_beats") or _phase_block.get("forbidden_early_escalations"), list)\n',
    '                else [],\n',
    '            }\n',
    '        _actor_profiles_block = state.get("actor_pressure_profiles") if isinstance(state.get("actor_pressure_profiles"), dict) else {}\n',
    '        _responder_actor_id = str(scene_plan_dict.get("responder_actor_id") or "").strip()\n',
    '        if _responder_actor_id and isinstance(_actor_profiles_block.get(_responder_actor_id), dict):\n',
    '            scene_plan_dict["actor_pressure_profile_used"] = {\n',
    '                "actor_id": _responder_actor_id,\n',
    '                "profile_keys": sorted(list(_actor_profiles_block[_responder_actor_id].keys())),\n',
    '            }\n',
    '        # NPC participation policy: respect actor_lane forbidden ids; record human exclusion.\n',
    '        _alc = state.get("actor_lane_context") if isinstance(state.get("actor_lane_context"), dict) else {}\n',
    '        scene_plan_dict["npc_participation_policy"] = {\n',
    '            "human_actor_id": _alc.get("human_actor_id"),\n',
    '            "ai_forbidden_actor_ids": list(_alc.get("ai_forbidden_actor_ids") or []) if isinstance(_alc.get("ai_forbidden_actor_ids"), list) else [],\n',
    '            "selected_responder_set": [\n',
    '                str(_row.get("actor_id") or "").strip()\n',
    '                for _row in (state.get("selected_responder_set") if isinstance(state.get("selected_responder_set"), list) else [])\n',
    '                if isinstance(_row, dict) and str(_row.get("actor_id") or "").strip()\n',
    '            ],\n',
    '        }\n',
    '        if str(state.get("turn_input_class") or "").strip().lower() == "opening":\n',
    '            opening_meta = build_opening_scene_plan_metadata(\n',
    '                opening_scene_sequence=state.get("opening_scene_sequence")\n',
    '                if isinstance(state.get("opening_scene_sequence"), dict)\n',
    '                else (yslice.get("opening_scene_sequence") if isinstance(yslice, dict) else {}),\n',
    '                hard_forbidden_rules=state.get("hard_forbidden_rules")\n',
    '                if isinstance(state.get("hard_forbidden_rules"), dict)\n',
    '                else (yslice.get("hard_forbidden_rules") if isinstance(yslice, dict) else {}),\n',
    '                actor_lane_context=state.get("actor_lane_context")\n',
    '                if isinstance(state.get("actor_lane_context"), dict)\n',
    '                else None,\n',
    '            )\n',
    '            scene_plan_dict.update(opening_meta)\n',
    '            rationale_codes.append("opening_scene_sequence_runtime_contract")\n',
    '            if opening_meta.get("opening_scene_sequence_id"):\n',
    '                rationale_codes.append(f"opening_scene_sequence:{opening_meta[\'opening_scene_sequence_id\']}")\n',
    '            scene_plan_dict["planner_rationale_codes"] = rationale_codes\n',
    '            update["scene_assessment"] = {\n',
    '                **(update.get("scene_assessment") if isinstance(update.get("scene_assessment"), dict) else merged_sa),\n',
    '                "opening_scene_sequence_id": opening_meta.get("opening_scene_sequence_id"),\n',
    '                "opening_first_playable_scene_phase": opening_meta.get("opening_first_playable_scene_phase"),\n',
    '                "hard_forbidden_constraints_active": bool(opening_meta.get("hard_forbidden_rule_ids")),\n',
    '            }\n',
    '        update["scene_plan_record"] = scene_plan_dict\n',
    '        prior_sig = state.get("prior_dramatic_signature") if isinstance(state.get("prior_dramatic_signature"), dict) else {}\n',
    '        prior_beat_id = str(prior_sig.get("prior_beat_id") or "").strip() or None\n',
    '        scene_id = str(state.get("current_scene_id") or "").strip() or "unknown_scene"\n',
    '        candidate_functions = [\n',
    '            str(item).strip()\n',
    '            for item in (resolution.get("candidates") or [])\n',
    '            if str(item).strip()\n',
    '        ]\n',
    '        if scene_fn not in candidate_functions:\n',
    '            candidate_functions.append(scene_fn)\n',
    '        deterministic_beat_id = f"{scene_id}:{scene_fn}"\n',
    '        capability_manager_plan = (\n',
    '            scene_plan_dict.get("capability_manager_plan")\n',
    '            if isinstance(scene_plan_dict.get("capability_manager_plan"), dict)\n',
    '            else {}\n',
    '        )\n',
    '        manager_selected_capabilities = executable_capabilities_from_manager_plan(capability_manager_plan)\n',
    '        expected_realization: list[str] = []\n',
    '        interp_for_beat = state.get("interpreted_input") if isinstance(state.get("interpreted_input"), dict) else {}\n',
    '        if capability_manager_plan.get("run_only_selected_capabilities") and manager_selected_capabilities:\n',
    '            expected_realization = list(dict.fromkeys(manager_selected_capabilities))\n',
    '        else:\n',
    '            if bool(interp_for_beat.get("narrator_response_expected")):\n',
    '                expected_realization.append(NARRATOR_ACTION_CONSEQUENCE_DESCRIBE)\n',
    '            if bool(interp_for_beat.get("npc_response_expected")) or responders:\n',
    '                expected_realization.append(NPC_SOCIAL_REACTION_OPTIONAL)\n',
    '        # PR-C: beat-consumption gate — suppress mandatory-beat consumption\n',
    '        # while director_gathering_state.paused is True. The player remains\n',
    '        # free, narrator local consequences are not blocked, but mandatory\n',
    '        # beats tied to the missing co-presence do not advance.\n',
    '        _pr_c_gathering = (\n',
    '            update.get("director_gathering_state")\n',
    '            or (state.get("director_gathering_state") if isinstance(state.get("director_gathering_state"), dict) else None)\n',
    '        )\n',
    '        _pr_c_beat_suppressed = should_suppress_mandatory_beat_consumption(_pr_c_gathering)\n',
    '        if _pr_c_beat_suppressed:\n',
    '            beat_candidates = []\n',
    '            beat_selection = select_beat_candidate(\n',
    '                [],\n',
    '                deterministic_fallback_id=deterministic_beat_id,\n',
    '                selection_source="director_gathering_paused_gate",\n',
    '                selection_reason="mandatory_beat_consumption_suppressed_while_gathering_paused",\n',
    '            )\n',
    '            selected_beat_id = deterministic_beat_id\n',
    '            scene_plan_dict["gathering_paused_beat_suppression"] = True\n',
    '            update["gathering_paused_beat_suppression"] = True\n',
    '        else:\n',
    '            scene_plan_dict["gathering_paused_beat_suppression"] = False\n',
    '            scene_plan_dict["gathering_paused_beat_suppression_reason"] = (\n',
    '                "director_gathering_not_paused"\n',
    '            )\n',
    '            update["gathering_paused_beat_suppression"] = False\n',
    '            beat_candidates = phase_beat_candidates(\n',
    '                module_policy=state.get("module_runtime_policy")\n',
    '                if isinstance(state.get("module_runtime_policy"), dict)\n',
    '                else None,\n',
    '                phase_id=scene_id,\n',
    '                fallback_candidate_ids=[f"{scene_id}:{fn}" for fn in candidate_functions] or [deterministic_beat_id],\n',
    '                expected_visible_functions=expected_realization,\n',
    '            )\n',
    '            beat_selection = select_beat_candidate(\n',
    '                beat_candidates,\n',
    '                deterministic_fallback_id=deterministic_beat_id,\n',
    '                selection_source=str(resolution.get("selection_source") or "scene_director"),\n',
    '                selection_reason=str(resolution.get("selection_source") or "semantic_pipeline_v1"),\n',
    '            )\n',
    '            selected_beat_id = beat_selection.selected_beat_id or deterministic_beat_id\n',
    '        scene_plan_dict.setdefault(\n',
    '            "selection_source",\n',
    '            str(resolution.get("selection_source") or "scene_director"),\n',
    '        )\n',
]
