"""Director selection opening state.

Starts dramatic parameter selection with opening-scene policy, selected scene identity, and director prerequisites.
"""
SOURCE_LINES = [
    '                if isinstance(state.get("active_narrative_threads"), list)\n',
    '                else None,\n',
    '                thread_pressure_summary=state.get("thread_pressure_summary")\n',
    '                if isinstance(state.get("thread_pressure_summary"), str)\n',
    '                else None,\n',
    '                scene_assessment=unresolved,\n',
    '                prior_social_state_record=state.get("prior_social_state_record")\n',
    '                if isinstance(state.get("prior_social_state_record"), dict)\n',
    '                else None,\n',
    '            )\n',
    '            update["semantic_move_record"] = sem_u.to_runtime_dict()\n',
    '            update["social_state_record"] = soc_u.to_runtime_dict()\n',
    '            return update\n',
    '        prior = state.get("prior_continuity_impacts") if isinstance(state.get("prior_continuity_impacts"), list) else None\n',
    '        yslice = state.get("goc_yaml_slice") if isinstance(state.get("goc_yaml_slice"), dict) else None\n',
    '        interpreted_input = state.get("interpreted_input") if isinstance(state.get("interpreted_input"), dict) else {}\n',
    '        interpreted_move = state.get("interpreted_move") if isinstance(state.get("interpreted_move"), dict) else {}\n',
    '        base_sa = build_scene_assessment(\n',
    '            module_id=module_id,\n',
    '            current_scene_id=state.get("current_scene_id") or "",\n',
    '            canonical_yaml=yaml_blob,\n',
    '            prior_continuity_impacts=prior,\n',
    '            yaml_slice=yslice,\n',
    '            prior_narrative_thread_state=state.get("prior_narrative_thread_state")\n',
    '            if isinstance(state.get("prior_narrative_thread_state"), dict)\n',
    '            else None,\n',
    '        )\n',
    '        callback_state = (\n',
    '            state.get("prior_callback_web_state")\n',
    '            if isinstance(state.get("prior_callback_web_state"), dict)\n',
    '            else {}\n',
    '        )\n',
    '        if callback_state:\n',
    '            base_sa["callback_web_feedback"] = {\n',
    '                "feedback_contract": callback_state.get("feedback_contract"),\n',
    '                "edge_count": int(callback_state.get("edge_count") or 0),\n',
    '                "observation_count": int(callback_state.get("observation_count") or 0),\n',
    '                "selected_callback_edge_id": callback_state.get("selected_callback_edge_id"),\n',
    '                "selected_callback_kind": callback_state.get("selected_callback_kind"),\n',
    '                "selected_continuity_classes": callback_state.get("selected_continuity_classes")\n',
    '                or [],\n',
    '                "selected_thread_ids": callback_state.get("selected_thread_ids") or [],\n',
    '            }\n',
    '        cascade_state = (\n',
    '            state.get("prior_consequence_cascade_state")\n',
    '            if isinstance(state.get("prior_consequence_cascade_state"), dict)\n',
    '            else {}\n',
    '        )\n',
    '        if cascade_state:\n',
    '            base_sa["consequence_cascade_feedback"] = {\n',
    '                "feedback_contract": cascade_state.get("feedback_contract"),\n',
    '                "atom_count": int(cascade_state.get("atom_count") or 0),\n',
    '                "edge_count": int(cascade_state.get("edge_count") or 0),\n',
    '                "selected_consequence_ids": cascade_state.get("selected_consequence_ids") or [],\n',
    '                "selected_continuity_classes": cascade_state.get("selected_continuity_classes")\n',
    '                or [],\n',
    '                "selected_statuses": cascade_state.get("selected_statuses") or [],\n',
    '            }\n',
    '        pc = prior_continuity_classes(prior)\n',
    '        semantic_player_input = "" if _is_engine_opening_turn(state) else state.get("player_input") or ""\n',
    '        sem_model = interpret_goc_semantic_move(\n',
    '            module_id=module_id,\n',
    '            player_input=semantic_player_input,\n',
    '            interpreted_input=interpreted_input,\n',
    '            interpreted_move=interpreted_move,\n',
    '            prior_continuity_classes=pc,\n',
    '        )\n',
    '        sem_dict = sem_model.to_runtime_dict()\n',
    '        soc_model = build_social_state_record(\n',
    '            prior_continuity_impacts=prior,\n',
    '            active_narrative_threads=state.get("active_narrative_threads")\n',
    '            if isinstance(state.get("active_narrative_threads"), list)\n',
    '            else None,\n',
    '            thread_pressure_summary=state.get("thread_pressure_summary")\n',
    '            if isinstance(state.get("thread_pressure_summary"), str)\n',
    '            else None,\n',
    '            scene_assessment=base_sa,\n',
    '            prior_social_state_record=state.get("prior_social_state_record")\n',
    '            if isinstance(state.get("prior_social_state_record"), dict)\n',
    '            else None,\n',
    '            yaml_slice=yslice,\n',
    '        )\n',
    '        soc_dict = soc_model.to_runtime_dict()\n',
    '        base_sa["semantic_move_fingerprint"] = semantic_move_fingerprint(sem_model)\n',
    '        base_sa["social_state_fingerprint"] = social_state_fingerprint(soc_model)\n',
    '        update["scene_assessment"] = base_sa\n',
    '        update["semantic_move_record"] = sem_dict\n',
    '        update["social_state_record"] = soc_dict\n',
    '        return update\n',
    '\n',
    '    def _director_select_dramatic_parameters(self, state: RuntimeTurnState) -> RuntimeTurnState:\n',
    '        """Describe what ``_director_select_dramatic_parameters`` does in\n',
    '        one line (verb-led summary for this method).\n',
    '        \n',
    '        Behaviour, edge cases, and invariants should be inferred from the implementation and public contract of this symbol.\n',
    '        \n',
    '        Args:\n',
    '            state: ``state`` (RuntimeTurnState); meaning follows the type and call sites.\n',
    '        \n',
    '        Returns:\n',
    '            RuntimeTurnState:\n',
    '                Returns a value of type ``RuntimeTurnState``; see the function body for structure, error paths, and sentinels.\n',
    '        """\n',
    '        update = _track(state, node_name="director_select_dramatic_parameters")\n',
    '        module_id = state.get("module_id") or ""\n',
    '        interpreted_move = state.get("interpreted_move") if isinstance(state.get("interpreted_move"), dict) else {}\n',
    '        engine_opening_turn = _is_engine_opening_turn(state)\n',
    '        player_input = "" if engine_opening_turn else state.get("player_input") or ""\n',
    '        pacing, silence = build_pacing_and_silence(\n',
    '            player_input=player_input,\n',
    '            interpreted_move=interpreted_move,\n',
    '            module_id=module_id,\n',
    '            prior_narrative_thread_state=state.get("prior_narrative_thread_state")\n',
    '            if isinstance(state.get("prior_narrative_thread_state"), dict)\n',
    '            else None,\n',
    '            semantic_move_record=state.get("semantic_move_record")\n',
    '            if isinstance(state.get("semantic_move_record"), dict)\n',
    '            else None,\n',
    '            prior_planner_truth=state.get("prior_planner_truth")\n',
    '            if isinstance(state.get("prior_planner_truth"), dict)\n',
    '            else None,\n',
    '        )\n',
    '        if module_id != GOC_MODULE_ID:\n',
    '            update["selected_responder_set"] = []\n',
    '            update["selected_scene_function"] = "establish_pressure"\n',
    '            update["pacing_mode"] = pacing\n',
    '            update["silence_brevity_decision"] = silence\n',
    '            update["character_mind_records"] = []\n',
    '            update["character_voice_profiles"] = []\n',
    '            update["scene_plan_record"] = ScenePlanRecord(\n',
    '                selected_scene_function="establish_pressure",\n',
    '                selected_responder_set=[],\n',
    '                pacing_mode=pacing,\n',
    '                silence_brevity_decision=dict(silence),\n',
    '                planner_rationale_codes=["non_goc_slice"],\n',
    '                selection_source="non_goc_slice",\n',
    '            ).to_runtime_dict()\n',
    '            return update\n',
    '        prior = state.get("prior_continuity_impacts") if isinstance(state.get("prior_continuity_impacts"), list) else None\n',
    '        yslice = state.get("goc_yaml_slice") if isinstance(state.get("goc_yaml_slice"), dict) else None\n',
    '        base_sa = state.get("scene_assessment") if isinstance(state.get("scene_assessment"), dict) else {}\n',
    '        sem_rec = state.get("semantic_move_record") if isinstance(state.get("semantic_move_record"), dict) else None\n',
    '        soc_rec = state.get("social_state_record") if isinstance(state.get("social_state_record"), dict) else None\n',
    '        responders, scene_fn, implied, resolution = build_responder_and_function(\n',
    '            player_input=player_input,\n',
    '            interpreted_move=interpreted_move,\n',
    '            interpreted_input=state.get("interpreted_input")\n',
    '            if isinstance(state.get("interpreted_input"), dict)\n',
    '            else None,\n',
    '            pacing_mode=pacing,\n',
    '            prior_continuity_impacts=prior,\n',
    '            yaml_slice=yslice,\n',
    '            current_scene_id=state.get("current_scene_id") or "",\n',
    '            semantic_move_record=sem_rec,\n',
    '            social_state_record=soc_rec,\n',
    '            prior_narrative_thread_state=state.get("prior_narrative_thread_state")\n',
    '            if isinstance(state.get("prior_narrative_thread_state"), dict)\n',
    '            else None,\n',
    '        )\n',
    '        if engine_opening_turn:\n',
    '            responders = []\n',
    '            scene_fn = "establish_pressure"\n',
    '            resolution = {\n',
    '                "selection_source": "engine_opening_turn",\n',
    '                "candidates": ["establish_pressure"],\n',
    '                "reason": "opening_prompt_is_engine_instruction_not_player_move",\n',
    '            }\n',
    '        merged_sa = {**base_sa, "multi_pressure_resolution": resolution}\n',
    '        update["scene_assessment"] = merged_sa\n',
    '        update["selected_responder_set"] = responders\n',
    '        update["selected_scene_function"] = scene_fn\n',
    '        update["pacing_mode"] = pacing\n',
    '        update["silence_brevity_decision"] = silence\n',
    '        primary = responders[0] if responders and isinstance(responders[0], dict) else {}\n',
    "        # Derive the active cast from the module's YAML characters block and\n",
    "        # order it so the primary responder's key comes first. The\n",
    '        # God of Carnage fallback kicks in only when no YAML cast is\n',
    '        # published, so any module shipping an authored characters block\n',
    '        # works without further code changes here.\n',
    '        active_keys = _derive_active_character_keys(\n',
]
