"""Model routing and invocation.

Routes the model request, invokes the primary adapter, and decides the next graph step after invocation.
"""
SOURCE_LINES = [
    '    def _route_model(self, state: RuntimeTurnState) -> RuntimeTurnState:\n',
    '        """``_route_model`` — see implementation for behaviour and contracts.\n',
    '        \n',
    '        Behaviour, edge cases, and invariants should be inferred from the implementation and public contract of this symbol.\n',
    '        \n',
    '        Args:\n',
    '            state: ``state`` (RuntimeTurnState); meaning follows the type and call sites.\n',
    '        \n',
    '        Returns:\n',
    '            RuntimeTurnState:\n',
    '                Returns a value of type ``RuntimeTurnState``; see the function body for structure, error paths, and sentinels.\n',
    '        """\n',
    '        dramatic_requirements = _drama_aware_routing_requirements(state)\n',
    '        try:\n',
    '            decision = self.routing.choose(\n',
    '                task_type=state["task_type"],\n',
    '                dramatic_requirements=dramatic_requirements,\n',
    '            )\n',
    '        except TypeError:\n',
    '            decision = self.routing.choose(task_type=state["task_type"])\n',
    '        selected = self.registry.get(decision.selected_model)\n',
    '        update = _track(state, node_name="route_model")\n',
    '        fallback_chain: list[str] = [decision.selected_model]\n',
    '        if decision.fallback_model:\n',
    '            fallback_chain.append(decision.fallback_model)\n',
    '        code = decision.route_reason\n',
    '        if code not in ROUTING_LABELS:\n',
    '            code = "role_matrix_primary"\n',
    '        governed = bool(getattr(self.routing, "routes", None))\n',
    '        # Surface route-family truth onto the per-turn state. The governed\n',
    '        # routing policy exposes its most recent choice via\n',
    '        # ``_last_choice_meta`` so this node can publish it without changing\n',
    '        # the shared ``RoutingDecision`` dataclass in ``story_runtime_core``.\n',
    '        last_choice_meta = getattr(self.routing, "_last_choice_meta", None)\n',
    '        if not isinstance(last_choice_meta, dict):\n',
    '            last_choice_meta = {}\n',
    '        update["routing"] = {\n',
    '            "selected_model": decision.selected_model,\n',
    '            "selected_provider": decision.selected_provider,\n',
    '            "reason": decision.route_reason,\n',
    '            "route_reason_code": code,\n',
    '            "fallback_model": decision.fallback_model,\n',
    '            "fallback_chain": fallback_chain,\n',
    '            "route_mode": "primary_graph_route",\n',
    '            "policy_id_used": STORY_RUNTIME_ROUTING_POLICY_ID,\n',
    '            "policy_version_used": STORY_RUNTIME_ROUTING_POLICY_VERSION,\n',
    '            "timeout_seconds": selected.timeout_seconds if selected else None,\n',
    '            "structured_output_success": bool(selected.structured_output_capable) if selected else False,\n',
    '            "registered_adapter_providers": sorted(self.adapters.keys()),\n',
    '            "governed_runtime_story_path": governed,\n',
    '            "legacy_default_registry_path": not governed,\n',
    '            "route_id": last_choice_meta.get("route_id"),\n',
    '            "route_family": last_choice_meta.get("route_family"),\n',
    '            "route_family_expected": last_choice_meta.get("route_family_expected"),\n',
    '            "route_substitution_occurred": bool(\n',
    '                last_choice_meta.get("route_substitution_occurred")\n',
    '            ),\n',
    '            "generation_execution_mode": last_choice_meta.get("generation_execution_mode")\n',
    '            or (self.generation_execution_mode or None),\n',
    '            "mock_fallback_blocked": bool(last_choice_meta.get("mock_fallback_blocked")),\n',
    '            "drama_aware_requirements": dramatic_requirements,\n',
    '            "drama_aware_profile": last_choice_meta.get("drama_aware_profile"),\n',
    '        }\n',
    '        update["selected_provider"] = decision.selected_provider or ""\n',
    '        update["selected_timeout"] = float(selected.timeout_seconds) if selected else 10.0\n',
    '        return update\n',
    '\n',
    '    def _invoke_model(self, state: RuntimeTurnState) -> RuntimeTurnState:\n',
    '        """``_invoke_model`` — see implementation for behaviour and contracts.\n',
    '        \n',
    '        Behaviour, edge cases, and invariants should be inferred from the implementation and public contract of this symbol.\n',
    '        \n',
    '        Args:\n',
    '            state: ``state`` (RuntimeTurnState); meaning follows the type and call sites.\n',
    '        \n',
    '        Returns:\n',
    '            RuntimeTurnState:\n',
    '                Returns a value of type ``RuntimeTurnState``; see the function body for structure, error paths, and sentinels.\n',
    '        """\n',
    '        provider = state.get("selected_provider") or ""\n',
    '        adapter = self.adapters.get(provider)\n',
    '        routing = state.get("routing") if isinstance(state.get("routing"), dict) else {}\n',
    '        selected_mid = str(routing.get("selected_model") or "").strip()\n',
    '        spec = self.registry.get(selected_mid) if selected_mid else None\n',
    '        provider_model = (\n',
    '            str(getattr(spec, "provider_model_name", "") or "").strip()\n',
    '            if spec is not None\n',
    '            else ""\n',
    '        )\n',
    '        api_model = provider_model or (spec.model_name if spec is not None else None)\n',
    '        generation: dict[str, Any] = {\n',
    '            "attempted": False,\n',
    '            "success": None,\n',
    '            "error": None,\n',
    '            "retrieval_context_attached": bool(state.get("context_text")),\n',
    '            "prompt_length": len(state.get("model_prompt", "")),\n',
    '            "fallback_used": False,\n',
    '        }\n',
    '        outcome = "ok"\n',
    '        if adapter:\n',
    '            generation["attempted"] = True\n',
    '            _realize_cap = str(state.get("realize_via_capabilities_used_capability") or "").strip()\n',
    '            _parser_variant = (\n',
    '                "thin"\n',
    '                if _realize_cap.startswith("narrator.") or _realize_cap.startswith("actor_line.")\n',
    '                else "full"\n',
    '            )\n',
    '            invoke_kw: dict[str, Any] = {\n',
    '                "adapter": adapter,\n',
    '                "player_input": state["player_input"],\n',
    '                "interpreted_input": state.get("interpreted_input", {}) if isinstance(state.get("interpreted_input"), dict) else {},\n',
    '                "retrieval_context": state.get("context_text"),\n',
    '                "timeout_seconds": float(state.get("selected_timeout", 10.0)),\n',
    '                "model_prompt": state.get("model_prompt", ""),\n',
    '                "dramatic_generation_packet": state.get("dramatic_generation_packet")\n',
    '                if isinstance(state.get("dramatic_generation_packet"), dict)\n',
    '                else None,\n',
    '                "parser_variant": _parser_variant,\n',
    '            }\n',
    '            if api_model:\n',
    '                invoke_kw["model_name"] = api_model\n',
    '            runtime_result = _invoke_runtime_adapter_with_langchain(**invoke_kw)\n',
    '            call = runtime_result.call\n',
    '            generation["success"] = call.success\n',
    '            generation["error"] = call.metadata.get("error") if not call.success else None\n',
    '            generation["model_raw_text"] = call.content\n',
    '            structured = None\n',
    '            if runtime_result.parsed_output:\n',
    '                structured = runtime_result.parsed_output.model_dump(mode="json")\n',
    '            generation["metadata"] = {\n',
    '                **call.metadata,\n',
    '                "langchain_prompt_used": True,\n',
    '                "langchain_parser_error": runtime_result.parser_error,\n',
    '                "structured_output": structured,\n',
    '                "adapter_invocation_mode": ADAPTER_INVOCATION_LANGCHAIN_PRIMARY,\n',
    '                "dramatic_generation_packet_included": isinstance(\n',
    '                    state.get("dramatic_generation_packet"), dict\n',
    '                ),\n',
    '                "dramatic_generation_packet_scene_function": (\n',
    '                    state.get("dramatic_generation_packet", {}).get("selected_scene_function")\n',
    '                    if isinstance(state.get("dramatic_generation_packet"), dict)\n',
    '                    else None\n',
    '                ),\n',
    '                "dramatic_generation_packet_primary_responder": (\n',
    '                    state.get("dramatic_generation_packet", {}).get("primary_responder_id")\n',
    '                    if isinstance(state.get("dramatic_generation_packet"), dict)\n',
    '                    else None\n',
    '                ),\n',
    '            }\n',
    '            if not call.success:\n',
    '                outcome = "error"\n',
    '            # PRIMARY-PARSER-EVIDENCE-01: capture primary attempt evidence into a\n',
    '            # separate state key so it survives self-correction and LDSS overwrites.\n',
    '            raw_out = str(call.content or "").strip()\n',
    '            raw_sha = (\n',
    '                hashlib.sha256(raw_out.encode("utf-8", errors="replace")).hexdigest()\n',
    '                if raw_out\n',
    '                else ""\n',
    '            )\n',
    '            update_pa: dict[str, Any] = {\n',
    '                "primary_attempt_provider": provider or "",\n',
    '                "primary_attempt_model": selected_mid or "",\n',
    '                "primary_attempt_api_model": api_model or "",\n',
    '                "primary_attempt_api_success": bool(call.success),\n',
    '                "primary_attempt_parser_error_present": bool(runtime_result.parser_error),\n',
    '                "primary_attempt_parser_error": str(runtime_result.parser_error or "")[:400],\n',
    '                "primary_attempt_structured_output_present": runtime_result.parsed_output is not None,\n',
    '                "primary_attempt_raw_output_sha256": raw_sha,\n',
    '                "primary_attempt_raw_output_excerpt": raw_out[:300],\n',
    '            }\n',
    '        else:\n',
    '            generation["error"] = f"adapter_not_registered:{provider}"\n',
    '            generation["metadata"] = {\n',
    '                "adapter_invocation_mode": ADAPTER_INVOCATION_DEGRADED_NO_FALLBACK,\n',
    '                "langchain_prompt_used": False,\n',
    '                "langchain_parser_error": None,\n',
    '                "structured_output": None,\n',
    '                "note": "No adapter registered for routed provider; invoke_model did not call LangChain.",\n',
    '            }\n',
    '            outcome = "error"\n',
]
