"""Model context validation material.

Adds validation, aspect-ledger, actor-lane, and runtime-governance material to model context.
"""
SOURCE_LINES = [
    '            lines.extend(render_prompt_lines("runtime_context.dramatic_irony_rule"))\n',
    '\n',
    '        expectation_variation = (\n',
    '            dramatic_packet.get("expectation_variation")\n',
    '            if isinstance(dramatic_packet.get("expectation_variation"), dict)\n',
    '            else {}\n',
    '        )\n',
    '        expectation_target = (\n',
    '            expectation_variation.get("target")\n',
    '            if isinstance(expectation_variation.get("target"), dict)\n',
    '            else {}\n',
    '        )\n',
    '        selected_variation_ids = (\n',
    '            expectation_target.get("selected_variation_ids")\n',
    '            if isinstance(expectation_target.get("selected_variation_ids"), list)\n',
    '            else []\n',
    '        )\n',
    '        if selected_variation_ids:\n',
    '            lines.append("Expectation Variation Context (bounded, selected only):")\n',
    '            lines.append(\n',
    '                f"- selected_variation_ids: {list(selected_variation_ids)[:3]} "\n',
    '                f"selected_variation_types: {list(expectation_target.get(\'selected_variation_types\') or [])[:3]}"\n',
    '            )\n',
    '            lines.extend(render_prompt_lines("runtime_context.expectation_variation_rule"))\n',
    '\n',
    '        genre_awareness = (\n',
    '            dramatic_packet.get("genre_awareness")\n',
    '            if isinstance(dramatic_packet.get("genre_awareness"), dict)\n',
    '            else {}\n',
    '        )\n',
    '        genre_target = (\n',
    '            genre_awareness.get("target")\n',
    '            if isinstance(genre_awareness.get("target"), dict)\n',
    '            else {}\n',
    '        )\n',
    '        if genre_target.get("genre_profile_id"):\n',
    '            lines.append("Genre Awareness Context (bounded profile, selected only):")\n',
    '            lines.append(\n',
    '                f"- genre_profile_id: {genre_target.get(\'genre_profile_id\')} "\n',
    '                f"selected_registers: {list(genre_target.get(\'selected_registers\') or [])[:3]} "\n',
    '                f"required_conventions: {list(genre_target.get(\'required_conventions\') or [])[:4]}"\n',
    '            )\n',
    '            lines.extend(render_prompt_lines("runtime_context.genre_awareness_rule"))\n',
    '\n',
    '        tonal_consistency = (\n',
    '            dramatic_packet.get("tonal_consistency")\n',
    '            if isinstance(dramatic_packet.get("tonal_consistency"), dict)\n',
    '            else {}\n',
    '        )\n',
    '        tonal_target = (\n',
    '            tonal_consistency.get("target")\n',
    '            if isinstance(tonal_consistency.get("target"), dict)\n',
    '            else {}\n',
    '        )\n',
    '        if tonal_target.get("profile_id"):\n',
    '            lines.append("Tonal Consistency Context (bounded profile, hard live loop):")\n',
    '            lines.append(\n',
    '                f"- profile_id: {tonal_target.get(\'profile_id\')} "\n',
    '                f"required_dimension_ids: {list(tonal_target.get(\'required_dimension_ids\') or [])[:4]} "\n',
    '                f"allowed_registers: {list(tonal_target.get(\'allowed_registers\') or [])[:3]} "\n',
    '                f"live_loop_mode: {tonal_target.get(\'live_loop_mode\')}"\n',
    '            )\n',
    '            lines.extend(render_prompt_lines("runtime_context.tonal_consistency_rule"))\n',
    '\n',
    '        symbolic_object = (\n',
    '            dramatic_packet.get("symbolic_object_resonance")\n',
    '            if isinstance(dramatic_packet.get("symbolic_object_resonance"), dict)\n',
    '            else {}\n',
    '        )\n',
    '        symbolic_target = (\n',
    '            symbolic_object.get("target")\n',
    '            if isinstance(symbolic_object.get("target"), dict)\n',
    '            else {}\n',
    '        )\n',
    '        selected_symbolic_object_ids = (\n',
    '            symbolic_target.get("selected_object_ids")\n',
    '            if isinstance(symbolic_target.get("selected_object_ids"), list)\n',
    '            else []\n',
    '        )\n',
    '        if selected_symbolic_object_ids:\n',
    '            lines.append("Symbolic Object Resonance Context (bounded, selected only):")\n',
    '            lines.append(\n',
    '                f"- selected_object_ids: {list(selected_symbolic_object_ids)[:3]} "\n',
    '                f"selected_resonance_roles: {list(symbolic_target.get(\'selected_resonance_roles\') or [])[:3]}"\n',
    '            )\n',
    '            lines.extend(render_prompt_lines("runtime_context.symbolic_object_resonance_rule"))\n',
    '\n',
    '        if temporal_target:\n',
    '            lines.append("Temporal Control Context (bounded committed refs):")\n',
    '            lines.append(\n',
    '                f"- operation: {temporal_target.get(\'operation\')} "\n',
    '                f"recalled_turn_ids: {list(temporal_target.get(\'recalled_turn_ids\') or [])[:3]} "\n',
    '                f"recalled_consequence_ids: {list(temporal_target.get(\'recalled_consequence_ids\') or [])[:3]}"\n',
    '            )\n',
    '            lines.extend(render_prompt_lines("runtime_context.temporal_control_rule"))\n',
    '\n',
    '        meta_narrative_context = (\n',
    '            (dramatic_packet.get("meta_narrative_awareness") or {}).get("target")\n',
    '            if isinstance(dramatic_packet.get("meta_narrative_awareness"), dict)\n',
    '            else {}\n',
    '        )\n',
    '        if isinstance(meta_narrative_context, dict) and meta_narrative_context:\n',
    '            lines.append("Meta-Narrative Awareness Context (opt-in, bounded):")\n',
    '            lines.append(\n',
    '                "- "\n',
    '                f"tier={str(meta_narrative_context.get(\'awareness_tier\') or \'\')[:40]}, "\n',
    '                f"intensity={str(meta_narrative_context.get(\'intensity\') or \'\')[:40]}, "\n',
    '                f"trigger_frequency={str(meta_narrative_context.get(\'trigger_frequency\') or \'\')[:40]}, "\n',
    '                f"selected_actor_ids={meta_narrative_context.get(\'selected_actor_ids\') or []}"\n',
    '            )\n',
    '            lines.extend(render_prompt_lines("runtime_context.meta_narrative_rule"))\n',
    '\n',
    '        yslice = state.get("goc_yaml_slice") if isinstance(state.get("goc_yaml_slice"), dict) else {}\n',
    '        if state.get("module_id") == GOC_MODULE_ID and yslice:\n',
    '            phase_key = str(scene_assess.get("guidance_phase_key") or "")\n',
    '            phase_arc_key = GUIDANCE_PHASE_TO_ESCALATION_ARC_KEY.get(phase_key, "")\n',
    '            phases = yslice.get("scene_phases") if isinstance(yslice.get("scene_phases"), dict) else {}\n',
    '            phase = phases.get(phase_arc_key) if isinstance(phases.get(phase_arc_key), dict) else {}\n',
    '            if phase:\n',
    '                lines.append("Canonical GoC Phase Law:")\n',
    '                for key in ("name", "description", "active_triggers", "enforced_constraints", "engine_tasks", "exit_condition"):\n',
    '                    val = phase.get(key)\n',
    '                    if val:\n',
    '                        lines.append(f"- {key}: {str(val)[:300]}")\n',
    '            rel_axes = yslice.get("relationship_axes") if isinstance(yslice.get("relationship_axes"), dict) else {}\n',
    '            if rel_axes:\n',
    '                axis_names = []\n',
    '                for axis_id, axis in list(rel_axes.items())[:4]:\n',
    '                    if isinstance(axis, dict):\n',
    '                        axis_names.append(f"{axis_id}:{axis.get(\'name\') or \'\'}")\n',
    '                if axis_names:\n',
    '                    lines.append(f"Canonical Relationship Axes: {\', \'.join(axis_names)}")\n',
    '            escalation_axes = yslice.get("escalation_axes") if isinstance(yslice.get("escalation_axes"), dict) else {}\n',
    '            if escalation_axes:\n',
    '                names = []\n',
    '                for axis_id, axis in list(escalation_axes.items())[:4]:\n',
    '                    if isinstance(axis, dict):\n',
    '                        names.append(f"{axis_id}:{axis.get(\'name\') or \'\'}")\n',
    '                if names:\n',
    '                    lines.append(f"Canonical Escalation Axes: {\', \'.join(names)}")\n',
    '\n',
    '            knowledge_contract = (\n',
    '                state.get("goc_runtime_knowledge_contract")\n',
    '                if isinstance(state.get("goc_runtime_knowledge_contract"), dict)\n',
    '                else {}\n',
    '            )\n',
    '            if knowledge_contract:\n',
    '                lines.extend(\n',
    '                    knowledge_contract_prompt_lines(\n',
    '                        knowledge_contract,\n',
    '                        opening_turn=turn_ic == "opening",\n',
    '                    )\n',
    '                )\n',
    '\n',
    '        lines.extend(render_prompt_lines("runtime_context.dramatic_packet_header"))\n',
    '        lines.append(json.dumps(dramatic_packet, sort_keys=True))\n',
    '        if prompt_authority:\n',
    '            lines.extend(\n',
    '                render_prompt_lines(\n',
    '                    "runtime_context.prompt_authority_block",\n',
    '                    authoritative_sections=list(prompt_authority.get("authoritative_sections") or [])[:10],\n',
    '                    forbidden_inferences=list(prompt_authority.get("forbidden_inferences") or [])[:8],\n',
    '                )\n',
    '            )\n',
    '        try:\n',
    '            generation_directive = render_prompt("runtime_generation_directive").strip()\n',
    '        except KeyError:\n',
    '            generation_directive = ""\n',
    '        if generation_directive:\n',
    '            lines.append(generation_directive)\n',
    '\n',
    '        update = _track(state, node_name="assemble_model_context")\n',
    '        directive = _session_language_directive_for_model(state)\n',
    '        update["model_prompt"] = f"{directive}{prompt}\\n\\n" + "\\n".join(lines)\n',
    '        update["dramatic_generation_packet"] = dramatic_packet\n',
    '        update["broad_nlu_listening"] = broad_nlu_listening\n',
    '        update["conversational_memory"] = conversational_memory\n',
    '        update["prompt_authority"] = prompt_authority\n',
    '        updated_ledger = set_aspect_record(\n',
    '            state.get("turn_aspect_ledger")\n',
]
