"""Generation self-correction.

Builds rewrite instructions and retry state for generations that need playability or validation recovery.
"""
SOURCE_LINES = [
    '            "adapter_invocation_mode": ADAPTER_INVOCATION_DEGRADED_NO_FALLBACK,\n',
    '            "langchain_prompt_used": False,\n',
    '            "note": "fallback_adapter_missing:mock — graph could not run graph-managed raw fallback.",\n',
    '            "configured_fallback_error": configured_fallback_error,\n',
    '        }\n',
    '        update = _track(state, node_name="fallback_model", outcome="error")\n',
    '        update["graph_errors"] = errors\n',
    '        update["generation"] = fallback_generation\n',
    '        return update\n',
    '\n',
    '    def _self_correct_generation(\n',
    '        self,\n',
    '        state: RuntimeTurnState,\n',
    '        generation: dict[str, Any],\n',
    '        current_proposed_effects: list[dict[str, Any]],\n',
    '        feedback_codes: list[str],\n',
    '        attempt_index: int,\n',
    '        preserve_actor_lanes: bool = False,\n',
    '        retry_context_synthesis_bundle: dict[str, Any] | None = None,\n',
    '        retry_context_synthesis_prompt: str = "",\n',
    '    ) -> tuple[dict[str, Any], list[dict[str, Any]], dict[str, Any]]:\n',
    '        routing = state.get("routing") if isinstance(state.get("routing"), dict) else {}\n',
    '        selected_mid = str(routing.get("selected_model") or "").strip()\n',
    '        fallback_mid = str(routing.get("fallback_model") or "").strip()\n',
    '        candidate_mid = selected_mid\n',
    '        current_meta = generation.get("metadata") if isinstance(generation.get("metadata"), dict) else {}\n',
    '        current_failed = generation.get("success") is False or bool(generation.get("error"))\n',
    '        if current_meta.get("adapter") == "mock" and fallback_mid:\n',
    '            candidate_mid = fallback_mid\n',
    '        elif current_failed and fallback_mid:\n',
    '            candidate_mid = fallback_mid\n',
    '        spec = self.registry.get(candidate_mid) if candidate_mid else None\n',
    '        provider = getattr(spec, "provider", "") or ""\n',
    '        adapter = self.adapters.get(provider) if provider else None\n',
    '        if adapter is None:\n',
    '            return (\n',
    '                generation,\n',
    '                list(current_proposed_effects or []),\n',
    '                {"attempt_index": attempt_index, "status": "adapter_missing", "candidate_model": candidate_mid},\n',
    '            )\n',
    '        provider_model = getattr(spec, "provider_model_name", None) if spec is not None else None\n',
    '        allowed_actor_ids: list[str] = []\n',
    '        selected = state.get("selected_responder_set") if isinstance(state.get("selected_responder_set"), list) else []\n',
    '        for row in selected:\n',
    '            if isinstance(row, dict):\n',
    '                actor_id = str(row.get("actor_id") or row.get("responder_id") or "").strip()\n',
    '                if actor_id and actor_id not in allowed_actor_ids:\n',
    '                    allowed_actor_ids.append(actor_id)\n',
    '        retry_prompt = state.get("model_prompt") if isinstance(state.get("model_prompt"), str) else None\n',
    '        if retry_context_synthesis_prompt.strip():\n',
    '            retry_prompt = (\n',
    '                f"{retry_prompt or state.get(\'player_input\') or \'\'}\\n\\n"\n',
    '                f"{retry_context_synthesis_prompt.strip()}"\n',
    '            ).strip()\n',
    '        retry_synthesis_status = ""\n',
    '        if isinstance(retry_context_synthesis_bundle, dict):\n',
    '            retry_synthesis_status = str(retry_context_synthesis_bundle.get("status") or "")\n',
    '        _retry_realize_cap = str(state.get("realize_via_capabilities_used_capability") or "").strip()\n',
    '        _retry_parser_variant = (\n',
    '            "thin"\n',
    '            if _retry_realize_cap.startswith("narrator.")\n',
    '            or _retry_realize_cap.startswith("actor_line.")\n',
    '            else "full"\n',
    '        )\n',
    '        runtime_result = _invoke_runtime_adapter_with_langchain(\n',
    '            adapter=adapter,\n',
    '            player_input=state["player_input"],\n',
    '            interpreted_input=state.get("interpreted_input", {}) if isinstance(state.get("interpreted_input"), dict) else {},\n',
    '            retrieval_context=state.get("context_text"),\n',
    '            timeout_seconds=float(getattr(spec, "timeout_seconds", state.get("selected_timeout", 10.0)) or 10.0),\n',
    '            model_prompt=retry_prompt,\n',
    '            prior_output=str(generation.get("content") or generation.get("model_raw_text") or ""),\n',
    '            feedback_codes=list(feedback_codes),\n',
    '            rewrite_instruction=build_rewrite_instruction(\n',
    '                list(feedback_codes),\n',
    '                allowed_actor_ids=allowed_actor_ids,\n',
    '                preserve_actor_lanes=preserve_actor_lanes,\n',
    '            ),\n',
    '            model_name=str(provider_model).strip() if provider_model else None,\n',
    '            dramatic_generation_packet=state.get("dramatic_generation_packet")\n',
    '            if isinstance(state.get("dramatic_generation_packet"), dict)\n',
    '            else None,\n',
    '            parser_variant=_retry_parser_variant,\n',
    '        )\n',
    '        call = runtime_result.call\n',
    '        prior_raw = str(generation.get("content") or generation.get("model_raw_text") or "").strip()\n',
    '        prior_success = generation.get("success") is True\n',
    '        if not call.success and (prior_success or bool(prior_raw)):\n',
    '            preserved = dict(generation)\n',
    '            preserved_meta = preserved.get("metadata") if isinstance(preserved.get("metadata"), dict) else {}\n',
    '            preserved["metadata"] = {\n',
    '                **preserved_meta,\n',
    '                "langchain_prompt_used": True,\n',
    '                "langchain_parser_error": runtime_result.parser_error,\n',
    '                "adapter_invocation_mode": ADAPTER_INVOCATION_LANGCHAIN_PRIMARY,\n',
    '                "self_correction_attempt_index": attempt_index,\n',
    '                "self_correction_feedback_codes": list(feedback_codes),\n',
    '                "self_correction_candidate_model": candidate_mid,\n',
    '                "self_correction_model_changed": bool(selected_mid)\n',
    '                and bool(candidate_mid)\n',
    '                and candidate_mid != selected_mid,\n',
    '                "context_synthesis_retry_attached": bool(retry_context_synthesis_prompt.strip()),\n',
    '                "context_synthesis_retry_status": retry_synthesis_status,\n',
    '                "dramatic_generation_packet_included": isinstance(\n',
    '                    state.get("dramatic_generation_packet"), dict\n',
    '                ),\n',
    '                "dramatic_generation_packet_scene_function": (\n',
    '                    state.get("dramatic_generation_packet", {}).get("selected_scene_function")\n',
    '                    if isinstance(state.get("dramatic_generation_packet"), dict)\n',
    '                    else None\n',
    '                ),\n',
    '                "dramatic_generation_packet_primary_responder": (\n',
    '                    state.get("dramatic_generation_packet", {}).get("primary_responder_id")\n',
    '                    if isinstance(state.get("dramatic_generation_packet"), dict)\n',
    '                    else None\n',
    '                ),\n',
    '            }\n',
    '            return (\n',
    '                preserved,\n',
    '                list(current_proposed_effects or []),\n',
    '                {\n',
    '                    "attempt_index": attempt_index,\n',
    '                    "candidate_model": candidate_mid,\n',
    '                    "provider": provider,\n',
    '                    "feedback_codes": list(feedback_codes),\n',
    '                    "success": False,\n',
    '                    "parser_error": runtime_result.parser_error,\n',
    '                    "preserve_actor_lanes": bool(preserve_actor_lanes),\n',
    '                    "context_synthesis_retry_attached": bool(retry_context_synthesis_prompt.strip()),\n',
    '                    "context_synthesis_retry_status": retry_synthesis_status,\n',
    '                    "status": "rewrite_failed_kept_prior_generation",\n',
    '                },\n',
    '            )\n',
    '        rewritten = dict(generation)\n',
    '        rewritten["attempted"] = True\n',
    '        rewritten["success"] = call.success\n',
    '        rewritten["error"] = call.metadata.get("error") if not call.success else None\n',
    '        rewritten["model_raw_text"] = call.content\n',
    '        rewritten["content"] = call.content\n',
    '        parsed_structured = runtime_result.parsed_output.model_dump(mode="json") if runtime_result.parsed_output else None\n',
    '        if parsed_structured is None:\n',
    '            raw_content = str(call.content or "").strip()\n',
    '            if raw_content.startswith("{"):\n',
    '                try:\n',
    '                    raw_parsed = json.loads(raw_content)\n',
    '                except Exception:\n',
    '                    raw_parsed = None\n',
    '                if isinstance(raw_parsed, dict) and (\n',
    '                    str(raw_parsed.get("schema_version") or "").strip() == "runtime_actor_turn_v1"\n',
    '                    or any(\n',
    '                        isinstance(raw_parsed.get(key), list)\n',
    '                        for key in ("spoken_lines", "action_lines", "initiative_events", "state_effects")\n',
    '                    )\n',
    '                ):\n',
    '                    parsed_structured = raw_parsed\n',
    '        self_correction_model_changed = bool(selected_mid) and bool(candidate_mid) and candidate_mid != selected_mid\n',
    '        rewritten["fallback_used"] = bool(generation.get("fallback_used"))\n',
    '        rewritten["metadata"] = {\n',
    '            **call.metadata,\n',
    '            "langchain_prompt_used": True,\n',
    '            "langchain_parser_error": runtime_result.parser_error,\n',
    '            "structured_output": parsed_structured,\n',
    '            "adapter_invocation_mode": ADAPTER_INVOCATION_LANGCHAIN_PRIMARY,\n',
    '            "self_correction_attempt_index": attempt_index,\n',
    '            "self_correction_feedback_codes": list(feedback_codes),\n',
    '            "self_correction_candidate_model": candidate_mid,\n',
    '            "self_correction_model_changed": self_correction_model_changed,\n',
    '            "context_synthesis_retry_attached": bool(retry_context_synthesis_prompt.strip()),\n',
    '            "context_synthesis_retry_status": retry_synthesis_status,\n',
    '            "dramatic_generation_packet_included": isinstance(\n',
    '                state.get("dramatic_generation_packet"), dict\n',
    '            ),\n',
    '            "dramatic_generation_packet_scene_function": (\n',
    '                state.get("dramatic_generation_packet", {}).get("selected_scene_function")\n',
    '                if isinstance(state.get("dramatic_generation_packet"), dict)\n',
    '                else None\n',
    '            ),\n',
    '            "dramatic_generation_packet_primary_responder": (\n',
    '                state.get("dramatic_generation_packet", {}).get("primary_responder_id")\n',
    '                if isinstance(state.get("dramatic_generation_packet"), dict)\n',
]
