"""Validation seam delegation.

Runs validation seam delegation, retry feedback construction, validation update copying, and transition toward commit.
"""
SOURCE_LINES = [
    '    def _validate_seam(self, state: RuntimeTurnState) -> RuntimeTurnState:\n',
    '        """``_validate_seam`` — see implementation for behaviour and contracts.\n',
    '        \n',
    '        Behaviour, edge cases, and invariants should be inferred from the implementation and public contract of this symbol.\n',
    '        \n',
    '        Args:\n',
    '            state: ``state`` (RuntimeTurnState); meaning follows the type and call sites.\n',
    '        \n',
    '        Returns:\n',
    '            RuntimeTurnState:\n',
    '                Returns a value of type ``RuntimeTurnState``; see the function body for structure, error paths, and sentinels.\n',
    '        """\n',
    '        update = _track(state, node_name="validate_seam")\n',
    '        generation = apply_structured_hydration(state, dict(state.get("generation") or {}))\n',
    '        proposed = list(state.get("proposed_state_effects") or [])\n',
    '        silence = state.get("silence_brevity_decision") if isinstance(state.get("silence_brevity_decision"), dict) else {}\n',
    '\n',
    '        def _run_validation(\n',
    '            current_generation: dict[str, Any],\n',
    '            current_proposed: list[dict[str, Any]],\n',
    '        ) -> dict[str, Any]:\n',
    '            return run_runtime_validation_seam(\n',
    '                state=state,\n',
    '                generation=current_generation,\n',
    '                proposed_state_effects=current_proposed,\n',
    '                silence_brevity_decision=silence,\n',
    '                actor_lane_validation=_actor_lane_validation,\n',
    '            )\n',
    '\n',
    '        validation_eval = _build_runtime_aspect_validation(\n',
    '            state=state,\n',
    '            generation=generation,\n',
    '            proposed_state_effects=proposed,\n',
    '            outcome=_run_validation(generation, proposed),\n',
    '        )\n',
    '        outcome = validation_eval["outcome"]\n',
    '        turn_number = int(state.get("turn_number") or 0)\n',
    '        max_attempts = max(0, int(self.max_self_correction_attempts))\n',
    '        tonal_target = (\n',
    '            state.get("tonal_consistency_target")\n',
    '            if isinstance(state.get("tonal_consistency_target"), dict)\n',
    '            else {}\n',
    '        )\n',
    '        if (\n',
    '            tonal_target.get("policy_enabled")\n',
    '            and tonal_target.get("live_loop_mode") in {"recover", "reject"}\n',
    '        ):\n',
    '            try:\n',
    '                tonal_max_attempts = int(tonal_target.get("max_repair_attempts"))\n',
    '            except (TypeError, ValueError):\n',
    '                tonal_max_attempts = max_attempts\n',
    '            max_attempts = min(max_attempts, max(0, tonal_max_attempts))\n',
    '        self_correction_attempts: list[dict[str, Any]] = []\n',
    '        context_synthesis_retry_history: list[dict[str, Any]] = []\n',
    '        last_retry_context_synthesis_bundle: dict[str, Any] | None = None\n',
    '        last_validation_feedback: dict[str, Any] | None = None\n',
    '        # Disable degraded commits for opening turns to prevent silent failures on game start\n',
    '        allow_degraded = self.allow_degraded_commit_after_retries and turn_number > 1\n',
    '        retry_loop_exhausted = False\n',
    '        for attempt_index in range(1, max_attempts + 1):\n',
    '            actor_lane_validation = validation_eval["actor_lane_validation"]\n',
    '            decision = decide_playability_recovery(\n',
    '                turn_number=turn_number,\n',
    '                attempt_index=attempt_index,\n',
    '                max_attempts=max_attempts,\n',
    '                outcome=outcome,\n',
    '                generation=generation,\n',
    '                proposed_state_effects=proposed,\n',
    '                allow_degraded_commit_after_retries=bool(allow_degraded),\n',
    '                actor_lane_validation=actor_lane_validation,\n',
    '            )\n',
    '            if not decision.should_retry:\n',
    '                if decision.allow_degraded_commit:\n',
    '                    outcome = degrade_validation_outcome(outcome)\n',
    '                    validation_eval = _build_runtime_aspect_validation(\n',
    '                        state=state,\n',
    '                        generation=generation,\n',
    '                        proposed_state_effects=proposed,\n',
    '                        outcome=outcome,\n',
    '                    )\n',
    '                    outcome = validation_eval["outcome"]\n',
    '                break\n',
    '            validation_feedback = build_validation_retry_feedback(\n',
    '                outcome=outcome,\n',
    '                decision=decision,\n',
    '                actor_lane_validation=actor_lane_validation,\n',
    '                attempt_index=attempt_index,\n',
    '            )\n',
    '            retry_context_synthesis_bundle, retry_context_synthesis_diagnostics, retry_context_synthesis_prompt = (\n',
    '                self._synthesize_context_for_retry(\n',
    '                    state,\n',
    '                    validation_feedback=validation_feedback,\n',
    '                    attempt_index=attempt_index,\n',
    '                )\n',
    '            )\n',
    '            last_retry_context_synthesis_bundle = retry_context_synthesis_bundle\n',
    '            last_validation_feedback = validation_feedback\n',
    '            context_synthesis_retry_history.append(retry_context_synthesis_diagnostics)\n',
    '            generation, proposed, attempt_record = self._self_correct_generation(\n',
    '                state,\n',
    '                generation,\n',
    '                proposed,\n',
    '                decision.feedback_codes,\n',
    '                attempt_index,\n',
    '                preserve_actor_lanes=decision.preserve_actor_lanes,\n',
    '                retry_context_synthesis_bundle=retry_context_synthesis_bundle,\n',
    '                retry_context_synthesis_prompt=retry_context_synthesis_prompt,\n',
    '            )\n',
    '            generation = apply_structured_hydration(state, generation)\n',
    '            validation_eval = _build_runtime_aspect_validation(\n',
    '                state=state,\n',
    '                generation=generation,\n',
    '                proposed_state_effects=proposed,\n',
    '                outcome=_run_validation(generation, proposed),\n',
    '            )\n',
    '            outcome = validation_eval["outcome"]\n',
    '            attempt_record = dict(attempt_record)\n',
    '            attempt_record.update(\n',
    '                build_retry_attempt_record_update(\n',
    '                    validation_feedback=validation_feedback,\n',
    '                    outcome=outcome,\n',
    '                    context_synthesis_retry=retry_context_synthesis_diagnostics,\n',
    '                )\n',
    '            )\n',
    '            self_correction_attempts.append(attempt_record)\n',
    '        else:\n',
    '            retry_loop_exhausted = max_attempts > 0\n',
    '        if retry_loop_exhausted:\n',
    '            actor_lane_validation = validation_eval["actor_lane_validation"]\n',
    '            decision = decide_playability_recovery(\n',
    '                turn_number=turn_number,\n',
    '                attempt_index=max_attempts + 1,\n',
    '                max_attempts=max_attempts,\n',
    '                outcome=outcome,\n',
    '                generation=generation,\n',
    '                proposed_state_effects=proposed,\n',
    '                allow_degraded_commit_after_retries=bool(allow_degraded),\n',
    '                actor_lane_validation=actor_lane_validation,\n',
    '            )\n',
    '            if decision.allow_degraded_commit:\n',
    '                outcome = degrade_validation_outcome(outcome)\n',
    '                validation_eval = _build_runtime_aspect_validation(\n',
    '                    state=state,\n',
    '                    generation=generation,\n',
    '                    proposed_state_effects=proposed,\n',
    '                    outcome=outcome,\n',
    '                )\n',
    '                outcome = validation_eval["outcome"]\n',
    '\n',
    '        reason = str(outcome.get("reason") or "")\n',
    '        generation_meta = generation.get("metadata") if isinstance(generation.get("metadata"), dict) else {}\n',
    '        if turn_number <= 1 and outcome.get("status") == "rejected" and reason == "dramatic_alignment_narrative_too_short":\n',
    '            raw = str(generation.get("content") or generation.get("model_raw_text") or "")\n',
    '            if len(raw.strip()) >= 48 or generation.get("success") is True:\n',
    '                outcome = degrade_validation_outcome(outcome, reason="opening_leniency_approved")\n',
    '                validation_eval = _build_runtime_aspect_validation(\n',
    '                    state=state,\n',
    '                    generation=generation,\n',
    '                    proposed_state_effects=proposed,\n',
    '                    outcome=outcome,\n',
    '                )\n',
    '                outcome = validation_eval["outcome"]\n',
    '\n',
    '        actor_lane_validation = validation_eval["actor_lane_validation"]\n',
    '        authority_ledger = validation_eval["turn_aspect_ledger"]\n',
    '        adr_mode, _ = resolve_validator_dispatch_mode()\n',
    '        if adr_mode is ValidatorDispatchMode.PLAN_ENFORCED and isinstance(authority_ledger, dict):\n',
    '            authority_ledger = dict(authority_ledger)\n',
    '            authority_ledger[ADR0041_RUNTIME_GRAPH_DISPATCH_CONTEXT_KEY] = (\n',
    '                _build_adr0041_runtime_graph_dispatch_bundle(\n',
    '                    state,\n',
    '                    generation,\n',
    '                    proposed,\n',
    '                    outcome,\n',
    '                )\n',
    '            )\n',
    '        update["generation"] = generation\n',
    '        update["proposed_state_effects"] = proposed\n',
    '        update["validation_outcome"] = outcome\n',
    '        update["actor_lane_validation"] = actor_lane_validation\n',
]
