"""Director selection context.

Adds scene assessment, responder scope, capability candidates, and narrative aspect context for director selection.
"""
SOURCE_LINES = [
    '            yaml_slice=yslice,\n',
    '            primary_responder=primary,\n',
    '            module_id=str(state.get("module_id") or ""),\n',
    '            module_runtime_policy=state.get("module_runtime_policy")\n',
    '            if isinstance(state.get("module_runtime_policy"), dict)\n',
    '            else None,\n',
    '        )\n',
    '        mind_models = build_character_mind_records_for_goc(\n',
    '            yaml_slice=yslice,\n',
    '            active_character_keys=active_keys,\n',
    '            current_scene_id=state.get("current_scene_id") or "",\n',
    '            module_id=str(state.get("module_id") or ""),\n',
    '        )\n',
    '        mind_dicts = [m.to_runtime_dict() for m in mind_models]\n',
    '        voice_models = build_character_voice_profiles_for_goc(\n',
    '            yaml_slice=yslice,\n',
    '            active_character_keys=active_keys,\n',
    '            current_scene_id=state.get("current_scene_id") or "",\n',
    '            module_id=str(state.get("module_id") or ""),\n',
    '        )\n',
    '        voice_dicts = [v.to_runtime_dict() for v in voice_models]\n',
    '        actor_lane_ctx = state.get("actor_lane_context") if isinstance(state.get("actor_lane_context"), dict) else {}\n',
    '        forbidden_actor_ids: set[str] = set()\n',
    '        for raw_actor_id in actor_lane_ctx.get("ai_forbidden_actor_ids") or []:\n',
    '            forbidden_actor_ids.update(expand_goc_actor_id_aliases(str(raw_actor_id)))\n',
    '        forbidden_actor_ids.update(expand_goc_actor_id_aliases(str(actor_lane_ctx.get("human_actor_id") or "")))\n',
    '        if forbidden_actor_ids:\n',
    '            filtered_responders: list[dict[str, Any]] = []\n',
    '            for responder in responders:\n',
    '                if not isinstance(responder, dict):\n',
    '                    continue\n',
    '                actor_id = str(responder.get("actor_id") or responder.get("responder_id") or "").strip()\n',
    '                if actor_id and actor_id not in forbidden_actor_ids:\n',
    '                    filtered_responders.append(responder)\n',
    '            if len(filtered_responders) != len(responders):\n',
    '                if not filtered_responders:\n',
    '                    for mind in mind_dicts:\n',
    '                        if not isinstance(mind, dict):\n',
    '                            continue\n',
    '                        actor_id = str(mind.get("runtime_actor_id") or mind.get("character_key") or "").strip()\n',
    '                        if actor_id and actor_id not in forbidden_actor_ids:\n',
    '                            filtered_responders.append(\n',
    '                                {\n',
    '                                    "actor_id": actor_id,\n',
    '                                    "role": "primary_responder",\n',
    '                                    "reason": "actor_lane_human_responder_pruned",\n',
    '                                }\n',
    '                            )\n',
    '                            break\n',
    '                responders = filtered_responders\n',
    '                resolution = dict(resolution) if isinstance(resolution, dict) else {}\n',
    '                resolution["human_actor_responder_pruned"] = True\n',
    '                update["scene_assessment"] = {**base_sa, "multi_pressure_resolution": resolution}\n',
    '                update["selected_responder_set"] = responders\n',
    '        update["character_mind_records"] = mind_dicts\n',
    '        update["character_voice_profiles"] = voice_dicts\n',
    '        sem_fp = ""\n',
    '        soc_fp = ""\n',
    '        if sem_rec:\n',
    '            try:\n',
    '                sem_fp = semantic_move_fingerprint(SemanticMoveRecord.model_validate(sem_rec))\n',
    '            except Exception:\n',
    '                sem_fp = str(sem_rec.get("move_type", ""))[:32]\n',
    '        if soc_rec:\n',
    '            try:\n',
    '                soc_fp = social_state_fingerprint(SocialStateRecord.model_validate(soc_rec))\n',
    '            except Exception:\n',
    '                soc_fp = ""\n',
    '        rationale_codes: list[str] = [\n',
    '            str(resolution.get("selection_source") or "unknown"),\n',
    '            f"scene_fn:{scene_fn}",\n',
    '        ]\n',
    '        if bool(resolution.get("keyword_scene_candidates_used")):\n',
    '            rationale_codes.append("keyword_scene_candidates_used")\n',
    '        if isinstance(sem_rec, dict) and isinstance(sem_rec.get("subtext"), dict):\n',
    '            subtext = sem_rec["subtext"]\n',
    '            subtext_function = str(subtext.get("subtext_function") or "").strip()\n',
    '            if subtext_function:\n',
    '                rationale_codes.append(f"subtext_function:{subtext_function}")\n',
    '            policy_rule_id = str(subtext.get("policy_rule_id") or "").strip()\n',
    '            if policy_rule_id:\n',
    '                rationale_codes.append(f"subtext_policy_rule:{policy_rule_id}")\n',
    '        pik = str(\n',
    '            (\n',
    '                state.get("interpreted_input") if isinstance(state.get("interpreted_input"), dict) else {}\n',
    '            ).get("player_input_kind")\n',
    '            or ""\n',
    '        ).strip()\n',
    '        if pik:\n',
    '            rationale_codes.append(f"player_input_kind:{pik}")\n',
    '        semantic_planner_selection_source = (\n',
    '            "engine_opening_turn"\n',
    '            if engine_opening_turn\n',
    '            else str(resolution.get("selection_source") or "semantic_pipeline_v1")\n',
    '        )\n',
    '        semantic_scene_plan = build_semantic_scene_plan_enrichment(\n',
    '            selected_scene_function=scene_fn,\n',
    '            selected_responder_set=responders,\n',
    '            pacing_mode=pacing,\n',
    '            silence_brevity_decision=silence,\n',
    '            semantic_move_record=sem_rec,\n',
    '            social_state_record=soc_rec,\n',
    '            character_mind_records=mind_dicts,\n',
    '            scene_assessment=update.get("scene_assessment")\n',
    '            if isinstance(update.get("scene_assessment"), dict)\n',
    '            else merged_sa,\n',
    '            implied_continuity_by_function=implied,\n',
    '            prior_continuity_impacts=prior,\n',
    '            prior_planner_truth=state.get("prior_planner_truth")\n',
    '            if isinstance(state.get("prior_planner_truth"), dict)\n',
    '            else None,\n',
    '            selection_source=semantic_planner_selection_source,\n',
    '            current_scene_id=str(state.get("current_scene_id") or ""),\n',
    '            turn_input_class=str(state.get("turn_input_class") or ""),\n',
    '            canonical_path=state.get("canonical_path")\n',
    '            if isinstance(state.get("canonical_path"), dict)\n',
    '            else (yslice.get("canonical_path") if isinstance(yslice, dict) else None),\n',
    '            scene_graph=state.get("scene_graph")\n',
    '            if isinstance(state.get("scene_graph"), dict)\n',
    '            else (yslice.get("scene_graph") if isinstance(yslice, dict) else None),\n',
    '            locations=state.get("locations")\n',
    '            if isinstance(state.get("locations"), dict)\n',
    '            else (yslice.get("locations") if isinstance(yslice, dict) else None),\n',
    '            objects=state.get("objects")\n',
    '            if isinstance(state.get("objects"), dict)\n',
    '            else (yslice.get("objects") if isinstance(yslice, dict) else None),\n',
    '            character_documents=state.get("character_documents")\n',
    '            if isinstance(state.get("character_documents"), dict)\n',
    '            else (yslice.get("character_documents") if isinstance(yslice, dict) else None),\n',
    '            content_access_policy=state.get("content_access_policy")\n',
    '            if isinstance(state.get("content_access_policy"), dict)\n',
    '            else (yslice.get("content_access_policy") if isinstance(yslice, dict) else None),\n',
    '            beat_library=state.get("beat_library")\n',
    '            if isinstance(state.get("beat_library"), dict)\n',
    '            else (yslice.get("beat_library") if isinstance(yslice, dict) else None),\n',
    '            opening_quote_anchors=state.get("opening_quote_anchors")\n',
    '            if isinstance(state.get("opening_quote_anchors"), dict)\n',
    '            else (yslice.get("opening_quote_anchors") if isinstance(yslice, dict) else None),\n',
    '            actor_lane_context=state.get("actor_lane_context")\n',
    '            if isinstance(state.get("actor_lane_context"), dict)\n',
    '            else None,\n',
    '            environment_state=state.get("environment_state")\n',
    '            if isinstance(state.get("environment_state"), dict)\n',
    '            else None,\n',
    '        )\n',
    '        for code in semantic_scene_plan.get("planner_rationale_codes") or []:\n',
    '            text = str(code or "").strip()\n',
    '            if text and text not in rationale_codes:\n',
    '                rationale_codes.append(text)\n',
    '        scene_plan = ScenePlanRecord(\n',
    '            selected_scene_function=scene_fn,\n',
    '            selected_responder_set=list(responders),\n',
    '            pacing_mode=pacing,\n',
    '            silence_brevity_decision=dict(silence),\n',
    '            narrative_scene_function=str(\n',
    '                semantic_scene_plan.get("narrative_scene_function") or ""\n',
    '            ),\n',
    '            realization_mode=str(semantic_scene_plan.get("realization_mode") or ""),\n',
    '            pressure_function=str(semantic_scene_plan.get("pressure_function") or ""),\n',
    '            scene_target=semantic_scene_plan.get("scene_target")\n',
    '            if isinstance(semantic_scene_plan.get("scene_target"), dict)\n',
    '            else {},\n',
    '            pressure_target=semantic_scene_plan.get("pressure_target")\n',
    '            if isinstance(semantic_scene_plan.get("pressure_target"), dict)\n',
    '            else {},\n',
    '            target_obligations=semantic_scene_plan.get("target_obligations")\n',
    '            if isinstance(semantic_scene_plan.get("target_obligations"), list)\n',
    '            else [],\n',
    '            actor_directives=semantic_scene_plan.get("actor_directives")\n',
    '            if isinstance(semantic_scene_plan.get("actor_directives"), list)\n',
    '            else [],\n',
    '            dramatic_beats=semantic_scene_plan.get("dramatic_beats")\n',
    '            if isinstance(semantic_scene_plan.get("dramatic_beats"), list)\n',
    '            else [],\n',
    '            handover_policy=semantic_scene_plan.get("handover_policy")\n',
    '            if isinstance(semantic_scene_plan.get("handover_policy"), dict)\n',
    '            else {},\n',
    '            content_frame=semantic_scene_plan.get("content_frame")\n',
    '            if isinstance(semantic_scene_plan.get("content_frame"), dict)\n',
    '            else {},\n',
]
