"""Action resolution commit.

Completes player-action resolution by applying environment updates, consequence plans, and action-resolution aspect records.
"""
SOURCE_LINES = [
    '                    if isinstance(state.get("actor_lane_context"), dict)\n',
    '                    else {}\n',
    '                )\n',
    '                _pr_c_w5_projection_enabled = w5_ast_director_projection_enabled()\n',
    '                _pr_c_location_resolution = (\n',
    '                    complete_actor_locations_for_gathering_with_optional_w5_projection(\n',
    '                        actor_locations=_pr_c_actor_locations_raw,\n',
    '                        actor_lane_context=_pr_c_alc,\n',
    '                        current_step_scene_id=_pr_c_scene_id,\n',
    '                        selected_human_actor_id=_pr_c_subject_actor_id,\n',
    '                        free_player_action_resolution=free_player_resolution,\n',
    '                        environment_current_room_id=_pr_c_env_current_room_id,\n',
    '                        w5_latest_snapshot=(\n',
    '                            state.get("w5_latest_snapshot")\n',
    '                            if isinstance(state.get("w5_latest_snapshot"), dict)\n',
    '                            else None\n',
    '                        ),\n',
    '                        w5_director_projection_enabled=True,\n',
    '                    )\n',
    '                    if _pr_c_w5_projection_enabled\n',
    '                    else {\n',
    '                        "location_completion": complete_actor_locations_for_gathering(\n',
    '                            actor_locations=_pr_c_actor_locations_raw,\n',
    '                            actor_lane_context=_pr_c_alc,\n',
    '                            current_step_scene_id=_pr_c_scene_id,\n',
    '                            selected_human_actor_id=_pr_c_subject_actor_id,\n',
    '                            free_player_action_resolution=free_player_resolution,\n',
    '                            environment_current_room_id=_pr_c_env_current_room_id,\n',
    '                        ),\n',
    '                        "diagnostics": {},\n',
    '                        "w5_projection": None,\n',
    '                    }\n',
    '                )\n',
    '                _pr_c_location_completion = _pr_c_location_resolution["location_completion"]\n',
    '                _pr_c_w5_director_diagnostics = (\n',
    '                    _pr_c_location_resolution.get("diagnostics")\n',
    '                    if isinstance(_pr_c_location_resolution.get("diagnostics"), dict)\n',
    '                    else {}\n',
    '                )\n',
    '                _pr_c_w5_director_projection = _pr_c_location_resolution.get("w5_projection")\n',
    '                if _pr_c_w5_projection_enabled:\n',
    '                    _w5_diag_payload = dict(_pr_c_w5_director_diagnostics)\n',
    '                    if isinstance(_pr_c_w5_director_projection, dict):\n',
    '                        _w5_diag_payload["w5_director_projection"] = _pr_c_w5_director_projection\n',
    '                    update.setdefault("graph_diagnostics", {}).update(\n',
    '                        {\n',
    '                            "w5_director_projection": _w5_diag_payload,\n',
    '                        }\n',
    '                    )\n',
    '                # --- end actor_locations source resolution ---\n',
    '                # gathering_scene_id is room-level, derived from NPC locations.\n',
    '                # NPCs do not move in Phase 1 → their location IS the gathering\n',
    '                # room.  Using this instead of _pr_c_scene_id ensures that the\n',
    '                # topology comparison in compute_gathering_state has matching\n',
    '                # granularity on both sides (room-level vs room-level).\n',
    '                _pr_c_gathering_scene_id: str | None = (\n',
    '                    _pr_c_location_completion.get("gathering_scene_id")\n',
    '                    or _pr_c_scene_id\n',
    '                )\n',
    '                if _pr_c_location_completion["diagnostic_blocker"]:\n',
    '                    update["director_gathering_state"] = _director_gathering_blocker(\n',
    '                        reason=_pr_c_location_completion["reason"],\n',
    '                        presence_required_for_step=_pr_c_named_chars,\n',
    '                    )\n',
    '                    update.setdefault("graph_diagnostics", {}).update({\n',
    '                        "actor_location_completion": _pr_c_location_completion,\n',
    '                        "current_step_scene_id": _pr_c_scene_id,\n',
    '                        "gathering_scene_id": _pr_c_gathering_scene_id,\n',
    '                        "selected_human_actor_id": _pr_c_subject_actor_id,\n',
    '                    })\n',
    '                    # Skip compute_gathering_state — fail closed on missing scene.\n',
    '                else:\n',
    '                    _pr_c_actor_locations = _pr_c_location_completion["actor_locations"]\n',
    '                    _pr_c_prev_state = (\n',
    '                        state.get("director_gathering_state")\n',
    '                        if isinstance(state.get("director_gathering_state"), dict)\n',
    '                        else state.get("_prior_director_gathering_state")\n',
    '                        if isinstance(state.get("_prior_director_gathering_state"), dict)\n',
    '                        else None\n',
    '                    )\n',
    '                    _pr_c_turn = state.get("turn_number")\n',
    '                    try:\n',
    '                        _pr_c_turn_int = int(_pr_c_turn) if _pr_c_turn is not None else None\n',
    '                    except (TypeError, ValueError):\n',
    '                        _pr_c_turn_int = None\n',
    '                    _pr_c_evidence_required = bool(\n',
    '                        isinstance(presence_evidence, dict)\n',
    '                        or str(free_player_resolution.get("action_commit_policy") or "").strip() == "commit_action"\n',
    '                    )\n',
    '                    director_gathering = compute_gathering_state(\n',
    '                        actor_locations=_pr_c_actor_locations,\n',
    '                        current_step_named_characters=_pr_c_named_chars,\n',
    '                        current_step_scene_id=_pr_c_gathering_scene_id,\n',
    '                        participation_relevance=_pr_c_participation,\n',
    '                        visibility_audibility=_pr_c_visibility,\n',
    '                        subject_actor_id=_pr_c_subject_actor_id,\n',
    '                        participation_evidence_required=_pr_c_evidence_required,\n',
    '                        current_turn_number=_pr_c_turn_int,\n',
    '                        previous_state=_pr_c_prev_state,\n',
    '                    )\n',
    '                    update["director_gathering_state"] = director_gathering\n',
    '                    if not _pr_c_actor_locations:\n',
    '                        update["director_gathering_state"] = _director_gathering_blocker(\n',
    '                            reason=DIAGNOSTIC_BLOCKER_MISSING_ACTOR_LOCATIONS,\n',
    '                            presence_required_for_step=_pr_c_named_chars,\n',
    '                        )\n',
    '                    elif isinstance(presence_evidence, dict) and (\n',
    '                        _pr_c_participation is None or _pr_c_visibility is None\n',
    '                    ):\n',
    '                        update["director_gathering_state"] = _director_gathering_blocker(\n',
    '                            reason=DIAGNOSTIC_BLOCKER_MISSING_PARTICIPATION_EVIDENCE,\n',
    '                            presence_required_for_step=_pr_c_named_chars,\n',
    '                            evidence_status={\n',
    '                                "participation_relevance_present": _pr_c_participation is not None,\n',
    '                                "visibility_audibility_present": _pr_c_visibility is not None,\n',
    '                            },\n',
    '                        )\n',
    '            else:\n',
    '                update["director_gathering_state"] = _director_gathering_blocker(\n',
    '                    reason=DIAGNOSTIC_BLOCKER_MISSING_NAMED_CHARACTERS,\n',
    '                    presence_required_for_step=[],\n',
    '                )\n',
    '        if frame and aff and model:\n',
    '            try:\n',
    '                sam = normalize_scene_affordance_model_for_contracts(model)\n',
    '                local_context_transition = build_local_context_transition(\n',
    '                    player_action_frame=frame,\n',
    '                    affordance_resolution=aff,\n',
    '                    scene_affordance_model=sam,\n',
    '                    current_player_local_context=state.get("player_local_context")\n',
    '                    if isinstance(state.get("player_local_context"), dict)\n',
    '                    else None,\n',
    '                )\n',
    '                narrator_consequence_plan = build_narrator_consequence_plan(\n',
    '                    lang=str(state.get("session_output_language") or "de"),\n',
    '                    player_action_frame=frame,\n',
    '                    affordance_resolution=aff,\n',
    '                    scene_affordance_model=sam,\n',
    '                    local_context_transition=local_context_transition,\n',
    '                )\n',
    '                if local_context_transition:\n',
    '                    update["local_context_transition"] = local_context_transition\n',
    '                if narrator_consequence_plan:\n',
    '                    update["narrator_consequence_plan"] = narrator_consequence_plan\n',
    '            except Exception as exc:\n',
    '                update["action_resolution_consequence_error"] = {\n',
    '                    "error_code": "narrator_consequence_plan_build_failed",\n',
    '                    "error": str(exc)[:240],\n',
    '                }\n',
    '        if interp and frame:\n',
    '            affn = frame.get("affordance_resolution") if isinstance(frame.get("affordance_resolution"), dict) else {}\n',
    '            pol = str(affn.get("action_commit_policy") or "").strip().lower()\n',
    '            merged_interp = {\n',
    '                **interp,\n',
    '                "player_input_kind": frame.get("player_input_kind") or interp.get("player_input_kind"),\n',
    '                "narrator_response_expected": bool(frame.get("narrator_response_expected")),\n',
    '                "npc_response_expected": bool(frame.get("npc_response_expected")),\n',
    '                "player_action_committed": pol == "commit_action",\n',
    '                "player_speech_committed": pol == "commit_speech" or bool(str(frame.get("speech_text") or "").strip()),\n',
    '                "movement_return_intent": bool(interp.get("movement_return_intent")),\n',
    '            }\n',
    '            update["interpreted_input"] = merged_interp\n',
    '            move = state.get("interpreted_move") if isinstance(state.get("interpreted_move"), dict) else {}\n',
    '            update["interpreted_move"] = {\n',
    '                **move,\n',
    '                "player_input_kind": frame.get("player_input_kind") or move.get("player_input_kind"),\n',
    '                "resolved_action_verb": frame.get("verb"),\n',
    '                "resolved_target_type": frame.get("resolved_target_type"),\n',
    '                "resolved_target_id": frame.get("resolved_target_id"),\n',
    '                "affordance_status": frame.get("affordance_status"),\n',
    '                "movement_return_intent": bool(interp.get("movement_return_intent")),\n',
    '            }\n',
    '        final_interp = (\n',
    '            update.get("interpreted_input")\n',
    '            if isinstance(update.get("interpreted_input"), dict)\n',
    '            else interp\n',
    '        )\n',
    '        turn_number = int(state.get("turn_number") or 0)\n',
    '        player_input_kind = str(\n',
    '            frame.get("player_input_kind")\n',
]
