"""NPC agency aspect records.

Builds NPC agency aspect records and related dramatic-quality rejection, recovery, governance, and section helpers.
"""
SOURCE_LINES = [
    '        reasons=error_codes,\n',
    '        source="validator",\n',
    '        failure_class=(\n',
    '            "hard_contract_failure"\n',
    '            if failed and forbidden\n',
    '            else "recoverable_dramatic_failure"\n',
    '            if failed\n',
    '            else None\n',
    '        ),\n',
    '        failure_reason=feedback_code if failed else None,\n',
    '    )\n',
    '\n',
    '\n',
    'def _dramatic_quality_rejection_locked(outcome: dict[str, Any] | None) -> bool:\n',
    '    """True when validation already rejected for dramatic alignment/effect (do not override)."""\n',
    '    if not isinstance(outcome, dict):\n',
    '        return False\n',
    '    if str(outcome.get("status") or "").strip().lower() != "rejected":\n',
    '        return False\n',
    '    reason = str(outcome.get("reason") or "").strip()\n',
    '    return reason.startswith("dramatic_alignment") or reason.startswith("dramatic_effect_")\n',
    '\n',
    '\n',
    'def _build_runtime_aspect_validation(\n',
    '    *,\n',
    '    state: "RuntimeTurnState",\n',
    '    generation: dict[str, Any],\n',
    '    proposed_state_effects: list[dict[str, Any]],\n',
    '    outcome: dict[str, Any],\n',
    ') -> dict[str, Any]:\n',
    '    """Evaluate runtime authority/capability aspects as validation inputs."""\n',
    '    return build_runtime_aspect_validation(\n',
    '        state=state,\n',
    '        generation=generation,\n',
    '        proposed_state_effects=proposed_state_effects,\n',
    '        outcome=outcome,\n',
    '        hooks=RuntimeAspectValidationHooks(\n',
    '            actor_lane_validation=_actor_lane_validation,\n',
    '            build_authority_aspect_records=_build_authority_aspect_records,\n',
    '            dramatic_quality_rejection_locked=_dramatic_quality_rejection_locked,\n',
    '            structured_output_from_generation=_structured_output_from_generation,\n',
    '            runtime_governance_section=_runtime_governance_section,\n',
    '            voice_consistency_validation=_voice_consistency_validation,\n',
    '            voice_aspect_record=_voice_aspect_record,\n',
    '            voice_semantic_failure_present=_voice_semantic_failure_present,\n',
    '            scene_energy_aspect_record=_scene_energy_aspect_record,\n',
    '            pacing_rhythm_aspect_record=_pacing_rhythm_aspect_record,\n',
    '            sensory_context_aspect_record=_sensory_context_aspect_record,\n',
    '            social_pressure_aspect_record=_social_pressure_aspect_record,\n',
    '            information_disclosure_aspect_record=_information_disclosure_aspect_record,\n',
    '            npc_agency_plan_from_state=_npc_agency_plan_from_state,\n',
    '            npc_agency_aspect_record=_npc_agency_aspect_record,\n',
    '        ),\n',
    '    )\n',
    '\n',
    '\n',
    'def _has_usable_narrative_effect(proposed_effects: list[dict[str, Any]]) -> bool:\n',
    '    """Return True when proposed effects already include non-empty narrative prose."""\n',
    '    for effect in proposed_effects:\n',
    '        if not isinstance(effect, dict):\n',
    '            continue\n',
    '        desc = str(effect.get("description") or "").strip()\n',
    '        if not desc:\n',
    '            continue\n',
    '        effect_type = str(effect.get("effect_type") or "").strip().lower()\n',
    '        if effect_type.startswith("narrative") or effect_type in {"opening", "scene", "story"}:\n',
    '            return True\n',
    '    return False\n',
    '\n',
    '\n',
    'def _build_actor_lane_opening_narration(\n',
    '    *,\n',
    '    state: "RuntimeTurnState",\n',
    '    structured_output: dict[str, Any],\n',
    ') -> str:\n',
    '    """Report missing opening narration; do not synthesize substitute story prose."""\n',
    '    return (\n',
    '        "Fallback: opening narration missing after actor-lane generation "\n',
    '        "(error_code=opening_actor_lane_narration_missing). "\n',
    '        "No substitute story text was committed."\n',
    '    )\n',
    '\n',
    '\n',
    'def _runtime_governance_policy_from_state(state: "RuntimeTurnState") -> dict[str, Any]:\n',
    '    policy = state.get("module_runtime_policy") if isinstance(state.get("module_runtime_policy"), dict) else {}\n',
    '    governance = (\n',
    '        policy.get("runtime_governance_policy")\n',
    '        if isinstance(policy.get("runtime_governance_policy"), dict)\n',
    '        else {}\n',
    '    )\n',
    '    return governance if isinstance(governance, dict) else {}\n',
    '\n',
    '\n',
    'def _runtime_governance_section(state: "RuntimeTurnState", section: str) -> dict[str, Any]:\n',
    '    governance = _runtime_governance_policy_from_state(state)\n',
    '    value = governance.get(section)\n',
    '    return value if isinstance(value, dict) else {}\n',
    '\n',
    '\n',
    'def _runtime_governance_hook_enabled(state: "RuntimeTurnState", hook_id: str) -> bool:\n',
    '    continuity = _runtime_governance_section(state, "continuity")\n',
    '    hooks = continuity.get("hooks") if isinstance(continuity.get("hooks"), list) else []\n',
    '    return hook_id in {str(item).strip() for item in hooks if str(item).strip()}\n',
]
