"""NPC agency projection inputs.

Builds W5 NPC projection inputs and NPC agency plan projections for director and model packet use.
"""
SOURCE_LINES = [
    '    npc_actor_ids: list[str],\n',
    '    compact_minds: list[dict[str, Any]],\n',
    ') -> tuple[\n',
    '    dict[str, Any] | None,\n',
    '    dict[str, Any] | None,\n',
    '    dict[str, Any] | None,\n',
    '    list[dict[str, Any]],\n',
    ']:\n',
    '    if not responder_ids and not npc_actor_ids:\n',
    '        return None, None, None, []\n',
    '\n',
    '    character_mind_records = (\n',
    '        state.get("character_mind_records")\n',
    '        if isinstance(state.get("character_mind_records"), list)\n',
    '        else compact_minds\n',
    '    )\n',
    '    interpreted_input = (\n',
    '        state.get("interpreted_input")\n',
    '        if isinstance(state.get("interpreted_input"), dict)\n',
    '        else {}\n',
    '    )\n',
    '    command_name = str(interpreted_input.get("command_name") or "").strip().lower()\n',
    '    navigation_command = (\n',
    '        str(interpreted_input.get("kind") or "").strip().lower() == "explicit_command"\n',
    '        and command_name in {"move", "goto", "go", "scene", "travel", "look", "inspect"}\n',
    '    )\n',
    '    npc_response_expected = (\n',
    '        False\n',
    '        if interpreted_input.get("npc_response_expected") is False or navigation_command\n',
    '        else None\n',
    '    )\n',
    '    npc_w5_situations, npc_w5_diagnostics = _build_w5_npc_projection_inputs(\n',
    '        state=state,\n',
    '        npc_actor_ids=npc_actor_ids or responder_ids,\n',
    '    )\n',
    '    # Phase 6B-3C — F11 W5-first NPC context. Under default-on with at least\n',
    '    # one usable W5 NPC projection, the legacy npc_context_bundle is demoted\n',
    '    # and NOT forwarded to the planner (it stays available as a legacy_compat\n',
    '    # breadcrumb on the resolution envelope). Under explicit opt-out,\n',
    '    # malformed/missing W5, or old payloads, the bundle is forwarded verbatim\n',
    '    # so pre-Phase-6B-3C planner semantics are preserved as a safety net.\n',
    '    npc_context_resolution = resolve_w5_first_npc_context(\n',
    '        npc_context_bundle=state.get("npc_context_bundle"),\n',
    '        npc_w5_projection_diagnostics=npc_w5_diagnostics,\n',
    '    )\n',
    '    effective_npc_context_bundle = npc_context_resolution.get(\n',
    '        "effective_npc_context_bundle"\n',
    '    )\n',
    '    simulation = build_npc_agency_simulation(\n',
    '        selected_responder_set=responders,\n',
    '        turn_number=state.get("turn_number"),\n',
    '        character_mind_records=character_mind_records,\n',
    '        social_state_record=state.get("social_state_record")\n',
    '        if isinstance(state.get("social_state_record"), dict)\n',
    '        else None,\n',
    '        semantic_move_record=state.get("semantic_move_record")\n',
    '        if isinstance(state.get("semantic_move_record"), dict)\n',
    '        else None,\n',
    '        selected_scene_function=str(state.get("selected_scene_function") or "").strip() or None,\n',
    '        prior_planner_truth=state.get("prior_planner_truth")\n',
    '        if isinstance(state.get("prior_planner_truth"), dict)\n',
    '        else None,\n',
    '        actor_lane_context=state.get("actor_lane_context")\n',
    '        if isinstance(state.get("actor_lane_context"), dict)\n',
    '            else None,\n',
    '        preferred_reaction_order_ids=responder_ids,\n',
    '        npc_actor_ids=npc_actor_ids,\n',
    '        npc_response_expected=npc_response_expected,\n',
    '        npc_context_bundle=effective_npc_context_bundle,\n',
    '        npc_w5_situations=npc_w5_situations,\n',
    '    )\n',
    '    plan = (\n',
    '        simulation.get("npc_agency_plan")\n',
    '        if isinstance(simulation, dict) and isinstance(simulation.get("npc_agency_plan"), dict)\n',
    '        else None\n',
    '    )\n',
    '    if not plan and len(responder_ids) >= 2 and npc_response_expected is not False:\n',
    '        plan = build_npc_agency_plan(\n',
    '            selected_responder_set=responders,\n',
    '            turn_number=state.get("turn_number"),\n',
    '            character_mind_records=character_mind_records,\n',
    '            social_state_record=state.get("social_state_record")\n',
    '            if isinstance(state.get("social_state_record"), dict)\n',
    '            else None,\n',
    '            semantic_move_record=state.get("semantic_move_record")\n',
    '            if isinstance(state.get("semantic_move_record"), dict)\n',
    '            else None,\n',
    '            selected_scene_function=str(state.get("selected_scene_function") or "").strip() or None,\n',
    '            prior_planner_truth=state.get("prior_planner_truth")\n',
    '            if isinstance(state.get("prior_planner_truth"), dict)\n',
    '            else None,\n',
    '            actor_lane_context=state.get("actor_lane_context")\n',
    '            if isinstance(state.get("actor_lane_context"), dict)\n',
    '            else None,\n',
    '            preferred_reaction_order_ids=responder_ids,\n',
    '            npc_context_bundle=effective_npc_context_bundle,\n',
    '            npc_w5_situations=npc_w5_situations,\n',
    '        )\n',
    '    if not plan:\n',
    '        return None, None, None, npc_w5_diagnostics\n',
    '    required_actor_ids = list(plan.get("required_actor_ids") or [])\n',
    '    secondary_ids = list(plan.get("secondary_responder_ids") or [])\n',
    '    full_simulation = isinstance(simulation, dict)\n',
    '    long_horizon_state = (\n',
    '        simulation.get("npc_long_horizon_state")\n',
    '        if isinstance(simulation, dict) and isinstance(simulation.get("npc_long_horizon_state"), dict)\n',
    '        else {}\n',
    '    )\n',
    '    private_plans = (\n',
    '        simulation.get("npc_private_plans")\n',
    '        if isinstance(simulation, dict) and isinstance(simulation.get("npc_private_plans"), list)\n',
    '        else []\n',
    '    )\n',
    '    conflict = (\n',
    '        simulation.get("npc_plan_conflict_resolution")\n',
    '        if isinstance(simulation, dict) and isinstance(simulation.get("npc_plan_conflict_resolution"), dict)\n',
    '        else {}\n',
    '    )\n',
    '    selected_private_plan_ids = list(conflict.get("selected_private_plan_ids") or [])\n',
    '    selected_plan_rows = [\n',
    '        row\n',
    '        for row in private_plans\n',
    '        if isinstance(row, dict) and row.get("private_plan_id") in selected_private_plan_ids\n',
    '    ]\n',
    '    directives = {\n',
    '        "contract": "npc_initiative_directives.v1",\n',
    '        "contract_status": NPC_AGENCY_SIMULATION_IMPLEMENTED_STATUS\n',
    '        if full_simulation\n',
    '        else "partial_runtime_projection",\n',
    '        "not_full_multi_agent_simulation": not full_simulation,\n',
    '        "independent_planning_used": full_simulation,\n',
    '        "required_actor_ids": required_actor_ids,\n',
    '        "minimum_secondary_initiatives_required": 1 if secondary_ids else 0,\n',
    '        "long_horizon_state_present": bool(long_horizon_state),\n',
    '        "private_plan_resolution_present": bool(selected_private_plan_ids),\n',
    '        "selected_private_plan_ids": selected_private_plan_ids,\n',
    '        "selected_private_plan_actor_ids": [\n',
    '            row.get("actor_id") for row in selected_plan_rows if row.get("actor_id")\n',
    '        ],\n',
    '        "selected_private_plan_source_intention_thread_ids": [\n',
    '            thread_id\n',
    '            for row in selected_plan_rows\n',
    '            for thread_id in (row.get("source_intention_thread_ids") or [])\n',
    '        ],\n',
    '        "withheld_private_plan_ids": list(conflict.get("withheld_private_plan_ids") or []),\n',
    '        "instruction": (\n',
    '            "Use npc_agency_simulation as the NPC initiative plan. "\n',
    '            "Realize required_actor_ids in spoken_lines or action_lines unless validation constraints prevent it; "\n',
    '            "initiative_events alone do not close required NPC initiative."\n',
    '        ),\n',
    '    }\n',
    '    return plan, directives, simulation, npc_w5_diagnostics\n',
    '\n',
    '\n',
    'def _packet_strings(values: Any, *, limit: int) -> list[str]:\n',
    '    rows = values if isinstance(values, list) else []\n',
    '    out: list[str] = []\n',
    '    for raw in rows:\n',
    '        value = str(raw or "").strip()\n',
    '        if value and value not in out:\n',
    '            out.append(value)\n',
    '        if len(out) >= limit:\n',
    '            break\n',
    '    return out\n',
]
