"""Reaction-order governance.

Computes divergence between preferred director reaction order and realized model output order, then derives responder-order preferences.
"""
SOURCE_LINES = [
    'def _extract_realized_actor_order_from_output(state: dict[str, Any]) -> list[str]:\n',
    '    """Extract unique actor order from realized output (spoken + action lines)."""\n',
    '    spoken = [\n',
    '        str(line.get("speaker_id") or "").strip()\n',
    '        for line in (state.get("spoken_lines") or [])\n',
    '        if isinstance(line, dict) and line.get("speaker_id")\n',
    '    ]\n',
    '    action = [\n',
    '        str(line.get("actor_id") or "").strip()\n',
    '        for line in (state.get("action_lines") or [])\n',
    '        if isinstance(line, dict) and line.get("actor_id")\n',
    '    ]\n',
    '    return list(dict.fromkeys(filter(None, spoken + action)))\n',
    '\n',
    '\n',
    'def _compute_reaction_order_divergence_for_render(state: dict[str, Any]) -> dict[str, Any]:\n',
    '    """Compute canonical reaction order divergence structure from committed responders vs realized output.\n',
    '\n',
    '    Returns dict with complete divergence metadata, structured for render_context and diagnostics.\n',
    '\n',
    '    Returns:\n',
    '        divergence: bool — True if preferred and realized orders differ\n',
    '        reason: str | None — canonical reason code if divergence exists\n',
    '        preferred_reaction_order_ids: list[str] — planned responder order\n',
    '        realized_actor_order: list[str] — actual order in output\n',
    '        not_realized_actor_ids: list[str] — nominated but not realized actors\n',
    '        non_fatal: bool — divergence does not block output (always True)\n',
    '        justified: bool — divergence has explicit reason (True if valid reason)\n',
    '        justification: str | None — human-readable explanation\n',
    '    """\n',
    '    preferred = _preferred_reaction_order_ids_from_responders(\n',
    '        state.get("selected_responder_set") or []\n',
    '    )\n',
    '    secondary = [\n',
    '        r.get("actor_id")\n',
    '        for r in (state.get("selected_responder_set") or [])\n',
    '        if isinstance(r, dict) and r.get("actor_id") and r.get("role") in ("secondary_reactor",)\n',
    '    ]\n',
    '    realized = _extract_realized_actor_order_from_output(state)\n',
    '    not_realized = [a for a in secondary if a not in realized]\n',
    '\n',
    '    reason: str | None = None\n',
    '    justification: str | None = None\n',
    '    if not_realized and realized:\n',
    '        reason = "secondary_responder_nominated_not_realized_in_output"\n',
    '        justification = f"Secondary responders {not_realized} nominated but not realized in output"\n',
    '    elif len(preferred) > 1 and len(realized) == 1:\n',
    '        reason = "single_actor_only"\n',
    '        justification = "Multiple responders nominated; only one actor realized in output"\n',
    '    elif realized and realized != preferred:\n',
    '        reason = "realized_order_differs"\n',
    '        justification = f"Realization order {realized} differs from preferred {preferred}"\n',
    '\n',
    '    divergence = reason is not None\n',
    '    justified = bool(reason)\n',
    '\n',
    '    return {\n',
    '        "reaction_order_divergence": reason,\n',
    '        "divergence": divergence,\n',
    '        "preferred_reaction_order_ids": preferred,\n',
    '        "realized_actor_order": realized,\n',
    '        "not_realized_actor_ids": not_realized,\n',
    '        "non_fatal": True,\n',
    '        "justified": justified,\n',
    '        "justification": justification,\n',
    '    }\n',
    '\n',
    '\n',
    'def _preferred_reaction_order_ids_from_responders(responders: list[Any]) -> list[str]:\n',
    '    scored: list[tuple[int, str]] = []\n',
    '    for row in responders:\n',
    '        if not isinstance(row, dict):\n',
    '            continue\n',
    '        actor_id = str(row.get("actor_id") or row.get("responder_id") or "").strip()\n',
    '        if not actor_id:\n',
    '            continue\n',
    '        try:\n',
    '            seq = int(row.get("preferred_reaction_order"))\n',
    '        except (TypeError, ValueError):\n',
    '            seq = 999\n',
    '        scored.append((seq, actor_id))\n',
    '    scored.sort(key=lambda item: item[0])\n',
    '    ordered: list[str] = []\n',
    '    for _, aid in scored:\n',
    '        if aid not in ordered:\n',
    '            ordered.append(aid)\n',
    '    return ordered\n',
    '\n',
    '\n',
    'def w5_ast_npc_projection_enabled() -> bool:\n',
    '    """W5 NPC-projection flag (default-on as of Phase 6B-1).\n',
    '\n',
    '    Returns True when unset/empty: NPC planning consumes the typed,\n',
    '    actor-specific W5 projection while the legacy NPC context remains\n',
    '    in place as fallback. Explicit opt-out via ``0/false/no/off``\n',
    '    restores pre-Phase-6B-1 legacy-only behavior.\n',
    '    """\n',
    '\n',
    '    raw = (os.environ.get("W5_AST_NPC_PROJECTION_ENABLED") or "").strip().lower()\n',
    '    if raw in {"0", "false", "no", "off"}:\n',
    '        return False\n',
    '    return True\n',
    '\n',
    '\n',
    'def _w5_npc_projection_has_inferred_why(projection_payload: dict[str, Any]) -> bool:\n',
    '    truth = (\n',
    '        projection_payload.get("truth_attribution")\n',
    '        if isinstance(projection_payload.get("truth_attribution"), dict)\n',
    '        else {}\n',
    '    )\n',
    '    return any(\n',
    '        str(path).startswith("why_summary.") and value == "inferred"\n',
    '        for path, value in truth.items()\n',
    '    )\n',
    '\n',
    '\n',
    'def _build_w5_npc_projection_inputs(\n',
    '    *,\n',
    '    state: RuntimeTurnState,\n',
    '    npc_actor_ids: list[str],\n',
    ') -> tuple[dict[str, dict[str, Any]], list[dict[str, Any]]]:\n',
    '    if not w5_ast_npc_projection_enabled():\n',
    '        return {}, []\n',
    '\n',
    '    actor_ids: list[str] = []\n',
    '    for raw_actor_id in npc_actor_ids:\n',
    '        actor_id = str(raw_actor_id or "").strip()\n',
    '        if actor_id and actor_id not in actor_ids:\n',
    '            actor_ids.append(actor_id)\n',
    '    if not actor_ids:\n',
    '        return {}, []\n',
    '\n',
    '    latest_snapshot = state.get("w5_latest_snapshot")\n',
    '    raw_bundle = state.get("npc_context_bundle")\n',
    '    legacy_bundle_present = isinstance(raw_bundle, dict) and bool(raw_bundle)\n',
    '    snapshot_present = isinstance(latest_snapshot, dict) and bool(latest_snapshot)\n',
    '    projections: dict[str, dict[str, Any]] = {}\n',
    '    diagnostics: list[dict[str, Any]] = []\n',
    '    for actor_id in actor_ids:\n',
    '        diagnostic: dict[str, Any] = {\n',
    '            "w5_npc_projection_used": False,\n',
    '            "w5_npc_projection_failed": None,\n',
    '            "w5_snapshot_id": None,\n',
    '            "npc_actor_id": actor_id,\n',
    '            "npc_projection_source": "actor_lane_context",\n',
    '            "npc_projection_has_how": False,\n',
    '            "npc_projection_has_inferred_why": False,\n',
    '        }\n',
    '        try:\n',
    '            if not snapshot_present:\n',
    '                raise ValueError("missing_w5_latest_snapshot")\n',
    '            projection = build_w5_projection_for_npc(\n',
    '                latest_snapshot,\n',
    '                actor_id=actor_id,\n',
    '            )\n',
    '            payload = projection.to_dict()\n',
    '            where_summary = (\n',
    '                payload.get("where_summary")\n',
    '                if isinstance(payload.get("where_summary"), dict)\n',
    '                else {}\n',
    '            )\n',
    '            how_summary = (\n',
    '                payload.get("how_summary")\n',
    '                if isinstance(payload.get("how_summary"), dict)\n',
    '                else {}\n',
    '            )\n',
    '            diagnostic.update(\n',
    '                {\n',
    '                    "w5_npc_projection_used": True,\n',
    '                    "w5_snapshot_id": where_summary.get("w5_snapshot_id"),\n',
    '                    "npc_projection_source": "w5_projection",\n',
    '                    "npc_projection_has_how": bool(\n',
    '                        isinstance(how_summary.get("facts"), dict)\n',
    '                        and how_summary.get("facts")\n',
    '                    ),\n',
    '                    "npc_projection_has_inferred_why": _w5_npc_projection_has_inferred_why(payload),\n',
    '                }\n',
    '            )\n',
    '            projections[actor_id] = payload\n',
    '        except Exception as exc:\n',
    '            text = str(exc).strip()\n',
    '            diagnostic["w5_npc_projection_failed"] = text or type(exc).__name__\n',
    '        diagnostics.append(diagnostic)\n',
    '    # Phase 6B-3C — classify the turn-level NPC context source and back-fill\n',
    '    # the new F11 diagnostics on every per-actor row.\n',
    '    if not snapshot_present:\n',
    '        turn_npc_context_source = "old_payload_legacy"\n',
    '        turn_legacy_visible = False\n',
    '        turn_fallback_reason: str | None = "missing_w5_latest_snapshot"\n',
    '    elif projections:\n',
    '        turn_npc_context_source = "w5_projection"\n',
    '        turn_legacy_visible = legacy_bundle_present\n',
    '        turn_fallback_reason = None\n',
    '    else:\n',
    '        first_failure = next(\n',
    '            (\n',
    '                row.get("w5_npc_projection_failed")\n',
    '                for row in diagnostics\n',
    '                if row.get("w5_npc_projection_failed")\n',
    '            ),\n',
    '            None,\n',
    '        )\n',
    '        turn_npc_context_source = "malformed_w5_fallback"\n',
    '        turn_legacy_visible = False\n',
    '        turn_fallback_reason = first_failure or "malformed_w5_snapshot"\n',
    '    for diagnostic in diagnostics:\n',
    '        diagnostic["npc_context_source"] = turn_npc_context_source\n',
    '        diagnostic["npc_context_legacy_compat_visible"] = turn_legacy_visible\n',
    '        diagnostic["npc_context_fallback_reason"] = turn_fallback_reason\n',
    '    return projections, diagnostics\n',
    '\n',
    '\n',
    'def resolve_w5_first_npc_context(\n',
    '    *,\n',
    '    npc_context_bundle: dict[str, Any] | None,\n',
    '    npc_w5_projection_diagnostics: list[dict[str, Any]] | None,\n',
    '    w5_npc_projection_enabled: bool | None = None,\n',
    ') -> dict[str, Any]:\n',
    '    """Phase 6B-3C — F11 W5-first NPC context resolver.\n',
    '\n',
    '    Classifies the NPC planner\'s actor-situation source for the current\n',
    '    turn and returns the legacy ``npc_context_bundle`` payload (if any)\n',
    '    the planner should consume. Under default-on with at least one usable\n',
    '    W5 NPC projection, the legacy bundle is demoted to a non-authoritative\n',
    '    ``_legacy_compat`` breadcrumb and is **not** fed into the planner\n',
    '    contract; W5 is the primary actor-situation authority. Under explicit\n',
    '    opt-out, malformed/missing W5, or old payloads without a W5 snapshot,\n',
    '    the legacy bundle is forwarded verbatim so pre-Phase-6B-3C planner\n',
    '    semantics are preserved.\n',
    '\n',
    '    Result keys:\n',
    '\n',
    '        npc_context_source: str\n',
    '            One of ``"w5_projection"``, ``"explicit_opt_out_legacy"``,\n',
    '            ``"malformed_w5_fallback"``, ``"old_payload_legacy"``.\n',
    '        effective_npc_context_bundle: dict | None\n',
    '            Bundle to forward to ``build_npc_agency_simulation`` /\n',
    '            ``build_npc_agency_plan``; ``None`` under ``w5_projection``.\n',
    '        legacy_compat_npc_context_bundle: dict | None\n',
    '            The bundle when present and demoted under ``w5_projection``;\n',
    '            audit/observability-only, never consumed by the planner.\n',
    '        npc_context_legacy_compat_visible: bool\n',
    '            ``True`` iff ``legacy_compat_npc_context_bundle`` is set.\n',
    '        npc_context_fallback_reason: str | None\n',
    '            Compact reason on the non-``w5_projection`` paths only.\n',
    '\n',
    '    Privacy / actor-knowledge-scope semantics from Phase 3B are\n',
    '    unaffected — the resolver only chooses which substrate the planner\n',
    '    consumes. The W5 NPC projection contract still enforces per-actor\n',
    '    visibility (target NPC may receive its own private facts; another\n',
    '    actor\'s private/inferred Why is exposed only when\n',
    '    ``actor_knowledge_scope`` allows the target NPC; player-private and\n',
    '    GM/director-only facts never leak to NPC projections). The legacy\n',
    '    bundle, when used, carries only retrieval-lane metadata.\n',
    '\n',
    '    No committed event is mutated. ADR-0033, the Actor Lane, ADR-0061\n',
    '    pause semantics, ADR-0063 W5 semantics, the Canonical Path, and W5\n',
    '    validation semantics are unchanged. How remains first-class.\n',
    '    Inferred Why remains soft truth.\n',
    '    """\n',
    '\n',
    '    enabled = (\n',
    '        w5_ast_npc_projection_enabled()\n',
    '        if w5_npc_projection_enabled is None\n',
    '        else bool(w5_npc_projection_enabled)\n',
    '    )\n',
    '    raw_bundle: dict[str, Any] | None = (\n',
    '        dict(npc_context_bundle)\n',
    '        if isinstance(npc_context_bundle, dict) and npc_context_bundle\n',
    '        else None\n',
    '    )\n',
    '    if not enabled:\n',
    '        return {\n',
    '            "npc_context_source": "explicit_opt_out_legacy",\n',
    '            "effective_npc_context_bundle": raw_bundle,\n',
    '            "legacy_compat_npc_context_bundle": None,\n',
    '            "npc_context_legacy_compat_visible": False,\n',
    '            "npc_context_fallback_reason": "explicit_opt_out",\n',
    '        }\n',
    '    diagnostics = (\n',
    '        list(npc_w5_projection_diagnostics)\n',
    '        if isinstance(npc_w5_projection_diagnostics, list)\n',
    '        else []\n',
    '    )\n',
    '    any_used = any(\n',
    '        isinstance(row, dict) and row.get("w5_npc_projection_used") is True\n',
    '        for row in diagnostics\n',
    '    )\n',
    '    if any_used:\n',
    '        return {\n',
    '            "npc_context_source": "w5_projection",\n',
    '            "effective_npc_context_bundle": None,\n',
    '            "legacy_compat_npc_context_bundle": raw_bundle,\n',
    '            "npc_context_legacy_compat_visible": raw_bundle is not None,\n',
    '            "npc_context_fallback_reason": None,\n',
    '        }\n',
    '    if not diagnostics:\n',
    '        return {\n',
    '            "npc_context_source": "old_payload_legacy",\n',
    '            "effective_npc_context_bundle": raw_bundle,\n',
    '            "legacy_compat_npc_context_bundle": None,\n',
    '            "npc_context_legacy_compat_visible": False,\n',
    '            "npc_context_fallback_reason": "missing_w5_latest_snapshot",\n',
    '        }\n',
    '    first_failure = next(\n',
    '        (\n',
    '            row.get("w5_npc_projection_failed")\n',
    '            for row in diagnostics\n',
    '            if isinstance(row, dict) and row.get("w5_npc_projection_failed")\n',
    '        ),\n',
    '        None,\n',
    '    )\n',
    '    if first_failure == "missing_w5_latest_snapshot":\n',
    '        source = "old_payload_legacy"\n',
    '    else:\n',
    '        source = "malformed_w5_fallback"\n',
    '    return {\n',
    '        "npc_context_source": source,\n',
    '        "effective_npc_context_bundle": raw_bundle,\n',
    '        "legacy_compat_npc_context_bundle": None,\n',
    '        "npc_context_legacy_compat_visible": False,\n',
    '        "npc_context_fallback_reason": first_failure or "malformed_w5_snapshot",\n',
    '    }\n',
    '\n',
    '\n',
    'def _build_npc_agency_plan_projection(\n',
    '    *,\n',
    '    state: RuntimeTurnState,\n',
    '    responders: list[Any],\n',
    '    responder_ids: list[str],\n',
]
