"""Relationship dynamics context.

Normalizes packet strings and compacts relationship-dynamics state for dramatic generation context.
"""
SOURCE_LINES = [
    'def _compact_relationship_dynamics_context(\n',
    '    *,\n',
    '    state: RuntimeTurnState,\n',
    '    npc_agency_simulation: dict[str, Any] | None,\n',
    ') -> dict[str, Any]:\n',
    '    social = state.get("social_state_record") if isinstance(state.get("social_state_record"), dict) else {}\n',
    '    yslice = state.get("goc_yaml_slice") if isinstance(state.get("goc_yaml_slice"), dict) else {}\n',
    '    canonical_axes = yslice.get("relationship_axes") if isinstance(yslice.get("relationship_axes"), dict) else {}\n',
    '    pressure_codes = _packet_strings(social.get("relationship_pressure_codes"), limit=8)\n',
    '    active_axis_ids = _packet_strings(social.get("active_relationship_axis_ids"), limit=4)\n',
    '    dominant_axis_id = str(social.get("dominant_relationship_axis_id") or "").strip() or None\n',
    '    if dominant_axis_id and dominant_axis_id not in active_axis_ids:\n',
    '        active_axis_ids = _packet_strings([dominant_axis_id, *active_axis_ids], limit=4)\n',
    '\n',
    '    relationship_axes: list[dict[str, Any]] = []\n',
    '    for axis_id in active_axis_ids:\n',
    '        axis = canonical_axes.get(axis_id) if isinstance(canonical_axes, dict) else None\n',
    '        if not isinstance(axis, dict):\n',
    '            continue\n',
    '        rel_ids = _packet_strings(axis.get("relationships"), limit=8)\n',
    '        relationship_axes.append(\n',
    '            {\n',
    '                "axis_id": axis_id,\n',
    '                "name": axis.get("name"),\n',
    '                "relationship_count": len(rel_ids),\n',
    '                "relationship_ids": rel_ids,\n',
    '            }\n',
    '        )\n',
    '\n',
    '    simulation = npc_agency_simulation if isinstance(npc_agency_simulation, dict) else {}\n',
    '    graph = simulation.get("npc_interaction_graph") if isinstance(simulation.get("npc_interaction_graph"), dict) else {}\n',
    '    graph_edges = graph.get("edges") if isinstance(graph.get("edges"), list) else []\n',
    '    npc_edges: list[dict[str, Any]] = []\n',
    '    for edge in graph_edges:\n',
    '        if not isinstance(edge, dict):\n',
    '            continue\n',
    '        source_actor_id = str(edge.get("source_actor_id") or "").strip()\n',
    '        target_actor_id = str(edge.get("target_actor_id") or "").strip()\n',
    '        if not source_actor_id or not target_actor_id or source_actor_id == target_actor_id:\n',
    '            continue\n',
    '        npc_edges.append(\n',
    '            {\n',
    '                "source_actor_id": source_actor_id,\n',
    '                "target_actor_id": target_actor_id,\n',
    '                "edge_type": str(edge.get("edge_type") or "initiative_pressure").strip(),\n',
    '            }\n',
    '        )\n',
    '        if len(npc_edges) >= 6:\n',
    '            break\n',
    '\n',
    '    social_state = {\n',
    '        key: social.get(key)\n',
    '        for key in (\n',
    '            "scene_pressure_state",\n',
    '            "social_risk_band",\n',
    '            "responder_asymmetry_code",\n',
    '            "social_continuity_status",\n',
    '        )\n',
    '        if social.get(key) is not None\n',
    '    }\n',
    '    if not (social_state or pressure_codes or relationship_axes or npc_edges):\n',
    '        return {}\n',
    '    return {\n',
    '        "contract": "relationship_dynamics_context.v1",\n',
    '        "relationship_pressure_codes": pressure_codes,\n',
    '        "active_relationship_axis_ids": active_axis_ids,\n',
    '        "dominant_relationship_axis_id": dominant_axis_id,\n',
    '        "relationship_axes": relationship_axes,\n',
    '        "npc_interaction_edges": npc_edges,\n',
    '        "social_state": social_state,\n',
    '        "source_contracts": [\n',
    '            "social_state_record",\n',
    '            "canonical_relationship_axes",\n',
    '            "npc_agency_simulation",\n',
    '        ],\n',
    '        "scope": "bounded_pressure_context_not_durable_relationship_state",\n',
    '    }\n',
]
