"""Source segment for ai_stack.langgraph.langgraph_runtime_executor.

Generated by the DS-010 runtime-executor file split; keep files below 200 lines.
"""
SOURCE_LINES = [
    ') -> None:\n',
    '    if not query_signal.get("attached"):\n',
    '        return\n',
    '    retrieval["continuity_query_signal"] = query_signal\n',
    '    notes = retrieval.get("ranking_notes")\n',
    '    if not isinstance(notes, list):\n',
    '        notes = []\n',
    '        retrieval["ranking_notes"] = notes\n',
    '    if "retrieval_continuity_query=attached" not in notes:\n',
    '        notes.append("retrieval_continuity_query=attached")\n',
    '\n',
    '\n',
    'def _invoke_runtime_adapter_with_langchain(**kwargs: Any) -> Any:\n',
    '    """Load LangChain integration only when a graph node actually invokes an adapter.\n',
    '\n',
    '    Keeping this import lazy lets ``ai_stack.langgraph.langgraph_runtime`` (and test collection)\n',
    '    succeed in slim images or CI slices that ship LangGraph but omit optional\n',
    '    ``langchain_core`` / ``langchain`` extras.\n',
    '    """\n',
    '    from ai_stack.langchain import invoke_runtime_adapter_with_langchain\n',
    '\n',
    '    return invoke_runtime_adapter_with_langchain(**kwargs)\n',
]
