"""Retrieval continuity query context.

Builds the continuity query context for runtime retrieval from player input, scene state, actor keys, and governance metadata.
"""
SOURCE_LINES = [
    '        prior_planner.get("selected_scene_function"),\n',
    '    )\n',
    '    add_line(\n',
    '        "social_outcome_precedents",\n',
    '        "prior_planner_truth",\n',
    '        prior_planner.get("social_outcome"),\n',
    '        prior_planner.get("dramatic_direction"),\n',
    '        prior_planner.get("initiative_summary"),\n',
    '        prior_planner.get("social_pressure_shift"),\n',
    '        prior_planner.get("initiative_seizer_id"),\n',
    '        prior_planner.get("initiative_loser_id"),\n',
    '        prior_planner.get("initiative_pressure_label"),\n',
    '    )\n',
    '    add_line(\n',
    '        "initiative_precedents",\n',
    '        "prior_planner_truth",\n',
    '        prior_planner.get("initiative_seizer_id"),\n',
    '        prior_planner.get("initiative_loser_id"),\n',
    '        prior_planner.get("initiative_pressure_label"),\n',
    '        prior_planner.get("carry_forward_tension_notes"),\n',
    '    )\n',
    '\n',
    '    prior_dramatic = state.get("prior_dramatic_signature")\n',
    '    if not isinstance(prior_dramatic, dict):\n',
    '        prior_dramatic = {}\n',
    '    add_line(\n',
    '        "beat_precedents",\n',
    '        "prior_dramatic_signature",\n',
    '        prior_dramatic.get("prior_beat_id"),\n',
    '        prior_dramatic.get("prior_beat_advancement_reason"),\n',
    '    )\n',
    '    add_line(\n',
    '        "pacing_precedents",\n',
    '        "prior_dramatic_signature",\n',
    '        prior_dramatic.get("prior_pacing_mode"),\n',
    '        prior_planner.get("pacing_mode"),\n',
    '        prior_planner.get("silence_mode"),\n',
    '    )\n',
    '\n',
    '    prior_social = state.get("prior_social_state_record")\n',
    '    if not isinstance(prior_social, dict):\n',
    '        prior_social = {}\n',
    '    add_line(\n',
    '        "continuity_pressure_context",\n',
    '        "committed_continuity_truth",\n',
    '        prior_dramatic.get("prior_pressure_state"),\n',
    '        prior_scene_assessment.get("pressure_state"),\n',
    '        prior_social.get("scene_pressure_state"),\n',
    '        prior_social.get("social_risk_band"),\n',
    '        prior_social.get("responder_asymmetry_code"),\n',
    '        prior_social.get("prior_continuity_classes"),\n',
    '        prior_social_summary.get("social_risk_band"),\n',
    '        prior_social_summary.get("responder_asymmetry_code"),\n',
    '        prior_planner.get("continuity_impacts"),\n',
    '        state.get("prior_continuity_impacts"),\n',
    '        prior_planner.get("carry_forward_tension_notes"),\n',
    '    )\n',
    '\n',
    '    prior_thread = state.get("prior_narrative_thread_state")\n',
    '    if not isinstance(prior_thread, dict):\n',
    '        prior_thread = {}\n',
    '    active_threads = prior_thread.get("active_threads")\n',
    '    thread_pressure_label: str | None = None\n',
    '    try:\n',
    '        thread_pressure_level = int(prior_thread.get("thread_pressure_level") or 0)\n',
    '        if thread_pressure_level >= 3:\n',
    '            thread_pressure_label = "thread_pressure_high"\n',
    '        elif thread_pressure_level > 0:\n',
    '            thread_pressure_label = "thread_pressure_active"\n',
    '    except Exception:\n',
    '        thread_pressure_label = None\n',
    '    thread_actor_values: list[Any] = []\n',
    '    thread_precedent_values: list[Any] = [\n',
    '        prior_thread.get("dominant_thread_kind"),\n',
    '        thread_pressure_label,\n',
    '    ]\n',
    '    if isinstance(active_threads, list):\n',
    '        for thread in active_threads:\n',
    '            if not isinstance(thread, dict):\n',
    '                continue\n',
    '            thread_actor_values.append(thread.get("related_entities"))\n',
    '            thread_precedent_values.extend(\n',
    '                [\n',
    '                    thread.get("thread_kind"),\n',
    '                    thread.get("status"),\n',
    '                    thread.get("resolution_hint"),\n',
    '                ]\n',
    '            )\n',
    '    add_line("actor_precedents", "prior_narrative_thread_state", thread_actor_values)\n',
    '    add_line("narrative_thread_precedents", "prior_narrative_thread_state", thread_precedent_values)\n',
    '    add_line(\n',
    '        "continuity_pressure_context",\n',
    '        "prior_narrative_thread_state",\n',
    '        prior_thread.get("dominant_thread_kind"),\n',
    '        thread_pressure_label,\n',
    '    )\n',
    '\n',
    '    prior_callback = state.get("prior_callback_web_state")\n',
    '    if not isinstance(prior_callback, dict):\n',
    '        prior_callback = {}\n',
    '    callback_edges = (\n',
    '        prior_callback.get("edges") if isinstance(prior_callback.get("edges"), list) else []\n',
    '    )\n',
    '    callback_values: list[Any] = [\n',
    '        prior_callback.get("selected_callback_kind"),\n',
    '        prior_callback.get("selected_continuity_classes"),\n',
    '        prior_callback.get("selected_thread_ids"),\n',
    '    ]\n',
    '    for edge in callback_edges[:4]:\n',
    '        if not isinstance(edge, dict):\n',
    '            continue\n',
    '        callback_values.extend(\n',
    '            [\n',
    '                edge.get("callback_kind"),\n',
    '                edge.get("continuity_classes"),\n',
    '                edge.get("thread_ids"),\n',
    '            ]\n',
    '        )\n',
    '    add_line("narrative_thread_precedents", "prior_callback_web_state", callback_values)\n',
    '    add_line("continuity_pressure_context", "prior_callback_web_state", callback_values)\n',
    '\n',
    '    prior_cascade = state.get("prior_consequence_cascade_state")\n',
    '    if not isinstance(prior_cascade, dict):\n',
    '        prior_cascade = {}\n',
    '    cascade_items = (\n',
    '        prior_cascade.get("items") if isinstance(prior_cascade.get("items"), list) else []\n',
    '    )\n',
    '    cascade_values: list[Any] = [\n',
    '        prior_cascade.get("selected_consequence_ids"),\n',
    '        prior_cascade.get("selected_continuity_classes"),\n',
    '        prior_cascade.get("selected_statuses"),\n',
    '    ]\n',
    '    for item in cascade_items[:5]:\n',
    '        if not isinstance(item, dict):\n',
    '            continue\n',
    '        cascade_values.extend(\n',
    '            [\n',
    '                item.get("consequence_id"),\n',
    '                item.get("continuity_class"),\n',
    '                item.get("status"),\n',
    '                item.get("thread_ids"),\n',
    '            ]\n',
    '        )\n',
    '    add_line("narrative_thread_precedents", "prior_consequence_cascade_state", cascade_values)\n',
    '    add_line("continuity_pressure_context", "prior_consequence_cascade_state", cascade_values)\n',
    '\n',
    '    memory_context = state.get("hierarchical_memory_context")\n',
    '    if isinstance(memory_context, dict):\n',
    '        tiers = memory_context.get("tiers") if isinstance(memory_context.get("tiers"), dict) else {}\n',
    '        memory_values: list[Any] = []\n',
    '        if isinstance(tiers, dict):\n',
    '            for tier_id, rows in tiers.items():\n',
    '                if not isinstance(rows, list):\n',
    '                    continue\n',
    '                for row in rows[:4]:\n',
    '                    if not isinstance(row, dict):\n',
    '                        continue\n',
    '                    memory_values.extend(\n',
    '                        [\n',
    '                            tier_id,\n',
    '                            row.get("summary"),\n',
    '                            row.get("tags"),\n',
    '                            row.get("actor_ids"),\n',
    '                            row.get("location_ids"),\n',
    '                            row.get("capability_ids"),\n',
    '                            row.get("beat_id"),\n',
    '                        ]\n',
    '                    )\n',
    '        add_line("hierarchical_memory_context", "hierarchical_memory", memory_values)\n',
    '\n',
    '    if not lines:\n',
    '        return "", signal\n',
    '    signal["attached"] = True\n',
    '    signal["sources"] = sorted(sources)\n',
    '    return "continuity_retrieval_context:\\n" + "\\n".join(lines), signal\n',
    '\n',
    '\n',
    'def _attach_retrieval_continuity_signal(\n',
    '    retrieval: dict[str, Any],\n',
    '    query_signal: dict[str, Any],\n',
]
