"""Scene energy and pacing aspects.

Builds scene-energy, pacing-rhythm, and sensory-context aspect records from derived narrative state.
"""
SOURCE_LINES = [
    '            ),\n',
    '            "semantic_mixed_signature_count": drift_counts.get(\n',
    '                "mixed_voice_signature", 0\n',
    '            ),\n',
    '            "semantic_ambiguous_signature_count": drift_counts.get(\n',
    '                "ambiguous_voice_signature", 0\n',
    '            ),\n',
    '            "semantic_weak_alignment_count": drift_counts.get(\n',
    '                "weak_profile_alignment", 0\n',
    '            ),\n',
    '        },\n',
    '        reasons=[failure_reason] if failure_reason else [],\n',
    '        source="validator",\n',
    '        failure_class="recoverable_dramatic_failure" if failure_reason else None,\n',
    '        failure_reason=failure_reason,\n',
    '        offending_actor_id=str(first_blocking.get("speaker_id") or first_finding.get("speaker_id") or "").strip() or None,\n',
    '        actual_owner=str(first_blocking.get("actual_source_actor_id") or "").strip() or None,\n',
    '        expected_owner=str(first_blocking.get("expected_profile_actor_id") or "").strip() or None,\n',
    '    )\n',
    '\n',
    '\n',
    'def _voice_semantic_failure_present(result: dict[str, Any]) -> bool:\n',
    '    blocking = result.get("blocking_findings") if isinstance(result.get("blocking_findings"), list) else []\n',
    '    for finding in blocking:\n',
    '        if not isinstance(finding, dict):\n',
    '            continue\n',
    '        if str(finding.get("policy_source") or "") == (\n',
    '            "character_voice.voice_consistency.semantic_classification"\n',
    '        ):\n',
    '            return True\n',
    '    return False\n',
    '\n',
    '\n',
    'def _scene_energy_aspect_record(\n',
    '    *,\n',
    '    target: dict[str, Any] | None,\n',
    '    transition: dict[str, Any] | None,\n',
    '    validation: dict[str, Any] | None = None,\n',
    '    policy: dict[str, Any] | None = None,\n',
    ') -> dict[str, Any]:\n',
    '    target_dict = target if isinstance(target, dict) else {}\n',
    '    transition_dict = transition if isinstance(transition, dict) else {}\n',
    '    validation_dict = validation if isinstance(validation, dict) else {}\n',
    '    failure_codes = [\n',
    '        str(code)\n',
    '        for code in (validation_dict.get("failure_codes") or [])\n',
    '        if str(code).strip()\n',
    '    ]\n',
    '    validation_status = str(validation_dict.get("status") or "").strip().lower()\n',
    '    applicable = bool(target_dict)\n',
    '    if not validation_dict:\n',
    '        aspect_status = "partial" if applicable else "not_applicable"\n',
    '    elif validation_status == "approved":\n',
    '        aspect_status = "passed"\n',
    '    elif validation_status == "not_applicable":\n',
    '        aspect_status = "not_applicable"\n',
    '        applicable = False\n',
    '    else:\n',
    '        aspect_status = "failed"\n',
    '    actual = (\n',
    '        dict(validation_dict.get("actual"))\n',
    '        if isinstance(validation_dict.get("actual"), dict)\n',
    '        else {}\n',
    '    )\n',
    '    actual.update(\n',
    '        {\n',
    '            "validation_status": validation_status or None,\n',
    '            "contract_pass": validation_dict.get("contract_pass"),\n',
    '            "failure_codes": failure_codes,\n',
    '            "transition_allowed": transition_dict.get("allowed"),\n',
    '        }\n',
    '    )\n',
    '    selected = {\n',
    '        "target": target_dict,\n',
    '        "transition": transition_dict,\n',
    '        "energy_level": target_dict.get("energy_level"),\n',
    '        "pressure_vector": target_dict.get("pressure_vector"),\n',
    '        "tempo": target_dict.get("tempo"),\n',
    '        "density": target_dict.get("density"),\n',
    '        "volatility": target_dict.get("volatility"),\n',
    '        "target_transition": target_dict.get("target_transition"),\n',
    '        "minimum_actor_response_count": target_dict.get("minimum_actor_response_count"),\n',
    '    }\n',
    '    return make_aspect_record(\n',
    '        applicable=applicable,\n',
    '        status=aspect_status,\n',
    '        expected={\n',
    '            "schema_version": target_dict.get("schema_version"),\n',
    '            "policy_present": bool(policy),\n',
    '            "policy_enabled": bool((policy or {}).get("enabled")),\n',
    '            "validation_uses_structured_counts": True,\n',
    '        },\n',
    '        selected=selected,\n',
    '        actual=actual,\n',
    '        reasons=failure_codes or (["scene_energy_target_selected"] if target_dict and not validation_dict else []),\n',
    '        source="runtime" if not validation_dict else "validator",\n',
    '        failure_class="recoverable_dramatic_failure" if failure_codes else None,\n',
    '        failure_reason=failure_codes[0] if failure_codes else None,\n',
    '    )\n',
    '\n',
    '\n',
    'def _pacing_rhythm_aspect_record(\n',
    '    *,\n',
    '    state_record: dict[str, Any] | None,\n',
    '    target: dict[str, Any] | None,\n',
    '    validation: dict[str, Any] | None = None,\n',
    '    policy: dict[str, Any] | None = None,\n',
    ') -> dict[str, Any]:\n',
    '    state_dict = state_record if isinstance(state_record, dict) else {}\n',
    '    target_dict = target if isinstance(target, dict) else {}\n',
    '    validation_dict = validation if isinstance(validation, dict) else {}\n',
    '    failure_codes = [\n',
    '        str(code)\n',
    '        for code in (validation_dict.get("failure_codes") or [])\n',
    '        if str(code).strip()\n',
    '    ]\n',
    '    validation_status = str(validation_dict.get("status") or "").strip().lower()\n',
    '    applicable = bool(target_dict)\n',
    '    if not validation_dict:\n',
    '        aspect_status = "partial" if applicable else "not_applicable"\n',
    '    elif validation_status == "approved":\n',
    '        aspect_status = "passed"\n',
    '    elif validation_status == "not_applicable":\n',
    '        aspect_status = "not_applicable"\n',
    '        applicable = False\n',
    '    elif validation_status == "degraded":\n',
    '        aspect_status = "partial"\n',
    '    else:\n',
    '        aspect_status = "failed"\n',
    '    actual = (\n',
    '        dict(validation_dict.get("actual"))\n',
    '        if isinstance(validation_dict.get("actual"), dict)\n',
    '        else {}\n',
    '    )\n',
    '    actual.update(\n',
    '        {\n',
    '            "validation_status": validation_status or None,\n',
    '            "contract_pass": validation_dict.get("contract_pass"),\n',
    '            "failure_codes": failure_codes,\n',
    '        }\n',
    '    )\n',
    '    selected = {\n',
    '        "state": state_dict,\n',
    '        "target": target_dict,\n',
    '        "cadence": target_dict.get("cadence"),\n',
    '        "tempo_arc": target_dict.get("tempo_arc"),\n',
    '        "response_shape": target_dict.get("response_shape"),\n',
    '        "turn_change_policy": target_dict.get("turn_change_policy"),\n',
    '        "min_visible_blocks": target_dict.get("min_visible_blocks"),\n',
    '        "max_visible_blocks": target_dict.get("max_visible_blocks"),\n',
    '        "requires_pause": target_dict.get("requires_pause"),\n',
    '        "blocks_forced_speech": target_dict.get("blocks_forced_speech"),\n',
    '    }\n',
    '    return make_aspect_record(\n',
    '        applicable=applicable,\n',
    '        status=aspect_status,\n',
    '        expected={\n',
    '            "schema_version": target_dict.get("schema_version"),\n',
    '            "policy_present": bool(policy),\n',
    '            "policy_enabled": bool((policy or {}).get("enabled")),\n',
    '            "validation_uses_structured_counts": True,\n',
    '        },\n',
    '        selected=selected,\n',
    '        actual=actual,\n',
    '        reasons=failure_codes or (["pacing_rhythm_target_selected"] if target_dict and not validation_dict else []),\n',
    '        source="runtime" if not validation_dict else "validator",\n',
    '        failure_class="recoverable_dramatic_failure" if failure_codes else None,\n',
    '        failure_reason=failure_codes[0] if failure_codes else None,\n',
    '    )\n',
]
