"""Social pressure aspect records.

Builds social-pressure and information-disclosure aspect records, including pressure labels and disclosure realization checks.
"""
SOURCE_LINES = [
    'def _sensory_context_aspect_record(\n',
    '    *,\n',
    '    state_record: dict[str, Any] | None,\n',
    '    target: dict[str, Any] | None,\n',
    '    validation: dict[str, Any] | None = None,\n',
    '    policy: dict[str, Any] | None = None,\n',
    ') -> dict[str, Any]:\n',
    '    state_dict = state_record if isinstance(state_record, dict) else {}\n',
    '    target_dict = target if isinstance(target, dict) else {}\n',
    '    validation_dict = validation if isinstance(validation, dict) else {}\n',
    '    failure_codes = [\n',
    '        str(code)\n',
    '        for code in (validation_dict.get("failure_codes") or [])\n',
    '        if str(code).strip()\n',
    '    ]\n',
    '    validation_status = str(validation_dict.get("status") or "").strip().lower()\n',
    '    applicable = bool(target_dict)\n',
    '    if not validation_dict:\n',
    '        aspect_status = "partial" if applicable else "not_applicable"\n',
    '    elif validation_status == "approved":\n',
    '        aspect_status = "passed"\n',
    '    elif validation_status == "not_applicable":\n',
    '        aspect_status = "not_applicable"\n',
    '        applicable = False\n',
    '    elif validation_status == "degraded":\n',
    '        aspect_status = "partial"\n',
    '    else:\n',
    '        aspect_status = "failed"\n',
    '    selected_layers = [\n',
    '        row\n',
    '        for row in (target_dict.get("selected_layers") or [])\n',
    '        if isinstance(row, dict)\n',
    '    ]\n',
    '    selected_layer_ids = [\n',
    '        str(row.get("layer_id") or "").strip()\n',
    '        for row in selected_layers\n',
    '        if str(row.get("layer_id") or "").strip()\n',
    '    ]\n',
    '    actual = (\n',
    '        dict(validation_dict.get("actual"))\n',
    '        if isinstance(validation_dict.get("actual"), dict)\n',
    '        else {}\n',
    '    )\n',
    '    actual.update(\n',
    '        {\n',
    '            "validation_status": validation_status or None,\n',
    '            "contract_pass": validation_dict.get("contract_pass"),\n',
    '            "failure_codes": failure_codes,\n',
    '        }\n',
    '    )\n',
    '    selected = {\n',
    '        "state": state_dict,\n',
    '        "target": target_dict,\n',
    '        "intensity": target_dict.get("intensity"),\n',
    '        "location_id": target_dict.get("location_id"),\n',
    '        "object_id": target_dict.get("object_id"),\n',
    '        "mood_key": target_dict.get("mood_key"),\n',
    '        "selected_layer_ids": selected_layer_ids,\n',
    '        "required_layer_ids": target_dict.get("required_layer_ids") or [],\n',
    '        "selected_layers": selected_layers,\n',
    '    }\n',
    '    return make_aspect_record(\n',
    '        applicable=applicable,\n',
    '        status=aspect_status,\n',
    '        expected={\n',
    '            "schema_version": target_dict.get("schema_version"),\n',
    '            "policy_present": bool(policy),\n',
    '            "policy_enabled": bool((policy or {}).get("enabled")),\n',
    '            "require_structured_events": bool(target_dict.get("require_structured_events")),\n',
    '            "min_layers_per_turn": int(target_dict.get("min_layers_per_turn") or 0),\n',
    '            "max_layers_per_turn": int(target_dict.get("max_layers_per_turn") or 0),\n',
    '        },\n',
    '        selected=selected,\n',
    '        actual=actual,\n',
    '        reasons=failure_codes or (["sensory_context_target_selected"] if target_dict and not validation_dict else []),\n',
    '        source="runtime" if not validation_dict else "validator",\n',
    '        failure_class="recoverable_dramatic_failure" if failure_codes else None,\n',
    '        failure_reason=failure_codes[0] if failure_codes else None,\n',
    '    )\n',
    '\n',
    '\n',
    'def _social_pressure_aspect_record(\n',
    '    *,\n',
    '    state_record: dict[str, Any] | None,\n',
    '    target: dict[str, Any] | None,\n',
    '    validation: dict[str, Any] | None = None,\n',
    '    policy: dict[str, Any] | None = None,\n',
    ') -> dict[str, Any]:\n',
    '    state_dict = state_record if isinstance(state_record, dict) else {}\n',
    '    target_dict = target if isinstance(target, dict) else {}\n',
    '    validation_dict = validation if isinstance(validation, dict) else {}\n',
    '    failure_codes = [\n',
    '        str(code)\n',
    '        for code in (validation_dict.get("failure_codes") or [])\n',
    '        if str(code).strip()\n',
    '    ]\n',
    '    validation_status = str(validation_dict.get("status") or "").strip().lower()\n',
    '    applicable = bool(target_dict)\n',
    '    if not validation_dict:\n',
    '        aspect_status = "partial" if applicable else "not_applicable"\n',
    '    elif validation_status == "approved":\n',
    '        aspect_status = "passed"\n',
    '    elif validation_status == "not_applicable":\n',
    '        aspect_status = "not_applicable"\n',
    '        applicable = False\n',
    '    elif validation_status == "degraded":\n',
    '        aspect_status = "partial"\n',
    '    else:\n',
    '        aspect_status = "failed"\n',
    '    actual = (\n',
    '        dict(validation_dict.get("actual"))\n',
    '        if isinstance(validation_dict.get("actual"), dict)\n',
    '        else {}\n',
    '    )\n',
    '    actual.update(\n',
    '        {\n',
    '            "current_score": state_dict.get("current_score") or target_dict.get("target_score"),\n',
    '            "current_band": state_dict.get("current_band") or target_dict.get("target_band"),\n',
    '            "trend": state_dict.get("trend") or target_dict.get("trend"),\n',
    '            "velocity": state_dict.get("velocity"),\n',
    '            "validation_status": validation_status or None,\n',
    '            "contract_pass": validation_dict.get("contract_pass"),\n',
    '            "failure_codes": failure_codes,\n',
    '        }\n',
    '    )\n',
    '    selected = {\n',
    '        "state": state_dict,\n',
    '        "target": target_dict,\n',
    '        "target_score": target_dict.get("target_score"),\n',
    '        "target_band": target_dict.get("target_band"),\n',
    '        "trend": target_dict.get("trend"),\n',
    '        "pressure_floor": target_dict.get("pressure_floor"),\n',
    '        "requires_visible_pressure": target_dict.get("requires_visible_pressure"),\n',
    '        "release_allowed": target_dict.get("release_allowed"),\n',
    '    }\n',
    '    return make_aspect_record(\n',
    '        applicable=applicable,\n',
    '        status=aspect_status,\n',
    '        expected={\n',
    '            "schema_version": target_dict.get("schema_version"),\n',
    '            "policy_present": bool(policy),\n',
    '            "policy_enabled": bool((policy or {}).get("enabled")),\n',
    '            "validation_uses_policy_thresholds": True,\n',
    '        },\n',
    '        selected=selected,\n',
    '        actual=actual,\n',
    '        reasons=failure_codes or (["social_pressure_target_selected"] if target_dict and not validation_dict else []),\n',
    '        source="runtime" if not validation_dict else "validator",\n',
    '        failure_class="recoverable_dramatic_failure" if failure_codes else None,\n',
    '        failure_reason=failure_codes[0] if failure_codes else None,\n',
    '    )\n',
    '\n',
    '\n',
    'def _information_disclosure_aspect_record(\n',
    '    *,\n',
    '    target: dict[str, Any] | None,\n',
    '    validation: dict[str, Any] | None = None,\n',
    '    policy: dict[str, Any] | None = None,\n',
    ') -> dict[str, Any]:\n',
    '    target_dict = target if isinstance(target, dict) else {}\n',
    '    validation_dict = validation if isinstance(validation, dict) else {}\n',
    '    policy_dict = policy if isinstance(policy, dict) else {}\n',
    '    failure_codes = [\n',
    '        str(code)\n',
    '        for code in (validation_dict.get("failure_codes") or [])\n',
    '        if str(code).strip()\n',
    '    ]\n',
    '    validation_status = str(validation_dict.get("status") or "").strip().lower()\n',
    '    policy_present = bool(policy_dict.get("units") or target_dict.get("policy_enabled"))\n',
    '    if not validation_dict:\n',
    '        aspect_status = "partial" if target_dict.get("policy_enabled") else "not_applicable"\n',
    '    elif validation_status == "approved":\n',
    '        aspect_status = "passed"\n',
    '    elif validation_status == "not_applicable":\n',
    '        aspect_status = "not_applicable"\n',
    '    elif validation_status == "degraded":\n',
    '        aspect_status = "partial"\n',
    '    else:\n',
    '        aspect_status = "failed"\n',
    '    actual = (\n',
]
