"""Record field catalog used by the runtime-intelligence projection.

Each entry describes one named source block that is copied from a canonical
aspect record into the projection builder context. Keeping this catalog separate
from extraction code makes the long list auditable without hiding control flow.
"""

from __future__ import annotations

RECORD_FIELD_NAMES: tuple[tuple[str, str, str], ...] = (
    ("input_actual", "input_rec", "actual"),
    ("broad_nlu_expected", "broad_nlu_rec", "expected"),
    ("broad_nlu_selected", "broad_nlu_rec", "selected"),
    ("broad_nlu_actual", "broad_nlu_rec", "actual"),
    ("action_actual", "action_rec", "actual"),
    ("conversational_memory_expected", "conversational_memory_rec", "expected"),
    ("conversational_memory_selected", "conversational_memory_rec", "selected"),
    ("conversational_memory_actual", "conversational_memory_rec", "actual"),
    ("prompt_authority_expected", "prompt_authority_rec", "expected"),
    ("prompt_authority_selected", "prompt_authority_rec", "selected"),
    ("prompt_authority_actual", "prompt_authority_rec", "actual"),
    ("beat_expected", "beat_rec", "expected"),
    ("beat_selected", "beat_rec", "selected"),
    ("beat_actual", "beat_rec", "actual"),
    ("scene_energy_expected", "scene_energy_rec", "expected"),
    ("scene_energy_selected", "scene_energy_rec", "selected"),
    ("scene_energy_actual", "scene_energy_rec", "actual"),
    ("pacing_rhythm_expected", "pacing_rhythm_rec", "expected"),
    ("pacing_rhythm_selected", "pacing_rhythm_rec", "selected"),
    ("pacing_rhythm_actual", "pacing_rhythm_rec", "actual"),
    ("sensory_context_expected", "sensory_context_rec", "expected"),
    ("sensory_context_selected", "sensory_context_rec", "selected"),
    ("sensory_context_actual", "sensory_context_rec", "actual"),
    ("symbolic_object_expected", "symbolic_object_rec", "expected"),
    ("symbolic_object_selected", "symbolic_object_rec", "selected"),
    ("symbolic_object_actual", "symbolic_object_rec", "actual"),
    ("improvisational_expected", "improvisational_rec", "expected"),
    ("improvisational_selected", "improvisational_rec", "selected"),
    ("improvisational_actual", "improvisational_rec", "actual"),
    ("meta_narrative_expected", "meta_narrative_rec", "expected"),
    ("meta_narrative_selected", "meta_narrative_rec", "selected"),
    ("meta_narrative_actual", "meta_narrative_rec", "actual"),
    ("social_pressure_expected", "social_pressure_rec", "expected"),
    ("social_pressure_selected", "social_pressure_rec", "selected"),
    ("social_pressure_actual", "social_pressure_rec", "actual"),
    ("relationship_state_expected", "relationship_state_rec", "expected"),
    ("relationship_state_selected", "relationship_state_rec", "selected"),
    ("relationship_state_actual", "relationship_state_rec", "actual"),
    ("cap_expected", "cap_rec", "expected"),
    ("cap_selected", "cap_rec", "selected"),
    ("cap_actual", "cap_rec", "actual"),
    ("narr_expected", "narr_rec", "expected"),
    ("narr_actual", "narr_rec", "actual"),
    ("npc_expected", "npc_rec", "expected"),
    ("npc_actual", "npc_rec", "actual"),
    ("npc_agency_expected", "npc_agency_rec", "expected"),
    ("npc_agency_selected", "npc_agency_rec", "selected"),
    ("npc_agency_actual", "npc_agency_rec", "actual"),
    ("dramatic_irony_expected", "dramatic_irony_rec", "expected"),
    ("dramatic_irony_selected", "dramatic_irony_rec", "selected"),
    ("dramatic_irony_actual", "dramatic_irony_rec", "actual"),
    ("expectation_variation_expected", "expectation_variation_rec", "expected"),
    ("expectation_variation_selected", "expectation_variation_rec", "selected"),
    ("expectation_variation_actual", "expectation_variation_rec", "actual"),
    ("narrative_momentum_expected", "narrative_momentum_rec", "expected"),
    ("narrative_momentum_selected", "narrative_momentum_rec", "selected"),
    ("narrative_momentum_actual", "narrative_momentum_rec", "actual"),
    ("voice_expected", "voice_rec", "expected"),
    ("voice_actual", "voice_rec", "actual"),
    ("tonal_expected", "tonal_rec", "expected"),
    ("tonal_selected", "tonal_rec", "selected"),
    ("tonal_actual", "tonal_rec", "actual"),
    ("genre_awareness_expected", "genre_awareness_rec", "expected"),
    ("genre_awareness_selected", "genre_awareness_rec", "selected"),
    ("genre_awareness_actual", "genre_awareness_rec", "actual"),
    ("narrative_expected", "narrative_rec", "expected"),
    ("narrative_selected", "narrative_rec", "selected"),
    ("narrative_actual", "narrative_rec", "actual"),
    ("disclosure_expected", "disclosure_rec", "expected"),
    ("disclosure_selected", "disclosure_rec", "selected"),
    ("disclosure_actual", "disclosure_rec", "actual"),
    ("memory_expected", "memory_rec", "expected"),
    ("memory_selected", "memory_rec", "selected"),
    ("memory_actual", "memory_rec", "actual"),
    ("callback_expected", "callback_rec", "expected"),
    ("callback_selected", "callback_rec", "selected"),
    ("callback_actual", "callback_rec", "actual"),
    ("cascade_expected", "cascade_rec", "expected"),
    ("cascade_selected", "cascade_rec", "selected"),
    ("cascade_actual", "cascade_rec", "actual"),
    ("temporal_control_expected", "temporal_control_rec", "expected"),
    ("temporal_control_selected", "temporal_control_rec", "selected"),
    ("temporal_control_actual", "temporal_control_rec", "actual"),
    ("visible_actual", "visible_rec", "actual"),
    ("commit_actual", "commit_rec", "actual"),
)
