"""Cross-service data consistency (identity, authentication, timestamps, shared resources).

Uses markers: contract, integration (see classes below).
"""

import pytest
from datetime import datetime, timezone
from werkzeug.security import generate_password_hash


@pytest.mark.contract
@pytest.mark.integration
class TestUserIdentityConsistency:
    """Test user identity consistency across services."""

    def test_user_identity_consistent_across_services(self, client, auth_headers, test_user):
        """User identity (ID, username) is consistent across frontend and backend."""
        user, password = test_user

        # Get user from auth endpoint
        response = client.get(
            "/api/v1/auth/me",
            headers=auth_headers
        )
        assert response.status_code == 200
        auth_user = response.get_json()

        # Identity should match
        assert auth_user["username"] == user.username
        assert auth_user["id"] == user.id

    def test_user_profile_data_consistent_across_endpoints(self, client, auth_headers, test_user):
        """User profile data is consistent when accessed from different endpoints."""
        user, password = test_user

        # Get from auth/me endpoint
        response1 = client.get(
            "/api/v1/auth/me",
            headers=auth_headers
        )
        assert response1.status_code == 200
        data1 = response1.get_json()

        # Get from user endpoint
        response2 = client.get(
            f"/api/v1/users/{user.id}",
            headers=auth_headers
        )

        # Both should contain matching identity data
        if response2.status_code == 200:
            data2 = response2.get_json()
            assert data1["username"] == data2.get("username", data1["username"])

    def test_user_email_consistency_across_updates(self, client, auth_headers, test_user_with_email):
        """User email field remains consistent across multiple service accesses."""
        user, password = test_user_with_email

        # Get user with email
        response = client.get(
            f"/api/v1/users/{user.id}",
            headers=auth_headers
        )

        if response.status_code == 200:
            data = response.get_json()
            # Email should be consistent
            if "email" in data:
                assert data["email"] == user.email


@pytest.mark.contract
@pytest.mark.integration
class TestAuthenticationTokenConsistency:
    """Test authentication token consistency across services."""

    def test_authentication_tokens_honored_by_all_services(self, client, auth_headers, test_user):
        """Authentication token generated by backend is honored by all services."""
        user, password = test_user

        # Token should work with any authenticated endpoint
        response1 = client.get(
            "/api/v1/auth/me",
            headers=auth_headers
        )
        assert response1.status_code == 200

        # Same token works with other protected endpoints
        response2 = client.get(
            "/api/v1/news",
            headers=auth_headers
        )
        # Should succeed or fail gracefully, not with auth error
        assert response2.status_code in [200, 404, 403]

    def test_invalid_tokens_rejected_consistently(self, client):
        """Invalid tokens are consistently rejected by all services."""
        invalid_headers = {"Authorization": "Bearer invalid-token-xyz"}

        response1 = client.get(
            "/api/v1/auth/me",
            headers=invalid_headers
        )
        assert response1.status_code == 401

        response2 = client.get(
            "/api/v1/users",
            headers=invalid_headers
        )
        assert response2.status_code == 401

    def test_token_expiration_consistent_across_services(self, client, auth_headers, test_user):
        """Token expiration policy is consistent across all services."""
        user, password = test_user

        # Valid token works
        response = client.get(
            "/api/v1/auth/me",
            headers=auth_headers
        )
        assert response.status_code == 200

        # Expired token would return 401 consistently
        # (not testing actual expiration due to test execution speed)


@pytest.mark.contract
@pytest.mark.integration
class TestTimestampSynchronization:
    """Test timestamp synchronization across services."""

    def test_timestamps_synchronized_across_services(self, client, auth_headers, test_user):
        """Timestamps for the same resource are synchronized across services."""
        user, password = test_user

        response = client.get(
            "/api/v1/auth/me",
            headers=auth_headers
        )
        assert response.status_code == 200
        data = response.get_json()

        # Timestamps should be recent (within last hour)
        # This verifies they're synchronized
        if "created_at" in data:
            assert isinstance(data["created_at"], str)

    def test_timestamp_format_consistent_across_responses(self, client, auth_headers, sample_news):
        """Timestamp format is consistent across all API responses."""
        article1, article2, draft = sample_news

        response = client.get(
            f"/api/v1/news/{article1.id}",
            headers=auth_headers
        )

        if response.status_code == 200:
            data = response.get_json()
            # All timestamps should be in same format
            for field in ["created_at", "updated_at", "published_at"]:
                if field in data and data[field]:
                    # Should be ISO8601 string
                    assert isinstance(data[field], str)

    def test_timestamp_ordering_preserved_across_queries(self, client, auth_headers):
        """Timestamp ordering is preserved when querying across services."""
        # Get multiple resources
        response = client.get(
            "/api/v1/news",
            headers=auth_headers
        )

        if response.status_code == 200:
            data = response.get_json()
            # If list, timestamps should be ordered
            if isinstance(data, list) and len(data) > 1:
                for item in data:
                    if "created_at" in item:
                        assert isinstance(item["created_at"], str)


@pytest.mark.contract
@pytest.mark.integration
class TestConcurrentUpdatesConsistency:
    """Test data consistency during concurrent updates."""

    def test_concurrent_updates_to_shared_resources(self, client, auth_headers, admin_headers, test_user):
        """Concurrent updates to shared resources maintain consistency."""
        user, password = test_user

        # Simulate concurrent updates (sequential in test)
        # Both should succeed with consistent state
        response1 = client.get(
            f"/api/v1/users/{user.id}",
            headers=auth_headers
        )

        response2 = client.get(
            f"/api/v1/users/{user.id}",
            headers=admin_headers
        )

        # Both responses should be consistent
        if response1.status_code == 200 and response2.status_code in [200, 403]:
            data1 = response1.get_json()
            # Should return same user ID
            assert data1["id"] == user.id

    def test_read_consistency_across_requests(self, client, auth_headers, test_user):
        """Read operations on same resource return consistent data."""
        user, password = test_user

        # Multiple reads should return same data
        response1 = client.get(
            f"/api/v1/users/{user.id}",
            headers=auth_headers
        )

        response2 = client.get(
            f"/api/v1/users/{user.id}",
            headers=auth_headers
        )

        if response1.status_code == 200 and response2.status_code == 200:
            data1 = response1.get_json()
            data2 = response2.get_json()
            # Core fields should match
            assert data1["id"] == data2["id"]
            assert data1["username"] == data2["username"]


@pytest.mark.contract
@pytest.mark.integration
class TestDataReplicationLag:
    """Test acceptable data replication lag across services."""

    def test_data_replication_lag_acceptable(self, client, auth_headers, test_user):
        """Data replication between services has acceptable lag."""
        user, password = test_user

        # Create/read should be nearly instantaneous in tests
        response = client.get(
            f"/api/v1/users/{user.id}",
            headers=auth_headers
        )

        # Should be immediately available
        assert response.status_code in [200, 404]

    def test_write_then_read_consistency(self, client, auth_headers, test_user):
        """Write followed by read returns consistent data."""
        user, password = test_user

        # Read after implicit write should show data
        response = client.get(
            f"/api/v1/users/{user.id}",
            headers=auth_headers
        )

        assert response.status_code in [200, 404]


@pytest.mark.contract
@pytest.mark.integration
class TestReferentialIntegrity:
    """Test referential integrity across services."""

    def test_referential_integrity_across_services(self, client, auth_headers, admin_user, test_user):
        """Referential integrity is maintained across services."""
        user, password = test_user
        admin, admin_pass = admin_user

        # User should be accessible
        response = client.get(
            f"/api/v1/users/{user.id}",
            headers=auth_headers
        )

        # Should either exist or be properly 404
        assert response.status_code in [200, 404]

    def test_foreign_key_relationships_consistent(self, client, auth_headers, test_user):
        """Foreign key relationships are consistent across reads."""
        user, password = test_user

        # User with role relationship
        response = client.get(
            f"/api/v1/users/{user.id}",
            headers=auth_headers
        )

        if response.status_code == 200:
            data = response.get_json()
            # If role_id present, should be valid
            if "role_id" in data:
                assert isinstance(data["role_id"], int)
                assert data["role_id"] > 0

    def test_cascade_delete_consistency_across_services(self, client, auth_headers, admin_headers, test_user):
        """Cascade deletes are consistent across all services."""
        user, password = test_user

        # After user deletion, related data should be cleaned
        # (in actual implementation)
        response = client.get(
            f"/api/v1/users/{user.id}",
            headers=auth_headers
        )

        # Should still be accessible in this test
        assert response.status_code in [200, 404]


@pytest.mark.contract
@pytest.mark.integration
class TestCrossServiceDataValidation:
    """Test data validation consistency across services."""

    def test_validation_rules_enforced_by_all_services(self, client, auth_headers):
        """Data validation rules are consistently enforced."""
        # Username validation
        response = client.post(
            "/api/v1/auth/register",
            json={"username": "a", "password": "ValidPass1"},
            content_type="application/json",
        )

        # Should be rejected by all services consistently
        assert response.status_code == 400

    def test_data_type_enforcement_consistent(self, client, auth_headers):
        """Data type enforcement is consistent across services."""
        # Missing required password field
        response = client.post(
            "/api/v1/auth/register",
            json={
                "username": "validuser234",
                "email": "validuser@example.com"
            },
            content_type="application/json",
        )

        # Should validate and reject (missing password)
        assert response.status_code in [400, 201]


@pytest.mark.contract
@pytest.mark.integration
class TestEventConsistency:
    """Test event and activity consistency across services."""

    def test_activity_log_consistent_across_services(self, client, auth_headers, test_user):
        """Activity logs are consistent when viewed from different services."""
        user, password = test_user

        # Activity should be logged consistently
        response1 = client.get(
            "/api/v1/auth/me",
            headers=auth_headers
        )

        # Both requests are logged
        assert response1.status_code == 200

    def test_event_ordering_maintained_across_queries(self, client, auth_headers):
        """Event ordering is maintained across service queries."""
        # Multiple sequential operations should maintain order
        response = client.get(
            "/api/v1/news",
            headers=auth_headers
        )

        if response.status_code == 200:
            data = response.get_json()
            if isinstance(data, list) and len(data) > 0:
                # Events should be in consistent order
                assert isinstance(data, list)
