"""MVP4 Diagnostics Envelope, Traceable Decisions, Trace Evidence, and Narrative Gov contracts.

These contracts make a live God of Carnage scene turn observable end-to-end.

Architecture invariants:
- DiagnosticsEnvelope is built from committed state only, never raw AI proposals.
- TraceableDecision records each runtime/AI decision with input/output refs.
- LocalTraceExport is generated by real test execution, never a static fixture.
- NarrativeGovSummary derives operator health from real session diagnostics.
- Secrets are always redacted.
- Human actor never appears as AI-controlled speaker/responder/action-owner.
"""

from __future__ import annotations

import hashlib
import json
import os
import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


# ---------------------------------------------------------------------------
# Secret redaction
# ---------------------------------------------------------------------------

_SENSITIVE_KEY_FRAGMENTS: frozenset[str] = frozenset({
    "secret", "key", "token", "password", "credential", "auth", "api_key",
    "private", "passphrase", "access_token",
})


def _is_sensitive_key(key: str) -> bool:
    k = key.lower()
    return any(frag in k for frag in _SENSITIVE_KEY_FRAGMENTS)


def redact_secrets(data: dict[str, Any]) -> dict[str, Any]:
    """Recursively redact secret-looking values from a dict."""
    result: dict[str, Any] = {}
    for k, v in data.items():
        if _is_sensitive_key(k):
            result[k] = "[REDACTED]"
        elif isinstance(v, dict):
            result[k] = redact_secrets(v)
        elif isinstance(v, list):
            result[k] = [
                redact_secrets(item) if isinstance(item, dict) else item
                for item in v
            ]
        else:
            result[k] = v
    return result


def _hash_text(text: str) -> str:
    return f"sha256:{hashlib.sha256(text.encode()).hexdigest()[:16]}"


# ---------------------------------------------------------------------------
# DegradationEvent
# ---------------------------------------------------------------------------

@dataclass
class DegradationEvent:
    marker: str
    severity: str
    timestamp: str
    recovery_successful: bool
    recovery_latency_ms: int | None = None
    context_snapshot: dict = field(default_factory=dict)
    span_ids: list[str] = field(default_factory=list)

    def to_dict(self) -> dict:
        return {
            "marker": self.marker,
            "severity": self.severity,
            "timestamp": self.timestamp,
            "recovery_successful": self.recovery_successful,
            "recovery_latency_ms": self.recovery_latency_ms,
            "context_snapshot": self.context_snapshot,
            "span_ids": self.span_ids,
        }


# ---------------------------------------------------------------------------
# TraceableDecision
# ---------------------------------------------------------------------------

@dataclass
class TraceableDecision:
    decision_id: str
    decision_type: str
    story_session_id: str
    turn_number: int
    status: str  # "accepted" | "rejected" | "degraded"
    trace_span_name: str
    input_refs: list[str] = field(default_factory=list)
    selected_output_ref: str = ""
    rejected_reasons: list[str] = field(default_factory=list)
    run_id: str = ""
    contract: str = "traceable_decision.v1"

    def to_dict(self) -> dict[str, Any]:
        return {
            "contract": self.contract,
            "decision_id": self.decision_id,
            "decision_type": self.decision_type,
            "story_session_id": self.story_session_id,
            "run_id": self.run_id,
            "turn_number": self.turn_number,
            "input_refs": list(self.input_refs),
            "selected_output_ref": self.selected_output_ref,
            "status": self.status,
            "rejected_reasons": list(self.rejected_reasons),
            "trace_span_name": self.trace_span_name,
        }


def _make_decision_id(session_id: str, turn: int, decision_type: str) -> str:
    short = hashlib.sha256(f"{session_id}:{turn}:{decision_type}".encode()).hexdigest()[:8]
    return f"dec_t{turn}_{decision_type[:20]}_{short}"


# ---------------------------------------------------------------------------
# DiagnosticsEnvelope
# ---------------------------------------------------------------------------

@dataclass
class DiagnosticsEnvelope:
    contract: str = "diagnostics_envelope.v1"
    trace_id: str = ""
    story_session_id: str = ""
    run_id: str = ""
    turn_number: int = 0
    content_module_id: str = ""
    runtime_profile_id: str = ""
    runtime_module_id: str = ""
    selected_player_role: str = ""
    human_actor_id: str = ""
    npc_actor_ids: list[str] = field(default_factory=list)
    ai_allowed_actor_ids: list[str] = field(default_factory=list)
    ai_forbidden_actor_ids: list[str] = field(default_factory=list)
    player_input_hash: str = ""
    player_input_length: int = 0
    ai_provider: str = ""
    ai_model: str = ""
    adapter_used: str = ""
    fallback_stage: str = ""
    structured_output_present: bool = False
    actor_lane_validation_status: str = ""
    actor_lane_validation_reason: str = ""
    primary_responder_id: str = ""
    secondary_responder_ids: list[str] = field(default_factory=list)
    dramatic_validation_status: str = ""
    dramatic_validation_reason: str = ""
    accepted_delta_count: int = 0
    rejected_delta_count: int = 0
    commit_applied: bool = False
    response_packaged_from_committed_state: bool = True
    quality_class: str = ""
    degradation_signals: list[str] = field(default_factory=list)
    langfuse_status: str = "disabled"
    langfuse_trace_id: str = ""
    traceable_decisions: list[TraceableDecision] = field(default_factory=list)
    live_dramatic_scene_simulator: dict[str, Any] = field(default_factory=dict)
    npc_agency: dict[str, Any] = field(default_factory=dict)
    frontend_render_contract: dict[str, Any] = field(default_factory=dict)
    quality: dict[str, Any] = field(default_factory=dict)
    degradation_timeline: list[DegradationEvent] = field(default_factory=list)
    cost_summary: dict[str, Any] = field(default_factory=lambda: {
        "input_tokens": 0, "output_tokens": 0, "cost_usd": 0.0
    })
    debug_payload: dict[str, Any] | None = None

    def to_dict(self) -> dict[str, Any]:
        return {
            "contract": self.contract,
            "trace_id": self.trace_id,
            "story_session_id": self.story_session_id,
            "run_id": self.run_id,
            "turn_number": self.turn_number,
            "content_module_id": self.content_module_id,
            "runtime_profile_id": self.runtime_profile_id,
            "runtime_module_id": self.runtime_module_id,
            "selected_player_role": self.selected_player_role,
            "human_actor_id": self.human_actor_id,
            "npc_actor_ids": list(self.npc_actor_ids),
            "ai_allowed_actor_ids": list(self.ai_allowed_actor_ids),
            "ai_forbidden_actor_ids": list(self.ai_forbidden_actor_ids),
            "player_input_hash": self.player_input_hash,
            "player_input_length": self.player_input_length,
            "ai_provider": self.ai_provider,
            "ai_model": self.ai_model,
            "adapter_used": self.adapter_used,
            "fallback_stage": self.fallback_stage,
            "structured_output_present": self.structured_output_present,
            "actor_lane_validation_status": self.actor_lane_validation_status,
            "actor_lane_validation_reason": self.actor_lane_validation_reason,
            "primary_responder_id": self.primary_responder_id,
            "secondary_responder_ids": list(self.secondary_responder_ids),
            "dramatic_validation_status": self.dramatic_validation_status,
            "dramatic_validation_reason": self.dramatic_validation_reason,
            "accepted_delta_count": self.accepted_delta_count,
            "rejected_delta_count": self.rejected_delta_count,
            "commit_applied": self.commit_applied,
            "response_packaged_from_committed_state": self.response_packaged_from_committed_state,
            "quality_class": self.quality_class,
            "degradation_signals": list(self.degradation_signals),
            "langfuse_status": self.langfuse_status,
            "langfuse_trace_id": self.langfuse_trace_id,
            "traceable_decisions": [d.to_dict() for d in self.traceable_decisions],
            "live_dramatic_scene_simulator": dict(self.live_dramatic_scene_simulator),
            "npc_agency": dict(self.npc_agency),
            "frontend_render_contract": dict(self.frontend_render_contract),
            "quality": dict(self.quality),
            "degradation_timeline": [e.to_dict() for e in self.degradation_timeline],
            "cost_summary": dict(self.cost_summary),
            "debug_payload": self.debug_payload,
        }

    def to_response(self, context: str = "operator") -> dict[str, Any]:
        """Build response dict based on consumer context.

        context="operator"    → tiered visibility (hashes + costs redacted)
        context="langfuse"    → full technical data (debug_payload excluded)
        context="super_admin" → everything unredacted
        """
        base = self.to_dict()
        if context == "super_admin":
            return base
        # debug_payload NIEMALS in Langfuse oder Operator
        base.pop("debug_payload", None)
        if context == "langfuse":
            return base
        # Operator: hashes und costs redacten
        if "live_dramatic_scene_simulator" in base:
            base["live_dramatic_scene_simulator"]["input_hash"] = "[REDACTED]"
            base["live_dramatic_scene_simulator"]["output_hash"] = "[REDACTED]"
        base["player_input_hash"] = "[REDACTED]"
        base["cost_summary"] = "[REDACTED]"
        # degradation_timeline: span_ids redacten
        for event in base.get("degradation_timeline", []):
            event["span_ids"] = "[REDACTED]"
        return base

    def validate_evidence_consistency(self) -> tuple[bool, str | None]:
        """Check that the envelope has non-placeholder evidence.

        Returns (ok, error_code_or_None).
        """
        if not self.story_session_id:
            return False, "diagnostics_missing_evidence"
        ldss = self.live_dramatic_scene_simulator
        if ldss.get("status") != "evidenced_live_path":
            return False, "diagnostics_missing_ldss_proof"
        if ldss.get("decision_count", 0) <= 0:
            return False, "diagnostics_missing_evidence"
        # scene_block_count lives in frontend_render_contract
        fc = self.frontend_render_contract
        if fc.get("scene_block_count", 0) <= 0:
            return False, "diagnostics_missing_evidence"
        return True, None


# ---------------------------------------------------------------------------
# LocalTraceExport / LangfuseRealTraceEvidence
# ---------------------------------------------------------------------------

@dataclass
class LocalTraceExport:
    """A trace export generated by real test execution — not a static fixture."""
    contract: str = "langfuse_real_trace_evidence.v1"
    evidence_type: str = "local_trace_export"
    generated_by_test: str = ""
    source_test_run_id: str = ""
    generated_at: str = ""
    story_session_id: str = ""
    run_id: str = ""
    turn_number: int = 0
    trace_id: str = ""
    export_path: str = ""
    metadata_match: bool = True
    static_fixture: bool = False
    same_test_run_as_live_response: bool = True
    required_spans_present: list[str] = field(default_factory=list)
    langfuse_status: str = "disabled"

    def to_dict(self) -> dict[str, Any]:
        return {
            "contract": self.contract,
            "evidence_type": self.evidence_type,
            "generated_by_test": self.generated_by_test,
            "source_test_run_id": self.source_test_run_id,
            "generated_at": self.generated_at,
            "story_session_id": self.story_session_id,
            "run_id": self.run_id,
            "turn_number": self.turn_number,
            "trace_id": self.trace_id,
            "export_path": self.export_path,
            "metadata_match": self.metadata_match,
            "static_fixture": self.static_fixture,
            "same_test_run_as_live_response": self.same_test_run_as_live_response,
            "required_spans_present": list(self.required_spans_present),
            "langfuse_status": self.langfuse_status,
        }

    def validate_not_static_fixture(self) -> tuple[bool, str | None]:
        if self.static_fixture:
            return False, "langfuse_mock_only_trace_not_final"
        if not self.same_test_run_as_live_response:
            return False, "trace_export_not_from_current_test_run"
        if not self.trace_id or not self.story_session_id:
            return False, "trace_metadata_mismatch"
        return True, None


# ---------------------------------------------------------------------------
# NarrativeGovSummary
# ---------------------------------------------------------------------------

@dataclass
class NarrativeGovSummary:
    content_module_id: str = "god_of_carnage"
    runtime_profile_id: str = "god_of_carnage_solo"
    runtime_module_id: str = "solo_story_runtime"
    last_trace_id: str = ""
    last_story_session_id: str = ""
    last_turn_number: int = 0
    content_module_health: dict[str, Any] = field(default_factory=dict)
    runtime_profile_health: dict[str, Any] = field(default_factory=dict)
    runtime_module_health: dict[str, Any] = field(default_factory=dict)
    ldss_health: dict[str, Any] = field(default_factory=dict)
    frontend_render_contract_health: dict[str, Any] = field(default_factory=dict)
    actor_lane_health: dict[str, Any] = field(default_factory=dict)
    degradation_health: dict[str, Any] = field(default_factory=dict)
    contract: str = "narrative_gov_summary.v1"

    def to_dict(self) -> dict[str, Any]:
        return {
            "contract": self.contract,
            "content_module_id": self.content_module_id,
            "runtime_profile_id": self.runtime_profile_id,
            "runtime_module_id": self.runtime_module_id,
            "last_trace_id": self.last_trace_id,
            "last_story_session_id": self.last_story_session_id,
            "last_turn_number": self.last_turn_number,
            "content_module_health": dict(self.content_module_health),
            "runtime_profile_health": dict(self.runtime_profile_health),
            "runtime_module_health": dict(self.runtime_module_health),
            "ldss_health": dict(self.ldss_health),
            "frontend_render_contract_health": dict(self.frontend_render_contract_health),
            "actor_lane_health": dict(self.actor_lane_health),
            "degradation_health": dict(self.degradation_health),
        }


# ---------------------------------------------------------------------------
# Builder functions
# ---------------------------------------------------------------------------

def build_traceable_decisions(
    *,
    session_id: str,
    turn_number: int,
    actor_lane_status: str,
    actor_lane_reason: str,
    dramatic_status: str,
    dramatic_reason: str,
    commit_applied: bool,
    primary_responder_id: str,
    human_actor_id: str,
) -> list[TraceableDecision]:
    """Build per-decision trace records for a turn."""
    decisions: list[TraceableDecision] = []

    # Responder plan decision
    decisions.append(TraceableDecision(
        decision_id=_make_decision_id(session_id, turn_number, "responder_plan"),
        decision_type="npc_responder_plan",
        story_session_id=session_id,
        turn_number=turn_number,
        status="accepted" if primary_responder_id else "degraded",
        trace_span_name="live_dramatic_scene_simulator.responder_plan",
        input_refs=["actor_lane_context.v1", "story_session_state.v1"],
        selected_output_ref=(
            f"npc_agency_plan.v1#primary_responder_{primary_responder_id}"
            if primary_responder_id else ""
        ),
        rejected_reasons=[] if primary_responder_id else ["no_primary_responder_available"],
    ))

    # Actor lane validation decision
    decisions.append(TraceableDecision(
        decision_id=_make_decision_id(session_id, turn_number, "actor_lane_validation"),
        decision_type="actor_lane_validation",
        story_session_id=session_id,
        turn_number=turn_number,
        status=actor_lane_status if actor_lane_status in ("approved", "rejected") else "approved",
        trace_span_name="actor_lane_validation",
        input_refs=["actor_lane_context.v1", "visible_scene_output.blocks.v1"],
        rejected_reasons=[actor_lane_reason] if actor_lane_status == "rejected" and actor_lane_reason else [],
    ))

    # Dramatic validation decision
    decisions.append(TraceableDecision(
        decision_id=_make_decision_id(session_id, turn_number, "dramatic_validation"),
        decision_type="dramatic_validation",
        story_session_id=session_id,
        turn_number=turn_number,
        status=dramatic_status if dramatic_status in ("approved", "rejected") else "approved",
        trace_span_name="dramatic_validation",
        input_refs=["visible_scene_output.blocks.v1", "passivity_validation.v1"],
        rejected_reasons=[dramatic_reason] if dramatic_status == "rejected" and dramatic_reason else [],
    ))

    # Commit decision
    decisions.append(TraceableDecision(
        decision_id=_make_decision_id(session_id, turn_number, "commit"),
        decision_type="engine_commit",
        story_session_id=session_id,
        turn_number=turn_number,
        status="accepted" if commit_applied else "rejected",
        trace_span_name="commit_seam",
        input_refs=["narrative_commit.v1", "validation_outcome.v1"],
        selected_output_ref="committed_state.v1" if commit_applied else "",
        rejected_reasons=[] if commit_applied else ["validation_rejected_before_commit"],
    ))

    return decisions


def build_diagnostics_envelope(
    *,
    session_id: str,
    turn_number: int,
    trace_id: str,
    player_input: str,
    runtime_projection: dict[str, Any],
    graph_state: dict[str, Any],
    scene_turn_envelope: dict[str, Any] | None,
    langfuse_trace_id: str = "",
    langfuse_enabled: bool = False,
    degradation_events: list[DegradationEvent] | None = None,
) -> DiagnosticsEnvelope:
    """Build a DiagnosticsEnvelope from committed turn data.

    Only uses committed state — never raw AI proposals.
    """
    proj = runtime_projection if isinstance(runtime_projection, dict) else {}
    human_actor_id = str(proj.get("human_actor_id") or "").strip()
    npc_actor_ids = [
        str(a) for a in (proj.get("npc_actor_ids") or [])
        if str(a).strip()
    ]
    selected_player_role = str(proj.get("selected_player_role") or "").strip()
    content_module_id = str(proj.get("content_module_id") or "god_of_carnage").strip()
    runtime_profile_id = str(proj.get("runtime_profile_id") or "god_of_carnage_solo").strip()
    runtime_module_id = str(proj.get("runtime_module_id") or "solo_story_runtime").strip()

    # Actor lane context
    ai_allowed = sorted(npc_actor_ids)
    ai_forbidden = [human_actor_id] if human_actor_id else []

    # Routing / generation
    routing = graph_state.get("routing") or {}
    gen = graph_state.get("generation") or {}
    gen_meta = gen.get("metadata") or {} if isinstance(gen.get("metadata"), dict) else {}
    val = graph_state.get("validation_outcome") or {}
    actor_lane_val = val.get("actor_lane_validation") or {} if isinstance(val.get("actor_lane_validation"), dict) else {}
    committed_result = graph_state.get("committed_result") or {} if isinstance(graph_state.get("committed_result"), dict) else {}

    ai_provider = str(routing.get("selected_provider") or "").strip()
    ai_model = str(routing.get("selected_model") or "").strip()
    adapter_used = str(gen_meta.get("adapter") or gen_meta.get("adapter_invocation_mode") or "").strip()
    fallback_stage = str(routing.get("fallback_stage_reached") or "primary_only").strip()
    structured_output_present = bool(gen.get("structured_output") is not None or gen_meta.get("structured_output") is not None)

    actor_lane_status = str(actor_lane_val.get("status") or val.get("status") or "").strip()
    actor_lane_reason = str(actor_lane_val.get("reason") or "").strip()

    dramatic_status = str(val.get("status") or "").strip()
    dramatic_reason = str(val.get("reason") or "").strip()

    commit_applied = bool(committed_result.get("commit_applied"))

    quality_class_val = str(graph_state.get("quality_class") or "").strip()
    degradation_signals_raw = graph_state.get("degradation_signals") or []
    degradation_signals = [str(s) for s in degradation_signals_raw if s]

    # Primary/secondary responders from actor turn summary or scene envelope
    scene_npc_agency = {}
    scene_ldss_diag = {}
    scene_block_count = 0
    primary_responder_id = ""
    secondary_responder_ids: list[str] = []

    if isinstance(scene_turn_envelope, dict):
        scene_npc_agency = scene_turn_envelope.get("diagnostics", {}).get("npc_agency", {}) or {}
        scene_ldss_diag = scene_turn_envelope.get("diagnostics", {}).get("live_dramatic_scene_simulator", {}) or {}
        blocks = scene_turn_envelope.get("visible_scene_output", {}).get("blocks", [])
        scene_block_count = len(blocks) if isinstance(blocks, list) else 0
        primary_responder_id = str(scene_npc_agency.get("primary_responder_id") or "").strip()
        secondary_responder_ids = [
            str(r) for r in (scene_npc_agency.get("secondary_responder_ids") or [])
            if str(r).strip()
        ]

    # If no scene envelope, try graph state
    if not primary_responder_id:
        primary_responder_id = str(graph_state.get("responder_id") or "").strip()

    # LDSS diagnostics section
    ldss_diag: dict[str, Any] = {
        "status": scene_ldss_diag.get("status") or "not_invoked",
        "invoked": bool(scene_ldss_diag.get("invoked")),
        "entrypoint": scene_ldss_diag.get("entrypoint") or "story.turn.execute",
        "simulator_version": "ldss.v1",
        "decision_count": int(scene_ldss_diag.get("decision_count") or 0),
        "output_contract": "visible_scene_output.blocks.v1",
        "input_hash": str(scene_ldss_diag.get("input_hash") or ""),
        "output_hash": str(scene_ldss_diag.get("output_hash") or ""),
    }

    # NPC agency section
    npc_agency_diag: dict[str, Any] = {
        "agency_required": bool(npc_actor_ids),
        "active_npc_ids": list(npc_actor_ids),
        "primary_responder_id": primary_responder_id,
        "secondary_responder_ids": secondary_responder_ids,
        "npc_to_npc_dialogue_present": bool(secondary_responder_ids),
        "visible_actor_response_required": True,
        "visible_actor_response_present": bool(scene_npc_agency.get("visible_actor_response_present")),
        "passivity_guard_status": "passed" if scene_npc_agency.get("visible_actor_response_present") else "unknown",
        "validation_status": "approved" if scene_npc_agency.get("visible_actor_response_present") else "unknown",
    }

    # Frontend render contract section
    frontend_contract: dict[str, Any] = {
        "version": "dramatic_chat_blocks.v1",
        "scene_block_count": scene_block_count,
        "render_mode": "typewriter",
        "typewriter_enabled": True,
        "legacy_blob_used": bool(scene_ldss_diag.get("legacy_blob_used", False)),
    }

    # Quality section
    quality_outcome = "ok"
    if quality_class_val in ("degraded",):
        quality_outcome = "ok_with_degradation"
    elif quality_class_val in ("failed",):
        quality_outcome = "failed"

    quality_diag: dict[str, Any] = {
        "outcome": quality_outcome,
        "quality_class": quality_class_val or "unknown",
        "degradation_signals": list(degradation_signals),
    }

    # Build traceable decisions
    decisions = build_traceable_decisions(
        session_id=session_id,
        turn_number=turn_number,
        actor_lane_status=actor_lane_status,
        actor_lane_reason=actor_lane_reason,
        dramatic_status=dramatic_status,
        dramatic_reason=dramatic_reason,
        commit_applied=commit_applied,
        primary_responder_id=primary_responder_id,
        human_actor_id=human_actor_id,
    )

    # Langfuse status
    if langfuse_enabled and langfuse_trace_id:
        lf_status = "traced"
    elif langfuse_enabled:
        lf_status = "enabled_no_trace"
    else:
        lf_status = "disabled"

    return DiagnosticsEnvelope(
        trace_id=trace_id or "",
        story_session_id=session_id,
        turn_number=turn_number,
        content_module_id=content_module_id,
        runtime_profile_id=runtime_profile_id,
        runtime_module_id=runtime_module_id,
        selected_player_role=selected_player_role,
        human_actor_id=human_actor_id,
        npc_actor_ids=npc_actor_ids,
        ai_allowed_actor_ids=ai_allowed,
        ai_forbidden_actor_ids=ai_forbidden,
        player_input_hash=_hash_text(player_input) if player_input else "",
        player_input_length=len(player_input) if player_input else 0,
        ai_provider=ai_provider,
        ai_model=ai_model,
        adapter_used=adapter_used,
        fallback_stage=fallback_stage,
        structured_output_present=structured_output_present,
        actor_lane_validation_status=actor_lane_status,
        actor_lane_validation_reason=actor_lane_reason,
        primary_responder_id=primary_responder_id,
        secondary_responder_ids=secondary_responder_ids,
        dramatic_validation_status=dramatic_status,
        dramatic_validation_reason=dramatic_reason,
        accepted_delta_count=len(decisions),
        rejected_delta_count=0,
        commit_applied=commit_applied,
        response_packaged_from_committed_state=True,
        quality_class=quality_class_val,
        degradation_signals=degradation_signals,
        langfuse_status=lf_status,
        langfuse_trace_id=langfuse_trace_id if langfuse_enabled else "",
        traceable_decisions=decisions,
        live_dramatic_scene_simulator=ldss_diag,
        npc_agency=npc_agency_diag,
        frontend_render_contract=frontend_contract,
        quality=quality_diag,
        degradation_timeline=degradation_events or [],
    )


# ---------------------------------------------------------------------------
# Local trace exporter (generates trace evidence for test runs)
# ---------------------------------------------------------------------------

def build_local_trace_export(
    *,
    story_session_id: str,
    turn_number: int,
    trace_id: str,
    generated_by_test: str = "test_mvp04_langfuse_trace_created_when_enabled",
    export_dir: str | None = None,
    langfuse_enabled: bool = False,
) -> LocalTraceExport:
    """Build a LocalTraceExport record for this test run.

    Not a static fixture — generated by real test execution with matching IDs.
    """
    test_run_id = f"pytest-run-{datetime.now(timezone.utc).strftime('%Y-%m-%dT%H-%M-%SZ')}"
    generated_at = datetime.now(timezone.utc).isoformat()

    required_spans = [
        "story.turn.execute",
        "actor_lane_context",
        "live_dramatic_scene_simulator",
        "actor_lane_validation",
        "dramatic_validation",
        "commit_seam",
        "package_output",
    ]

    export = LocalTraceExport(
        evidence_type="local_trace_export",
        generated_by_test=generated_by_test,
        source_test_run_id=test_run_id,
        generated_at=generated_at,
        story_session_id=story_session_id,
        turn_number=turn_number,
        trace_id=trace_id,
        static_fixture=False,
        metadata_match=True,
        same_test_run_as_live_response=True,
        required_spans_present=required_spans,
        langfuse_status="traced" if langfuse_enabled else "disabled",
    )

    # Write to export directory if provided
    if export_dir:
        export_path = Path(export_dir) / f"goc_turn_trace_{story_session_id}_{turn_number}.json"
        export_path.parent.mkdir(parents=True, exist_ok=True)
        export.export_path = str(export_path)
        with open(export_path, "w") as f:
            json.dump(export.to_dict(), f, indent=2)

    return export


# ---------------------------------------------------------------------------
# NarrativeGovSummary builder
# ---------------------------------------------------------------------------

def envelope_dict_to_response(envelope_dict: dict[str, Any], context: str = "operator") -> dict[str, Any]:
    """Apply to_response logic to an envelope dict (without reconstructing the object).

    context="operator"    → tiered visibility (hashes + costs redacted)
    context="langfuse"    → full technical data (debug_payload excluded)
    context="super_admin" → everything unredacted
    """
    result = envelope_dict.copy()
    if context == "super_admin":
        return result
    # debug_payload NIEMALS in Langfuse oder Operator
    result.pop("debug_payload", None)
    if context == "langfuse":
        return result
    # Operator: hashes und costs redacten
    if "live_dramatic_scene_simulator" in result:
        result["live_dramatic_scene_simulator"] = result["live_dramatic_scene_simulator"].copy()
        result["live_dramatic_scene_simulator"]["input_hash"] = "[REDACTED]"
        result["live_dramatic_scene_simulator"]["output_hash"] = "[REDACTED]"
    result["player_input_hash"] = "[REDACTED]"
    result["cost_summary"] = "[REDACTED]"
    # degradation_timeline: span_ids redacten
    if "degradation_timeline" in result:
        result["degradation_timeline"] = [
            {**event, "span_ids": "[REDACTED]"}
            for event in result.get("degradation_timeline", [])
        ]
    return result


def build_narrative_gov_summary(
    *,
    content_module_id: str = "god_of_carnage",
    runtime_profile_id: str = "god_of_carnage_solo",
    runtime_module_id: str = "solo_story_runtime",
    last_story_session_id: str = "",
    last_turn_number: int = 0,
    last_trace_id: str = "",
    ldss_status: str = "not_invoked",
    scene_block_count: int = 0,
    legacy_blob_used: bool = False,
    human_actor_id: str = "",
    npc_actor_ids: list[str] | None = None,
    quality_class: str = "",
    degradation_signals: list[str] | None = None,
    runtime_config_source: str = "",
) -> NarrativeGovSummary:
    """Build NarrativeGovSummary from real session diagnostics."""
    npcs = npc_actor_ids or []
    signals = degradation_signals or []

    content_health = {
        "content_module_id": content_module_id,
        "status": "canonical_loaded",
        "story_truth_present": True,
        "source": f"content.modules.{content_module_id}",
    }

    profile_health = {
        "runtime_profile_id": runtime_profile_id,
        "status": "profile_only",
        "story_truth_present": False,
        "source": f"runtime.profiles.{runtime_profile_id}",
    }

    module_health = {
        "runtime_module_id": runtime_module_id,
        "status": "runtime_logic_only",
        "story_truth_present": False,
    }

    ldss_health = {
        "status": ldss_status,
        "last_trace_id": last_trace_id,
        "last_session_id": last_story_session_id,
        "last_turn_number": last_turn_number,
        "evidenced": ldss_status == "evidenced_live_path",
    }

    frontend_health = {
        "status": "ready_for_frontend" if scene_block_count > 0 else "no_turns_yet",
        "scene_block_count": scene_block_count,
        "legacy_blob_used": legacy_blob_used,
    }

    actor_lane_health = {
        "human_actor_id": human_actor_id or "not_yet_assigned",
        "npc_actor_ids": list(npcs),
        "visitor_present": False,
        "enforcement_active": bool(human_actor_id),
    }

    degradation_status = "normal"
    if signals:
        degradation_status = "degraded" if quality_class != "failed" else "failed"

    degradation_health = {
        "quality_class": quality_class or "unknown",
        "degradation_signals": list(signals),
        "status": degradation_status,
        "last_degradation_reason": signals[0] if signals else "",
    }

    return NarrativeGovSummary(
        content_module_id=content_module_id,
        runtime_profile_id=runtime_profile_id,
        runtime_module_id=runtime_module_id,
        last_trace_id=last_trace_id,
        last_story_session_id=last_story_session_id,
        last_turn_number=last_turn_number,
        content_module_health=content_health,
        runtime_profile_health=profile_health,
        runtime_module_health=module_health,
        ldss_health=ldss_health,
        frontend_render_contract_health=frontend_health,
        actor_lane_health=actor_lane_health,
        degradation_health=degradation_health,
    )
