"""
Auto-generated tests for data_export_service
Generated by .ollama/test_generator.py
"""

import pytest
from app.services.data_export_service import *
from app.models import User, Role
from app.extensions import db

# Fixtures from conftest.py
# - app: Flask test app
# - client: Test client
# - db: Database session
# - test_user: Pre-created test user
# - auth_headers: JWT headers for test_user



# ── Generated Tests ──────────────────────────────────────────────────────────

"""Data export service tests - GDPR-compliant export"""

def test_export_has_metadata(app):
    """Full export includes versioned metadata."""
    from app.services.data_export_service import export_full
    result = export_full()
    assert result is not None
    assert "metadata" in result
    assert "data" in result
    assert result["metadata"].get("format_version") is not None
    assert result["metadata"].get("exported_at") is not None

def test_export_metadata_has_version(app):
    """Export metadata includes format version."""
    from app.services.data_export_service import export_full
    result = export_full()
    assert result["metadata"]["format_version"] == 1

def test_export_metadata_has_exported_at(app):
    """Export metadata includes ISO exported_at timestamp."""
    from app.services.data_export_service import export_full
    result = export_full()
    metadata = result["metadata"]
    assert metadata["exported_at"] is not None
    # Should be ISO format
    from datetime import datetime
    datetime.fromisoformat(metadata["exported_at"])

def test_export_excludes_alembic_version(app):
    """Export excludes internal alembic_version table."""
    from app.services.data_export_service import export_full
    result = export_full()
    assert "alembic_version" not in result["data"]["tables"]

def test_table_export_returns_dict(app):
    """Single-table export returns dict with metadata and data."""
    from app.services.data_export_service import export_table
    result = export_table("users")
    assert isinstance(result, dict)
    assert "metadata" in result
    assert "data" in result
    assert "tables" in result["data"]
    # All rows should be dicts
    for row in result["data"]["tables"]["users"]:
        assert isinstance(row, dict)

def test_table_export_serializes_datetime(app, test_user):
    """DateTime values are serialized to ISO format."""
    from app.services.data_export_service import export_table
    result = export_table("users")
    rows = result["data"]["tables"]["users"]
    if rows and "created_at" in rows[0]:
        assert isinstance(rows[0]["created_at"], str)

def test_row_export_returns_single_row(app, test_user):
    """Row-level export returns single row data."""
    from app.services.data_export_service import export_table_rows
    user_obj, _ = test_user
    result = export_table_rows("users", [user_obj.id])
    assert isinstance(result, dict)
    assert "metadata" in result
    assert "data" in result
    rows = result["data"]["tables"]["users"]
    assert len(rows) == 1
    assert rows[0]["id"] == user_obj.id

def test_row_export_by_multiple_ids(app, test_user):
    """Row export with multiple IDs returns multiple rows."""
    from app.services.data_export_service import export_table_rows
    user_obj, _ = test_user
    # Assuming at least test_user exists
    result = export_table_rows("users", [user_obj.id])
    assert isinstance(result, dict)
    rows = result["data"]["tables"]["users"]
    assert len(rows) >= 1

def test_serialize_row_converts_datetime(app):
    """Datetime values are converted to ISO strings."""
    from app.services.data_export_service import _serialize_row
    from datetime import datetime
    row = {"id": 1, "created_at": datetime.now()}
    result = _serialize_row(row)
    assert isinstance(result["created_at"], str)
    assert "T" in result["created_at"]

def test_collect_rows_by_pk(app, test_user):
    """Collect rows filters by primary key values."""
    from app.services.data_export_service import _collect_rows
    from app.extensions import db
    user_obj, _ = test_user
    table = db.metadata.tables.get("users")
    if table is not None:
        result = _collect_rows(table, where_ids=[user_obj.id])
        assert isinstance(result, list)



# ── Helper Functions (if needed) ───────────────────────────────────────────

# Add service-specific helpers here if needed
