"""
Auto-generated tests for data_import_service
Generated by .ollama/test_generator.py
"""

import pytest
from app.services.data_import_service import *
from app.models import User, Role
from app.extensions import db

# Fixtures from conftest.py
# - app: Flask test app
# - client: Test client
# - db: Database session
# - test_user: Pre-created test user
# - auth_headers: JWT headers for test_user



# ── Generated Tests ──────────────────────────────────────────────────────────

"""Data import service tests - validation, conflict detection, import"""

def test_preflight_rejects_invalid_payload(app):
    """Invalid payload fails preflight validation."""
    from app.services.data_import_service import preflight_validate_payload
    result = preflight_validate_payload("not a dict")
    assert result.ok is False
    assert len(result.issues) > 0

def test_preflight_requires_metadata(app):
    """Missing metadata section fails validation."""
    from app.services.data_import_service import preflight_validate_payload
    payload = {"data": {"tables": {}}}
    result = preflight_validate_payload(payload)
    assert result.ok is False

def test_preflight_requires_format_version(app):
    """Missing format_version fails validation."""
    from app.services.data_import_service import preflight_validate_payload
    payload = {
        "metadata": {"schema_revision": "", "exported_at": "2024-01-01T00:00:00"},
        "data": {"tables": {}}
    }
    result = preflight_validate_payload(payload)
    assert result.ok is False
    found_version_issue = any(
        issue.code == "UNSUPPORTED_FORMAT_VERSION"
        for issue in result.issues
    )
    assert found_version_issue

def test_preflight_validates_format_version(app):
    """Unsupported format_version is detected."""
    from app.services.data_import_service import preflight_validate_payload
    payload = {
        "metadata": {
            "format_version": 999,
            "schema_revision": "",
            "exported_at": "2024-01-01T00:00:00"
        },
        "data": {"tables": {}}
    }
    result = preflight_validate_payload(payload)
    assert result.ok is False
    found_version_issue = any(
        issue.code == "UNSUPPORTED_FORMAT_VERSION"
        for issue in result.issues
    )
    assert found_version_issue

def test_preflight_valid_minimal_payload(app):
    """Valid minimal payload passes validation."""
    from app.services.data_import_service import preflight_validate_payload
    payload = {
        "metadata": {
            "format_version": 1,
            "schema_revision": "",
            "exported_at": "2024-01-01T00:00:00"
        },
        "data": {"tables": {}}
    }
    result = preflight_validate_payload(payload)
    # May have schema revision warning but should not be fatal (ok=True or issues with non-blocking codes)
    assert isinstance(result.ok, bool)

def test_parse_datetime_from_iso_string(app):
    """ISO datetime strings are parsed correctly."""
    from app.services.data_import_service import _parse_datetime_if_needed
    from sqlalchemy import Column, DateTime
    from datetime import datetime

    col = Column(DateTime)
    value = "2024-01-15T10:30:00"
    result = _parse_datetime_if_needed(col, value)
    assert isinstance(result, datetime)

def test_parse_datetime_none(app):
    """None values remain None."""
    from app.services.data_import_service import _parse_datetime_if_needed
    from sqlalchemy import Column, DateTime

    col = Column(DateTime)
    result = _parse_datetime_if_needed(col, None)
    assert result is None

def test_parse_datetime_non_datetime_column(app):
    """Non-datetime columns pass through unchanged."""
    from app.services.data_import_service import _parse_datetime_if_needed
    from sqlalchemy import Column, String

    col = Column(String)
    value = "some_string"
    result = _parse_datetime_if_needed(col, value)
    assert result == value

def test_get_table_exists(app):
    """Get table by name returns table if exists."""
    from app.services.data_import_service import _get_table
    table = _get_table("users")
    assert table is not None

def test_get_table_not_found(app):
    """Get non-existent table returns None."""
    from app.services.data_import_service import _get_table
    table = _get_table("nonexistent_table_xyz")
    assert table is None

def test_get_table_excludes_alembic(app):
    """Get table rejects alembic_version table."""
    from app.services.data_import_service import _get_table
    table = _get_table("alembic_version")
    assert table is None



# ── Helper Functions (if needed) ───────────────────────────────────────────

# Add service-specific helpers here if needed
