"""
Auto-generated tests for user_service
Generated by .ollama/test_generator.py
"""

import hashlib
from datetime import datetime, timedelta, timezone

import pytest
from werkzeug.security import generate_password_hash

from app.extensions import db
from app.models import NewsArticle, Role, User
from app.models.email_verification_token import PURPOSE_ACTIVATION
from app.models.password_reset_token import PasswordResetToken
from app.services import user_service as us
from app.services.user_service import *

# Fixtures from conftest.py
# - app: Flask test app
# - client: Test client
# - db: Database session
# - test_user: Pre-created test user
# - auth_headers: JWT headers for test_user



# ── Generated Tests ──────────────────────────────────────────────────────────

"""User service tests - authentication, validation, lookup"""

def test_validate_password_valid(app):
    """Valid password passes validation."""
    from app.services.user_service import validate_password
    result = validate_password("ValidPass123")
    assert result is None  # None means valid

def test_validate_password_invalid_length(app):
    """Short password fails validation."""
    from app.services.user_service import validate_password
    result = validate_password("Short1")
    assert result is not None
    assert "at least" in result.lower()

def test_validate_password_missing_uppercase(app):
    """Password without uppercase fails."""
    from app.services.user_service import validate_password
    result = validate_password("lowercase123")
    assert result is not None
    assert "uppercase" in result.lower()

def test_validate_password_missing_lowercase(app):
    """Password without lowercase fails."""
    from app.services.user_service import validate_password
    result = validate_password("UPPERCASE123")
    assert result is not None
    assert "lowercase" in result.lower()

def test_validate_password_missing_digit(app):
    """Password without digits fails."""
    from app.services.user_service import validate_password
    result = validate_password("NoDigitsHere")
    assert result is not None
    assert "digit" in result.lower()

def test_get_user_by_username_found(app, test_user):
    """Get user by username returns correct user."""
    from app.services.user_service import get_user_by_username
    user_obj, _ = test_user
    user = get_user_by_username(user_obj.username)
    assert user is not None
    assert user.id == user_obj.id
    assert user.username == user_obj.username

def test_get_user_by_username_case_insensitive(app, test_user):
    """Username lookup is case-insensitive."""
    from app.services.user_service import get_user_by_username
    user_obj, _ = test_user
    user = get_user_by_username(user_obj.username.upper())
    assert user is not None
    assert user.id == user_obj.id

def test_get_user_by_username_not_found(app):
    """Non-existent username returns None."""
    from app.services.user_service import get_user_by_username
    user = get_user_by_username("nonexistent_user_xyz")
    assert user is None

def test_verify_user_incorrect_password(app, test_user):
    """Login with wrong password fails."""
    from app.services.user_service import verify_user
    user_obj, _ = test_user
    user = verify_user(user_obj.username, "WrongPassword123")
    assert user is None

def test_get_user_by_email_found(app, test_user_with_email):
    """Get user by email returns correct user."""
    from app.services.user_service import get_user_by_email
    user_obj, _ = test_user_with_email
    user = get_user_by_email(user_obj.email)
    assert user is not None
    assert user.id == user_obj.id

def test_get_user_by_email_case_insensitive(app, test_user_with_email):
    """Email lookup is case-insensitive."""
    from app.services.user_service import get_user_by_email
    user_obj, _ = test_user_with_email
    user = get_user_by_email(user_obj.email.upper())
    assert user is not None
    assert user.id == user_obj.id

def test_get_user_by_email_not_found(app):
    """Non-existent email returns None."""
    from app.services.user_service import get_user_by_email
    user = get_user_by_email("nonexistent@example.com")
    assert user is None


def test_validate_email_format_non_string():
    ok, msg = us.validate_email_format(123)  # type: ignore[arg-type]
    assert ok is False
    assert "required" in msg.lower()


def test_validate_password_too_long():
    pw = "Aa1" + "x" * 126  # 129 chars
    err = us.validate_password(pw)
    assert err and "at most" in err.lower()


def test_get_user_lookups_reject_bad_types(app):
    with app.app_context():
        assert us.get_user_by_username(None) is None
        assert us.get_user_by_username(1) is None  # type: ignore[arg-type]
        assert us.get_user_by_email(None) is None
        assert us.get_user_by_email(1) is None  # type: ignore[arg-type]


def test_verify_user_rejects_none_password(app, test_user):
    with app.app_context():
        u, _ = test_user
        assert us.verify_user(u.username, None) is None  # type: ignore[arg-type]


def test_get_user_by_id_branches(app, test_user):
    with app.app_context():
        u, _ = test_user
        assert us.get_user_by_id(None) is None
        assert us.get_user_by_id("nope") is None  # type: ignore[arg-type]
        assert us.get_user_by_id(999_999_999) is None
        assert us.get_user_by_id(u.id).id == u.id


def test_update_user_last_seen_branches(app, test_user):
    with app.app_context():
        uid = test_user[0].id
        u = db.session.get(User, uid)
        assert u is not None
        us.update_user_last_seen(None)
        us.update_user_last_seen("bad")  # type: ignore[arg-type]
        us.update_user_last_seen(999_999_999)

        u.last_seen_at = None
        db.session.commit()
        us.update_user_last_seen(u.id)
        db.session.refresh(u)
        first = u.last_seen_at
        assert first is not None

        us.update_user_last_seen(u.id)
        db.session.refresh(u)
        assert u.last_seen_at == first

        past = datetime.now(timezone.utc) - timedelta(seconds=us.LAST_SEEN_THROTTLE_SECONDS + 10)
        u.last_seen_at = past.replace(tzinfo=None)
        db.session.commit()
        us.update_user_last_seen(u.id)
        db.session.refresh(u)
        assert u.last_seen_at is not None
        assert u.last_seen_at != past


def test_list_users_with_search_and_pagination(app, test_user):
    with app.app_context():
        u, _ = test_user
        role = Role.query.filter_by(name=Role.NAME_USER).first()
        db.session.add(
            User(
                username="other_list_user",
                password_hash=generate_password_hash("Testpass1"),
                role_id=role.id,
            )
        )
        db.session.commit()

        rows, total = us.list_users(page=1, per_page=10, search=u.username[:4])
        assert total >= 1
        assert any(r.id == u.id for r in rows)

        rows2, total2 = us.list_users(page=99, per_page=1, search=None)
        assert total2 >= 2
        assert rows2 == []


def test_create_user_validation_errors(app):
    with app.app_context():
        u, err = us.create_user("", "Testpass1")
        assert u is None and err

        u2, err2 = us.create_user("x", "Testpass1")
        assert u2 is None and "at least 2" in (err2 or "")

        u3, err3 = us.create_user("bad!", "Testpass1")
        assert u3 is None and "invalid" in (err3 or "").lower()


def test_reset_and_verification_tokens(app, test_user_with_email):
    with app.app_context():
        uid = test_user_with_email[0].id
        u = db.session.get(User, uid)
        assert u is not None
        assert us.get_valid_reset_token("") is None
        assert us.reset_password_with_token("not-a-real-token", "Newpass123")[0] is False

        raw = us.create_password_reset_token(u)
        old_hash = u.password_hash
        ok, err = us.reset_password_with_token(raw, "Newpass123")
        assert ok and err is None
        u = db.session.get(User, uid)
        assert u is not None
        assert u.password_hash != old_hash

        raw_v = us.create_email_verification_token(u, ttl_hours=24)
        us.invalidate_existing_verification_tokens(u, PURPOSE_ACTIVATION)
        assert us.get_valid_verification_token(raw_v) is None

        raw_v2 = us.create_email_verification_token(u, ttl_hours=24)
        u.email_verified_at = None
        db.session.commit()
        ok_v, err_v = us.verify_email_with_token(raw_v2)
        assert ok_v and err_v is None
        u = db.session.get(User, uid)
        assert u is not None
        assert u.email_verified_at is not None


def test_expired_password_reset_token_not_accepted(app, test_user):
    with app.app_context():
        u = db.session.get(User, test_user[0].id)
        assert u is not None
        raw = "clear-token-for-test"
        th = hashlib.sha256(raw.encode()).hexdigest()
        old = datetime.now(timezone.utc) - timedelta(hours=2)
        db.session.add(
            PasswordResetToken(user_id=u.id, token_hash=th, created_at=old, used=False)
        )
        db.session.commit()
        assert us.get_valid_reset_token(raw) is None


def test_validate_password_complexity_requires_special_when_not_testing(app):
    with app.app_context():
        pw = "Abcdefghijklm1"
        prev = app.config["TESTING"]
        try:
            app.config["TESTING"] = False
            ok, msg = us.validate_password_complexity(pw)
            assert ok is False
            assert "special" in msg.lower()
        finally:
            app.config["TESTING"] = prev


def test_update_user_preferred_language_and_clear_email(app, test_user_with_email):
    with app.app_context():
        u = db.session.get(User, test_user_with_email[0].id)
        assert u is not None
        out, err = us.update_user(u.id, preferred_language="xx")
        assert out is None and err and "language" in err.lower()

        out2, err2 = us.update_user(u.id, preferred_language="de")
        assert err2 is None and out2.preferred_language == "de"

        out3, err3 = us.update_user(u.id, email="")
        assert err3 is None
        db.session.refresh(out3)
        assert out3.email is None


def test_delete_user_clears_news_author(app, test_user):
    with app.app_context():
        u = db.session.get(User, test_user[0].id)
        assert u is not None
        now = datetime.now(timezone.utc)
        article = NewsArticle(
            author_id=u.id,
            status="draft",
            default_language="de",
            created_at=now,
            updated_at=now,
        )
        db.session.add(article)
        db.session.commit()
        uid = u.id
        ok, err = us.delete_user(uid)
        assert ok and err is None
        a = db.session.get(NewsArticle, article.id)
        assert a.author_id is None


def test_activity_helpers_none_user_id():
    assert us.count_user_threads(None) == 0
    assert us.count_user_posts(None) == 0
    assert us.count_user_bookmarks(None) == 0
    assert us.get_user_recent_threads(None) == []
    assert us.get_user_recent_posts(None) == []
    assert us.get_user_bookmarks(None) == ([], 0)
    assert us.get_user_tags(None) == []


def test_change_password_missing_current(app, test_user):
    with app.app_context():
        u = db.session.get(User, test_user[0].id)
        assert u is not None
        out, err = us.change_password(u.id, current_password="", new_password="Newpass123")
        assert out is None and "required" in (err or "").lower()
