"""
Auto-generated tests for user_service
Generated by .ollama/test_generator.py
"""

import pytest
from app.services.user_service import *
from app.models import User, Role
from app.extensions import db

# Fixtures from conftest.py
# - app: Flask test app
# - client: Test client
# - db: Database session
# - test_user: Pre-created test user
# - auth_headers: JWT headers for test_user



# ── Generated Tests ──────────────────────────────────────────────────────────

"""User service tests - authentication, validation, lookup"""

def test_validate_password_valid(app):
    """Valid password passes validation."""
    from app.services.user_service import validate_password
    result = validate_password("ValidPass123")
    assert result is None  # None means valid

def test_validate_password_invalid_length(app):
    """Short password fails validation."""
    from app.services.user_service import validate_password
    result = validate_password("Short1")
    assert result is not None
    assert "at least" in result.lower()

def test_validate_password_missing_uppercase(app):
    """Password without uppercase fails."""
    from app.services.user_service import validate_password
    result = validate_password("lowercase123")
    assert result is not None
    assert "uppercase" in result.lower()

def test_validate_password_missing_lowercase(app):
    """Password without lowercase fails."""
    from app.services.user_service import validate_password
    result = validate_password("UPPERCASE123")
    assert result is not None
    assert "lowercase" in result.lower()

def test_validate_password_missing_digit(app):
    """Password without digits fails."""
    from app.services.user_service import validate_password
    result = validate_password("NoDigitsHere")
    assert result is not None
    assert "digit" in result.lower()

def test_get_user_by_username_found(app, test_user):
    """Get user by username returns correct user."""
    from app.services.user_service import get_user_by_username
    user_obj, _ = test_user
    user = get_user_by_username(user_obj.username)
    assert user is not None
    assert user.id == user_obj.id
    assert user.username == user_obj.username

def test_get_user_by_username_case_insensitive(app, test_user):
    """Username lookup is case-insensitive."""
    from app.services.user_service import get_user_by_username
    user_obj, _ = test_user
    user = get_user_by_username(user_obj.username.upper())
    assert user is not None
    assert user.id == user_obj.id

def test_get_user_by_username_not_found(app):
    """Non-existent username returns None."""
    from app.services.user_service import get_user_by_username
    user = get_user_by_username("nonexistent_user_xyz")
    assert user is None

def test_verify_user_incorrect_password(app, test_user):
    """Login with wrong password fails."""
    from app.services.user_service import verify_user
    user_obj, _ = test_user
    user = verify_user(user_obj.username, "WrongPassword123")
    assert user is None

def test_get_user_by_email_found(app, test_user_with_email):
    """Get user by email returns correct user."""
    from app.services.user_service import get_user_by_email
    user_obj, _ = test_user_with_email
    user = get_user_by_email(user_obj.email)
    assert user is not None
    assert user.id == user_obj.id

def test_get_user_by_email_case_insensitive(app, test_user_with_email):
    """Email lookup is case-insensitive."""
    from app.services.user_service import get_user_by_email
    user_obj, _ = test_user_with_email
    user = get_user_by_email(user_obj.email.upper())
    assert user is not None
    assert user.id == user_obj.id

def test_get_user_by_email_not_found(app):
    """Non-existent email returns None."""
    from app.services.user_service import get_user_by_email
    user = get_user_by_email("nonexistent@example.com")
    assert user is None



# ── Helper Functions (if needed) ───────────────────────────────────────────

# Add service-specific helpers here if needed
