"""List MVP files mapped MIGRATE_DIRECT whose active destination path is missing.

Reads ``raw/mvp_source_file_manifest.tsv`` from the canonical bundle and reuses the
same destination heuristics as ``tools/mvp_reintegration_intake.py``. Emits a Markdown
report for forward-integration triage (MVP-only assets that never landed in active).

The **original** for that tooling lives at repository root in ``'fy'-suites/`` (literal
directory name including quotes): migration and rules suites (Contractify, Docify,
Despaghettify, Postmanify, etc.) **belong to this repo** and are maintained there — not
under `backend/` or game product trees. Rows in the emitted report whose destination is
under ``'fy'-suites/`` mean the active checkout is **missing a path** that still exists under
``MVP/'fy'-suites/`` (worth reconciling for tooling parity). On some hosts, only the **deepest**
paths may fail to copy or check out; shallower files that exist are authoritative for those
paths.

Paths containing the nested snapshot artefact ``'fy'-suites/'fy'-suites/`` are skipped.

Usage (from repository root)::

    python scripts/mvp_forward_integration_candidates.py
    python scripts/mvp_forward_integration_candidates.py --max-rows 500
"""

from __future__ import annotations

import argparse
import importlib.util
import sys
from pathlib import Path


def _load_intake_module(repo_root: Path):
    path = repo_root / "tools" / "mvp_reintegration_intake.py"
    name = "mvp_reintegration_intake_dyn"
    spec = importlib.util.spec_from_file_location(name, path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"cannot load {path}")
    mod = importlib.util.module_from_spec(spec)
    sys.modules[name] = mod
    spec.loader.exec_module(mod)
    return mod


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo-root", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--max-rows", type=int, default=400, help="Cap rows written to the report body.")
    args = parser.parse_args()
    root = args.repo_root.resolve()
    mod = _load_intake_module(root)
    bundle = root / "docs" / "MVPs" / "MVP_World_Of_Shadows_Canonical_Implementation_Bundle"
    tsv = bundle / "raw" / "mvp_source_file_manifest.tsv"
    if not tsv.is_file():
        raise SystemExit(f"missing manifest: {tsv}")

    candidates: list[tuple[str, str, int]] = []
    with tsv.open(encoding="utf-8") as fh:
        header = fh.readline()
        if not header.startswith("relative_path"):
            raise SystemExit("unexpected manifest header")
        for line in fh:
            parts = line.rstrip("\n").split("\t")
            if len(parts) < 1 or not parts[0]:
                continue
            rel = parts[0].replace("\\", "/")
            size = int(parts[1]) if len(parts) > 1 and parts[1].isdigit() else 0
            cls, dest, _note = mod._destination_for(rel)
            if cls != "MIGRATE_DIRECT" or dest in ("n/a", ""):
                continue
            # Nested duplicate suite prefix inside MVP snapshots — not a real forward target.
            if "'fy'-suites/'fy'-suites/" in rel or "'fy'-suites/'fy'-suites/" in dest:
                continue
            dst = root.joinpath(*dest.split("/"))
            if dst.exists():
                continue
            candidates.append((rel, dest, size))

    out = bundle / "forward_integration_candidates.md"
    lines = [
        "# forward_integration_candidates",
        "",
        "Generated by `scripts/mvp_forward_integration_candidates.py` using the same heuristics as `tools/mvp_reintegration_intake.py` (`_destination_for`).",
        "",
        "Each row is an **MVP-relative** path classified **MIGRATE_DIRECT** whose mapped **active** destination path **does not exist** yet (neither file nor directory).",
        "These are candidates for **forward** integration (copy or merge from `MVP/` into the active tree), not snapshot alignment from active → `MVP/`.",
        "",
        "The **canonical original** for migration and rules tooling is **`'fy'-suites/`** at the repository root (intended for this repo). Many rows point there: they flag tooling files the MVP snapshot still holds while the active tree is missing them (e.g. checkout or export limits, or path-length issues affecting only the deepest leaves).",
        "",
        "For **governed import of MVP bundle content** (normalized trees under `mvpify/imports/<id>/normalized`, docs mirrored under `docs/MVPs/imports/<id>`, orchestration across fy suites), use **`mvpify`** — see [`'fy'-suites/mvpify/README.md`](../../../'fy'-suites/mvpify/README.md) relative to this bundle folder. Prefer that suite over unstructured bulk copies from this table.",
        "",
        "Paths containing the bogus nested prefix `'fy'-suites/'fy'-suites/` are excluded (snapshot artefact).",
        "",
        f"**Total candidates:** {len(candidates)}",
        "",
        "| MVP relative path | mapped active destination | size_bytes |",
        "|---|---|---|",
    ]
    for rel, dest, size in sorted(candidates)[: args.max_rows]:
        lines.append(f"| `MVP/{rel}` | `{dest}` | {size} |")
    if len(candidates) > args.max_rows:
        lines.append("")
        lines.append(f"_Listing truncated to {args.max_rows} rows; rerun with `--max-rows` to raise the cap._")
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(
        f"wrote {out.relative_to(root)} rows={min(len(candidates), args.max_rows)} "
        f"total_candidates={len(candidates)} (excludes nested 'fy'-suites/'fy'-suites/ paths)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
