"""
Branching system for World of Shadows.

Provides decision point management, path state tracking, and outcome divergence measurement.
"""

from .decision_point import (
    DecisionPoint, DecisionPointType, DecisionOption, DecisionPointRegistry
)
from .path_state import PathState, PathNode, PathStateManager
from .consequence_filter import ConsequenceFilter, ConsequenceFact
from .outcome_divergence import OutcomeDivergence, DivergenceMetric, DivergenceScore
from .forecast import (
    BRANCHING_FORECAST_SCHEMA_VERSION,
    BRANCHING_FORECAST_SOURCE,
    build_branching_forecast,
)
from .branch_tree import (
    BRANCHING_TREE_RECORD_SCHEMA_VERSION,
    BRANCHING_TREE_RECORD_SOURCE,
    BRANCHING_TREE_STATUS_COMMITTED,
    BRANCHING_TREE_STATUS_EXPIRED,
    BRANCHING_TREE_STATUS_NOT_APPLICABLE,
    BRANCHING_TREE_STATUS_SIMULATED,
    BRANCHING_TREE_STATUS_STALE,
    branch_tree_is_fresh,
    branch_tree_path_nodes,
    find_branch_tree_node,
    make_branch_tree_record,
    mark_branch_tree_committed,
    mark_branch_tree_expired,
    mark_branch_tree_stale,
    selectable_simulation_nodes,
)
from .branch_timeline import (
    BRANCHING_TIMELINE_DEFAULT_MAX_ACTIVE_TREES,
    BRANCHING_TIMELINE_DEFAULT_MAX_EVENTS,
    BRANCHING_TIMELINE_DEFAULT_MAX_TREE_REFERENCES,
    BRANCHING_TIMELINE_EVENT_NODE_SELECTED,
    BRANCHING_TIMELINE_EVENT_SCHEMA_VERSION,
    BRANCHING_TIMELINE_EVENT_SELECTION_REPLAY_COMMITTED,
    BRANCHING_TIMELINE_EVENT_SELECTION_REPLAY_CONFLICT,
    BRANCHING_TIMELINE_EVENT_SELECTION_REPLAY_STARTED,
    BRANCHING_TIMELINE_EVENT_TIMELINE_ARCHIVED,
    BRANCHING_TIMELINE_EVENT_TIMELINE_COMPACTED,
    BRANCHING_TIMELINE_EVENT_TREE_BECAME_STALE,
    BRANCHING_TIMELINE_EVENT_TREE_CREATED,
    BRANCHING_TIMELINE_EVENT_TREE_EXPIRED,
    BRANCHING_TIMELINE_EVENT_TYPES,
    BRANCHING_TIMELINE_RECORD_SCHEMA_VERSION,
    BRANCHING_TIMELINE_RECORD_SOURCE,
    BRANCHING_TIMELINE_SCOPE_ACTIVE,
    BRANCHING_TIMELINE_SCOPE_PREVIEW,
    BRANCHING_TIMELINE_SCOPES,
    BRANCHING_TIMELINE_SNAPSHOT_SCHEMA_VERSION,
    BRANCHING_TIMELINE_STATUS_ACTIVE,
    BRANCHING_TIMELINE_STATUS_ARCHIVED,
    BRANCHING_TIMELINE_STATUSES,
    append_branch_timeline_event,
    archive_branch_timeline,
    build_branch_timeline_snapshot,
    compact_branch_timeline,
    default_branch_timeline_bounds,
    make_branch_timeline_event,
    make_branch_timeline_record,
    normalize_branch_timeline_bounds,
    stable_branch_timeline_id,
)
from .simulation_tree import (
    BRANCHING_SIMULATION_TREE_SCHEMA_VERSION,
    BRANCHING_SIMULATION_TREE_SOURCE,
    append_simulation_node,
    clamp_simulation_limits,
    finalize_simulation_tree,
    forecast_has_options,
    make_simulated_turn_node,
    make_simulation_tree,
    simulated_input_for_branch_option,
)

__all__ = [
    'DecisionPoint',
    'DecisionPointType',
    'DecisionOption',
    'DecisionPointRegistry',
    'PathState',
    'PathNode',
    'PathStateManager',
    'ConsequenceFilter',
    'ConsequenceFact',
    'OutcomeDivergence',
    'DivergenceMetric',
    'DivergenceScore',
    'BRANCHING_FORECAST_SCHEMA_VERSION',
    'BRANCHING_FORECAST_SOURCE',
    'build_branching_forecast',
    'BRANCHING_TREE_RECORD_SCHEMA_VERSION',
    'BRANCHING_TREE_RECORD_SOURCE',
    'BRANCHING_TREE_STATUS_COMMITTED',
    'BRANCHING_TREE_STATUS_EXPIRED',
    'BRANCHING_TREE_STATUS_NOT_APPLICABLE',
    'BRANCHING_TREE_STATUS_SIMULATED',
    'BRANCHING_TREE_STATUS_STALE',
    'branch_tree_is_fresh',
    'branch_tree_path_nodes',
    'find_branch_tree_node',
    'make_branch_tree_record',
    'mark_branch_tree_committed',
    'mark_branch_tree_expired',
    'mark_branch_tree_stale',
    'selectable_simulation_nodes',
    'BRANCHING_TIMELINE_DEFAULT_MAX_ACTIVE_TREES',
    'BRANCHING_TIMELINE_DEFAULT_MAX_EVENTS',
    'BRANCHING_TIMELINE_DEFAULT_MAX_TREE_REFERENCES',
    'BRANCHING_TIMELINE_EVENT_NODE_SELECTED',
    'BRANCHING_TIMELINE_EVENT_SCHEMA_VERSION',
    'BRANCHING_TIMELINE_EVENT_SELECTION_REPLAY_COMMITTED',
    'BRANCHING_TIMELINE_EVENT_SELECTION_REPLAY_CONFLICT',
    'BRANCHING_TIMELINE_EVENT_SELECTION_REPLAY_STARTED',
    'BRANCHING_TIMELINE_EVENT_TIMELINE_ARCHIVED',
    'BRANCHING_TIMELINE_EVENT_TIMELINE_COMPACTED',
    'BRANCHING_TIMELINE_EVENT_TREE_BECAME_STALE',
    'BRANCHING_TIMELINE_EVENT_TREE_CREATED',
    'BRANCHING_TIMELINE_EVENT_TREE_EXPIRED',
    'BRANCHING_TIMELINE_EVENT_TYPES',
    'BRANCHING_TIMELINE_RECORD_SCHEMA_VERSION',
    'BRANCHING_TIMELINE_RECORD_SOURCE',
    'BRANCHING_TIMELINE_SCOPE_ACTIVE',
    'BRANCHING_TIMELINE_SCOPE_PREVIEW',
    'BRANCHING_TIMELINE_SCOPES',
    'BRANCHING_TIMELINE_SNAPSHOT_SCHEMA_VERSION',
    'BRANCHING_TIMELINE_STATUS_ACTIVE',
    'BRANCHING_TIMELINE_STATUS_ARCHIVED',
    'BRANCHING_TIMELINE_STATUSES',
    'append_branch_timeline_event',
    'archive_branch_timeline',
    'build_branch_timeline_snapshot',
    'compact_branch_timeline',
    'default_branch_timeline_bounds',
    'make_branch_timeline_event',
    'make_branch_timeline_record',
    'normalize_branch_timeline_bounds',
    'stable_branch_timeline_id',
    'BRANCHING_SIMULATION_TREE_SCHEMA_VERSION',
    'BRANCHING_SIMULATION_TREE_SOURCE',
    'append_simulation_node',
    'clamp_simulation_limits',
    'finalize_simulation_tree',
    'forecast_has_options',
    'make_simulated_turn_node',
    'make_simulation_tree',
    'simulated_input_for_branch_option',
]
