"""add updated_at column to users table

Revision ID: 038
Revises: 037
Create Date: 2026-03-26 13:16:39.613455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '038'
down_revision = '037'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('actor_username_snapshot', sa.String(length=80), nullable=True),
    sa.Column('actor_role_snapshot', sa.String(length=20), nullable=True),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('message', sa.String(length=512), nullable=True),
    sa.Column('route', sa.String(length=256), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('target_type', sa.String(length=64), nullable=True),
    sa.Column('target_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_logs_category'), ['category'], unique=False)

    with op.batch_alter_table('forum_thread_tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_forum_thread_tags_tag_id'), ['tag_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_forum_thread_tags_thread_id'), ['thread_id'], unique=False)

    with op.batch_alter_table('game_experience_templates', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_game_experience_templates_slug'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_game_experience_templates_template_id'), type_='unique')
        batch_op.create_index(batch_op.f('ix_game_experience_templates_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_game_experience_templates_template_id'), ['template_id'], unique=True)

    with op.batch_alter_table('password_histories', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'roles', ['role_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'roles', ['role_id'], ['id'])
        batch_op.drop_column('is_active')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('password_histories', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('game_experience_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_experience_templates_template_id'))
        batch_op.drop_index(batch_op.f('ix_game_experience_templates_slug'))
        batch_op.create_unique_constraint(batch_op.f('uq_game_experience_templates_template_id'), ['template_id'])
        batch_op.create_unique_constraint(batch_op.f('uq_game_experience_templates_slug'), ['slug'])

    with op.batch_alter_table('forum_thread_tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_forum_thread_tags_thread_id'))
        batch_op.drop_index(batch_op.f('ix_forum_thread_tags_tag_id'))

    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_logs_category'))
        batch_op.drop_index(batch_op.f('ix_activity_logs_action'))

    op.drop_table('activity_logs')
    # ### end Alembic commands ###
